Dockerfile
web/Dockerfile

Added dockerfiles because I can see how they might come in handy ;)

Added Dockerfiles

---

exchanges/bitfinex/bitfinex_websocket.go

I can see too much bugs in this code that's why I am starting new project.
I hope I can encourage you to contribute - https://github.com/crackcomm/crypto-exchanges

Bitfinex: handle read message error

---

config/config.go
exchanges/gdax/gdax.go
exchanges/gemini/gemini.go

Allow users to run the bot in sandbox mode, so we can test out new functionality

consistent access to sandbox environments on gemini and gdax

---

config_example.json
exchanges/okex/okex.go
exchanges/okex/okex_test.go
exchanges/okex/okex_types.go
testdata/configtest.json

This is a base support PR for OKEX, more functionality will be added at a later time ad hoc. All PR's are welcome on exchange branches.

Added support for Okex

---

README.md
config/config_test.go
config_example.json
exchange.go
exchanges/bitflyer/bitflyer.go
exchanges/bitflyer/bitflyer_test.go
exchanges/bitflyer/bitflyer_types.go
exchanges/bitflyer/bitflyer_wrapper.go
testdata/configtest.json

Authenticated requests not done due to the fact I could not get an adequate account.

Added support for Bitflyer exchange

---

README.md

As discussed on slack, here is the updated exchange API info.
Supporting links
https://github.com/BTCMarkets/API/wiki/websocket
https://www.bitstamp.net/fix/
https://docs.gemini.com/websocket-api/
https://docs.gemini.com/fix-api/
https://hitbtc.com/fix
https://api.itbit.com/fix

Update Exchange Support Table.

---

exchanges/bitfinex/bitfinex.go
exchanges/bitfinex/bitfinex_test.go
exchanges/bitfinex/bitfinex_types.go
exchanges/bitfinex/bitfinex_wrapper_test.go
exchanges/request/request.go
exchanges/request/request_test.go

Includes:
- Rate limit parameters for authenticated and unauthenticated exchange requests
- http.Client so you can set exchange specific params 
Future considerations:
- Monitoring service (already started) for exchange errors and requests to see overall achievement.

New request package

---

exchanges/gdax/gdax.go

Hi, This time i just submit the fix (hopefully my git does not pull other files this time). Maybe you can delete my previous pull request since that seemed to open another can of worms with these data races. (I will create a issue on that)

Fix for type assertion in Historic Rates in gdax.go

---

exchanges/localbitcoins/localbitcoins.go
routines.go

Interim update before work on asynchronous engine development. Windows review needed.

Update to test handling of async fetching through request handler package.

---

web/package.json
web/src/app/pages/settings/settings.component.html
web/src/app/shared/classes/config.ts

Fixes broken front-end after merge of: https://github.com/thrasher-/gocryptotrader/pull/126
Updates to new JSON config

Supports updated JSON config

---

routines.go

Just ran
gofmt -w .
on the project root. That's all.
https://blog.golang.org/go-fmt-your-code
---
> I made this PR with a project going on over at https://github.com/rotblauer/gofmt-att, and it's definitely a work in progress. So if I got something wrong, or this is annoying at all, please file an issue over there and we'll sort it out. On the other hand, if you think it's kind of funny like I do, please feel welcome to contribute or even fire up one of your own great automatic _gofmt_ers.

gofmt project

---

.gitignore

Added some improvement to prevent build/test ouptuts to end up in repo.

Added golang gitignore lines to prevent committing build outputs

---

exchanges/okex/okex.go
exchanges/okex/okex_test.go

Fixed issue with okex

---

config/config.go
config_example.json
testdata/configtest.json

To have all the json start with a lowercase I added the annotations on the models. This way the json responses on rest api are more aligned with REST Standards + the fact someone can use the json objects in javascript in such way the json is still compliant with javascript coding standards.

Lowercase json to be more compliant with javascript coding standards

---

exchanges/kraken/kraken.go
exchanges/kraken/kraken_test.go
exchanges/kraken/kraken_types.go
exchanges/kraken/kraken_wrapper.go
exchanges/localbitcoins/localbitcoins.go
exchanges/localbitcoins/localbitcoins_types.go

Hi,
I've completed the private part of Kraken API, it works, I already do some trading with this stuff.
I also fixed some LocalBitcoins bugs. 
Please review.
btw: Good job, all you guys! keep on!

Kraken rework + localbitcoins fixes

---

web/package-lock.json

NPM auditing warns there are currently vulnerabilities in master web project
After npm audit fix
Demonstration that the application still loads and runs with no console errors after compilation:
Signed-off-by: Scott Grant <scott.grant@thrasher.io>

Fixes frontend security issues

---

communications/communications_test.go
communications/slack/slack_test.go
communications/telegram/telegram_test.go

Improving telegram Setup test
More coverage for telegram PushEvent test
Adding telegram HandleMessages test
Adding telegram GetUpdates test
Adding telegram TestConnection test
Adding telegram SendMessage test
(Hopefully) completely fixed race conditions with slack testing

Telegram testing and race condition fix.

---

config/config.go
config/config_test.go

More coverage for GetExchangeBankAccounts test
More coverage for UpdateExchangeBankAccounts test
Adding CheckClientBankAccounts test
Fixing bug in CheckClientBankAccounts
Adding CheckCommunicationsConfig test
Fixing bugs in CheckCommunicationsConfig
Adding CheckPairConsistency test
Removing superfluous commas
More coverage for GetForexProviderConfig test
More coverage for GetPrimaryForexProvider

Improve config logic/testing

---

CONTRIBUTORS
README.md
exchanges/request/request.go
exchanges/request/request_test.go

Unit test: "https://httpstat.us/200?sleep=20000" end point to sleep before reply

Requester update

---

exchanges/coinbasepro/coinbasepro.go

Fixed Sandbox API URL for Coinbase Pro exchange.
`go test ./...`

CoinbasePro: fixed Sandbox API URL

---

exchanges/binance/binance.go
exchanges/binance/binance_test.go
exchanges/binance/binance_types.go

Hello it's my first PR here ! I don't know if I'm doing it fine, so don't hesitate to learn me how to do things the right way ! Cheers ! 
I added the GetAveragePrice function and the corresponding new filters from the last binance api changelog : https://github.com/binance-exchange/binance-official-api-docs/blob/master/CHANGELOG.md

Add GetAveragePrice function to the binance API

---

exchanges/poloniex/poloniex_websocket.go

Fixes ineffectual assignment issue

---

CONTRIBUTORS
README.md
tools/documentation/root_templates/root_readme.tmpl
tools/documentation/web_templates/web_readme.tmpl
web/README.md

Style guide link in README was dead. Fixed link to point to CONTRIBUTING.md

Fix code style link in readme to point to contributing doc

---

logger/logger_test.go

Fix bug in Logger test where it creates file but doesn't delete

---

exchanges/kraken/kraken.go
exchanges/kraken/kraken_test.go
exchanges/kraken/kraken_types.go

Fixes #235 
Test local package

Add functions and tests to kraken

---

codelingo.yaml

Fix issue with codelingo verbosity on test function comments

---

exchanges/gateio/gateio_types.go
exchanges/gateio/gateio_wrapper.go

fix UnmarshalJSON for gateio balances

GateIO: Account info - fix balance response

---

.golangci.yml
config/config.go
exchanges/anx/anx_wrapper.go
exchanges/binance/binance.go
exchanges/binance/binance_wrapper.go
exchanges/bitfinex/bitfinex_wrapper.go
exchanges/bithumb/bithumb_wrapper.go
exchanges/bitmex/bitmex_wrapper.go
exchanges/bittrex/bittrex_wrapper.go
exchanges/btcc/btcc_websocket.go
exchanges/btcmarkets/btcmarkets.go
exchanges/btcmarkets/btcmarkets_wrapper.go
exchanges/btse/btse_wrapper.go
exchanges/coinbasepro/coinbasepro_wrapper.go
exchanges/coinut/coinut_wrapper.go
exchanges/exchange.go
exchanges/gateio/gateio_wrapper.go
exchanges/gemini/gemini_wrapper.go
exchanges/hitbtc/hitbtc.go
exchanges/hitbtc/hitbtc_wrapper.go
exchanges/huobi/huobi_wrapper.go
exchanges/huobihadax/huobihadax_wrapper.go
exchanges/itbit/itbit_wrapper.go
exchanges/kraken/kraken.go
exchanges/kraken/kraken_wrapper.go
exchanges/localbitcoins/localbitcoins_wrapper.go
exchanges/okgroup/okgroup.go
exchanges/okgroup/okgroup_websocket.go
exchanges/okgroup/okgroup_wrapper.go

converted for loops from iterator value to iterator based on linter suggestions
Ran go test

Fix rangeValCopy linter issues 

---

exchanges/exchange.go

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change. 

find a unsuitable definition of a function

---

.travis.yml
common/common.go
common/common_test.go
config/config.go
logger/logger.go
logger/logger_test.go

Add in CI support for OS X and fixed tests
ci build test
Also did local test

Add OS X CI Matrix support to Travis

---

config/config.go
connchecker/connchecker.go
main.go

ipconfig /release /renew &&
literally pulling ethernet cable out of wall

Add in routine that checks internet connectivity for bot services

---

exchanges/okex/okex.go
exchanges/okgroup/okgroup_types.go

This fixes OKGroup and friends JSON unmarshalling issues after an API udpate.

OKGroup: Fix unmarshalling issues after API update

---

.appveyor.yml
config/config.go

This adds AppVeyor support to GCT specifically for testing the back and front end components of GCT targeting Windows.
Through AppVeyor

Add AppVeyor support

---

config/config.go

Fixes a typo in config.go from Emtpy to Empty
Go test ./...

Fixes typo in config.go

---

connchecker/connchecker.go
connchecker/connchecker_test.go
exchanges/okgroup/okgroup_websocket.go
main.go

Adds logic to ensure nothing proceeds a connectivity check and adds tests
go test ./...

Connection checker update

---

codelingo.yaml
common/common_test.go
exchanges/binance/binance.go
exchanges/bitfinex/bitfinex.go
exchanges/bitfinex/bitfinex_websocket.go
exchanges/bitstamp/bitstamp.go
exchanges/btcmarkets/btcmarkets.go
exchanges/coinbasepro/coinbasepro.go
exchanges/coinbasepro/coinbasepro_websocket.go
exchanges/coinbasepro/coinbasepro_wrapper.go
exchanges/coinut/coinut.go
exchanges/coinut/coinut_wrapper.go
exchanges/exchange.go
exchanges/exchange_websocket.go
exchanges/exmo/exmo.go
exchanges/gateio/gateio.go
exchanges/gemini/gemini.go
exchanges/hitbtc/hitbtc.go
exchanges/itbit/itbit.go
exchanges/lakebtc/lakebtc.go
exchanges/localbitcoins/localbitcoins.go
exchanges/okgroup/okgroup.go
exchanges/orders/orders.go
exchanges/poloniex/poloniex.go
exchanges/zb/zb.go
helpers_test.go

Replace non-nil zero-length slice declarations with nil slice declarations [as specified in Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#declaring-empty-slices).
Add [tenets](https://github.com/codelingo/codelingo/blob/master/tenets/codelingo/code-review-comments/declare-empty-slice/codelingo.yaml) to your [codelingo.yaml file](https://github.com/leilaes/gocryptotrader/blob/declare-empty-slice/codelingo.yaml#L8) to catch these issues during code review.
`go test -race -coverprofile=coverage.txt -covermode=atomic  ./...`. Although tests for zk.go failed due to `request canceled while waiting for connection` even on the master branch.

Replace a zero-length, non-nil slice with a nil slice

---

.travis.yml

This caches the golang pkg/mod dir.
Travis

Travis: Cache $GOPATH/pkg/mod

---

codelingo.yaml
communications/slack/slack.go
currency/storage.go
exchanges/kraken/kraken_websocket.go
exchanges/okgroup/okgroup_websocket.go
tools/exchange_template/exchange_template.go

Add missing close file and missing stop ticker.
Add [tenets](https://github.com/codelingo/codelingo/blob/master/tenets/codelingo/effective-go/defer-close-file/codelingo.yaml) to your [codelingo.yaml file](https://github.com/leilaes/gocryptotrader/blob/missing-closeFile-stopTicker/codelingo.yaml) to catch these issues during code review.
`go test -race -coverprofile=coverage.txt -covermode=atomic  ./...`.

Add missing close file and missing stop ticker

---

.appveyor.yml

This adds caching to AppVeyor builds, similar to what we've done with Travis.
https://ci.appveyor.com/project/thrasher-/gocryptotrader/builds/24750486

AppVeyor: Add cache

---

.appveyor.yml
.golangci.yml
Makefile
config/config_test.go
exchanges/btcmarkets/btcmarkets_wrapper.go
exchanges/btse/btse_websocket.go
exchanges/huobi/huobi_wrapper.go
exchanges/localbitcoins/localbitcoins_wrapper.go

Bump golangci-lint version to 1.16.0

---

communications/base/base_interface.go
communications/base/base_test.go

Added tests for communication/base package.

Unit tests for communication/base package

---

exchanges/alphapoint/alphapoint_wrapper.go
exchanges/bithumb/bithumb_wrapper.go
exchanges/bitmex/bitmex_wrapper.go
exchanges/bitstamp/bitstamp_wrapper.go
exchanges/btse/btse_wrapper.go
exchanges/exmo/exmo_wrapper.go
exchanges/gateio/gateio_wrapper.go
exchanges/gemini/gemini.go
exchanges/hitbtc/hitbtc_wrapper.go
exchanges/huobi/huobi_wrapper.go
exchanges/huobihadax/huobihadax_wrapper.go
exchanges/kraken/kraken_wrapper.go
exchanges/lakebtc/lakebtc_wrapper.go
exchanges/localbitcoins/localbitcoins_wrapper.go
exchanges/okgroup/okgroup_wrapper.go
exchanges/poloniex/poloniex.go
exchanges/poloniex/poloniex_wrapper.go
exchanges/yobit/yobit_wrapper.go
exchanges/zb/zb_wrapper.go

Fix some minor issues with logic that will try and cancel everything before returning error.

General fixes for CancelAllOrders exchange wrapper function

---

exchanges/btcmarkets/btcmarkets_types.go
exchanges/btcmarkets/btcmarkets_wrapper.go

Whilst working on engine branch, discovered this BTC Markets order JSON Unmarshal failure.

BTCMarkets: Fix order JSON unmarshal response

---

exchange.go
main.go

Started to do a bit of housekeeping and refactor main so it's no so busy.
Much easier to work on a project when you can clearly see its execution path.
clarity.
compiled
- [x ] My code follows the style guidelines of this project
- [ n/a] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool 
- [ x] My changes generate no new warnings
- [ n/a] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally and on Travis with my changes
- [ x] Any dependent changes have been merged and published in downstream modules

Refactor main.go to improve startup execution flow

---

exchanges/bithumb/bithumb.go
exchanges/bithumb/bithumb_types.go
exchanges/bithumb/bithumb_wrapper.go

API change occurred and broke type assertion. So fixed that and ticker type.
go test package

Bithumb fixes due to API change

---

exchanges/btse/btse_types.go
exchanges/btse/btse_websocket.go
exchanges/btse/btse_wrapper.go

Fixes various endpoint errors related to API updates for BTSE.

BTSE: Fix endpoint issues after API update

---

CONTRIBUTORS
README.md
cmd/documentation/root_templates/root_readme.tmpl
cmd/documentation/sub_templates/contributors.tmpl
cmd/gctcli/README.md
docs/EXCHANGE_API.md
docs/FILES.md
docs/README.md
gctrpc/README.md

Basic documentation update for gRPC/gctcli, root readme and a basic unified API doc with code examples.
Documentation update
Clicking on ALL THE LINKS

Basic documentation update for engine branch

---

exchanges/lbank/lbank.go
exchanges/lbank/lbank_test.go
exchanges/lbank/lbank_wrapper.go

Minor changes for LBank and its API Update
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change. 
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

Minor LBank Changes

---

exchanges/okgroup/okgroup_types.go

Fixes OKGroup GetFuturesContractInformationResponse json.Unmarshal wrong type issue.

OKEX: Fix OKGroup GetFuturesContractInformationResponse json.Unmarshal issue

---

.travis.yml
Makefile

Adds a 32 bit build job for Travis to ensure that our codebase works on 32 bit systems due to finding and resolving this issue:
https://github.com/thrasher-corp/gocryptotrader/pull/388
Travis CI and local testing on a 32 bit system

Add 32-bit linux build target for Travis

---

.gitignore
config/config.go
config/config_test.go
config_example.json
engine/syncer.go
main.go
testdata/configtest.json
testdata/preengine_config.json

1. Updates configs, stores an original pre-engine config for compatibility
2. Disables the gRPC JSON proxy by default
3. Uses sync item timeout instead of printing out wrong values
4. Removes useless config funcs/tests (we have GetPairFormat which does the same thing but with engine specific changes)

Engine pre-merge changes

---

exchanges/bittrex/bittrex.go
exchanges/bittrex/bittrex_types.go

Please include a summary of the change, feature or issue which this pull request addresses. Please also include relevant motivation and context. List any dependencies that are required for this change.
Bittrex GetDepositHistory method does not return all necessary fields (like Id, CryptoAddress, Confirmations) 
[x] My code follows the style guidelines of this project
[x] I have performed a self-review of my own code

Bittrex GetDepositHistory method return the new DepositHistory struct type

---

exchanges/bittrex/bittrex_test.go
exchanges/bittrex/bittrex_types.go

Quick PR to address ID capitilisation linting, int64 properties and cleans up some tests so that they work with and without API keys

LintFix: Bittrex properties and tests

---

engine/helpers.go
exchanges/bittrex/bittrex.go
exchanges/bittrex/bittrex_types.go

Fixed error in my previous PR 
Id field of DepositHistory type changed to int64

Bittrex - changed type of field "Id" in DepositHistory struct

---

exchanges/huobi/huobi.go
exchanges/huobi/huobi_test.go
exchanges/huobi/huobi_types.go
exchanges/huobi/huobi_wrapper.go
go.mod
go.sum

Adds Huobi deposit address and withdraw quota API support. Also performs some code deduplication and tidies go.mod/go.sum files after the dependabot depends merges

Huobi: Add deposit address and withdraw quota API support

---

exchanges/bitfinex/bitfinex.go
exchanges/bitfinex/bitfinex_test.go
exchanges/bitfinex/bitfinex_types.go

Implements the leaderboard API as per https://docs.bitfinex.com/reference#rest-public-rankings

Bitfinex: Implement leaderboard API

---

exchanges/bitmex/bitmex_wrapper.go
exchanges/exchange.go
exchanges/order/order_test.go
exchanges/order/orders.go

Bug-fixes: #459 #460

---

portfolio/portfolio_types.go

none
- [n/a] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [n/a] I have added tests that prove my fix is effective or that my feature works

Portfolio: Add XRPScan subtype with all fields implemented

---

exchanges/binance/binance.go
exchanges/binance/binance_test.go
exchanges/binance/binance_types.go
exchanges/mock/recording.go
testdata/http_mock/binance/binance.json

Including new fields for request/response and allowing test orders.

Binance: Update NewOrder API

---

go.sum
portfolio/portfolio.go

Fixes the XRP portfolio address test error

Bugfix: Fix XRP portfolio address test error

---

cmd/gctcli/commands.go
exchanges/kline/kline.go
exchanges/kline/kline_test.go

Some post merge fixes for issues I noticed with #479 
- Adds fifteensecond word support
- Improves test coverage for TotalCandlesPerInterval to confirm correct values are returned

(QoL) Kline fifteen second support & improved test coverage

---

exchanges/request/request.go
exchanges/request/request_test.go
exchanges/request/request_types.go

Add header response variable to request item, to specifically check header variables package side if needed. 

Requester: Add field variable to request item struct

---

exchanges/poloniex/poloniex.go
exchanges/poloniex/poloniex_websocket.go

Fixes panic in websocket as the endpoint sends different types.
Fixes nonce generation issue as it requires unixnano timestamp. 

Exchange: Poloniex fixes

---

codecov.yml

Adds a codecov config for greater setting flexibility (using default settings currently) plus annotations disabled to prevent spam when reviewing PRs.
- Pending PR request

Codecov: Add config plus disable annotations for PRs

---

engine/rpcserver.go
exchanges/kraken/kraken_websocket.go
exchanges/orderbook/orderbook.go

Please include a summary of the change, feature or issue which this pull request addresses. Please also include relevant motivation and context. List any dependencies that are required for this change.
Because of function GetSpecificOrderbook return a pointer of orderbook.Base - there was a race condition in method GetOrderbook (package engine), and I got the panic quite often here.

Orderbook/RPCServer: Fix GetOrderbook/Retrieve race condition (refactored and sped up)

---

.appveyor.yml
.golangci.yml
.travis.yml
Dockerfile
Makefile
cmd/exchange_wrapper_coverage/main.go
common/crypto/crypto.go
currency/coinmarketcap/coinmarketcap.go
currency/pairs.go
database/repository/withdraw/withdraw_test.go
exchanges/bitflyer/bitflyer.go
exchanges/bithumb/bithumb.go
exchanges/bithumb/bithumb_test.go
exchanges/coinbasepro/coinbasepro_types.go
exchanges/coinbasepro/coinbasepro_wrapper.go
exchanges/coinut/coinut.go
exchanges/kline/kline_test.go
exchanges/orderbook/orderbook_test.go
exchanges/stream/buffer/buffer_test.go
exchanges/ticker/ticker_test.go
gctscript/modules/ta/indicators/indicators_test.go
gctscript/wrappers/validator/validator.go
go.sum
web/Dockerfile

Updates our CI Go version depends to 1.15x and bumps golangci-lint to the latest version, including linter fixes.

Bump golangci-lint, Docker and Go CI versions

---

exchanges/ftx/ftx.go
exchanges/ftx/ftx_test.go
exchanges/ftx/ftx_wrapper.go

This PR includes bug fixes for FTX order placement/cancellation.

FTX: Fix order placement/cancellation issues

---

engine/engine_test.go

* enable a no longer failing test
Adjusting tests
Fixes nothing

engine: add a test for parallel bots

---

exchanges/ftx/ftx.go
exchanges/ftx/ftx_test.go
exchanges/ftx/ftx_types.go

Fixes various bugs in FTX;
1) JSON tag value and variable type mismatch.
2) Assumption of a URL encoded request not allowing for optional requests, which throws an error on authenticated endpoints. 
3) Wrong HTTP method for submitting margin lending offers.
4) Implement limit checks for tests
5) Improve test error checking
6) Usage of timestamps which are relevant to the market being tested
7) Mismatch between public/private endpoints
8) Allow for case insensitivity
- [N/A] Any dependent changes have been merged and published in downstream modules

FTX: Various bug fixes

---

exchanges/binance/binance_test.go
exchanges/binance/binance_types.go
exchanges/binance/binance_websocket.go
exchanges/binance/type_convert.go

A fix for missing data on the embedded structs when using an alias for unmarshalling for websocket data on Binance exchange.
- [n/a] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool

Binance: Fix websocket reponse unmarshal bug

---

exchanges/coinbene/coinbene.go
exchanges/coinbene/coinbene_test.go
exchanges/coinbene/coinbene_types.go
exchanges/coinbene/coinbene_wrapper.go
exchanges/coinbene/ratelimit.go
testdata/configtest.json

A new instruments method was introduced which allows us to use it instead of string indexing.
https://github.com/thrasher-corp/gocryptotrader/issues/662

Coinbene: Fix ticker pair parsing

---

cmd/documentation/currency_templates/fx.tmpl
cmd/documentation/currency_templates/fx_exchangeratehost.tmpl
config/config.go
config/config_test.go
config/config_types.go
currency/conversion_test.go
currency/currency_types.go
currency/forexprovider/exchangerate.host/README.md
currency/forexprovider/exchangerate.host/exchangerate.go
currency/forexprovider/exchangerate.host/exchangerate_test.go
currency/forexprovider/exchangerate.host/exchangerate_types.go
currency/forexprovider/exchangeratesapi.io/exchangeratesapi.go
currency/forexprovider/exchangeratesapi.io/exchangeratesapi_test.go
currency/forexprovider/exchangeratesapi.io/exchangeratesapi_types.go
currency/forexprovider/forexprovider.go
currency/storage.go
engine/engine.go
engine/engine_types.go
main.go

Adds a new default forex provider ExchangeRateHost.io due to ExchangeRateAPI disallowing APIkey free requests.

Currency: Add new forex provider exchangerate.host

---

engine/apiserver_types.go
engine/engine.go

Just noticed a potential slight improvement in the engine. Let me know what you guys think or if there are any problems with this.

engine: Set full state on settings struct

---

.golangci.yml
backtester/common/common_test.go
backtester/config/config_test.go
backtester/data/data_test.go

Slightly improves test coverage in some backtester packages.
- [] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool

backtester: Improve test coverage

---

.gitignore

Ignore coverage reports and debug executables, compiled by delve.

build: Enrich .gitignore

---

exchanges/bithumb/bithumb.go
exchanges/bithumb/bithumb_test.go
exchanges/bithumb/bithumb_wrapper.go
exchanges/order/limits.go

Adds basic limits for order execution. 

bithumb: Add basic exchange order execution limits

---

exchanges/binance/binance_test.go
exchanges/binance/binance_websocket.go
exchanges/order/order_types.go

- Set more fields of order.Detail
- "ExecutionReport" only provides "trade" status (partially filled), so check that executed amount == total amount before change status to filled

Binance websocket: Order Detail Execution Report

---

exchanges/bithumb/bithumb.go
exchanges/bithumb/bithumb_test.go
exchanges/bithumb/bithumb_types.go

Adds Missing API functionality: Assets status
This alerts caller of current withdrawal and deposit status. 

bithumb: Add missing functionality

---

communications/communications.go
dispatch/dispatch.go
engine/communication_manager_test.go
engine/connection_manager.go
engine/connection_manager_test.go
engine/helpers.go
engine/helpers_test.go
engine/ntp_manager.go
engine/ntp_manager_test.go
engine/ntp_manager_types.go
engine/rpcserver.go
gctscript/vm/manager.go

Fix GetSubsystemsStatus bug that was suppressing comm manager output via gctcli.

engine: GetSubsystemsStatus fix

---

exchanges/kraken/kraken_test.go

Fixes kraken tests that were failing. 

kraken: fix GetTrades test

---

exchanges/ftx/ftx_wrapper.go

FTX won't allow us to fetch balances for all accounts when
using a subaccount API key. Take subaccount config declarations into account when fetching balances.
- [] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool

ftx: honour subaccount setting when fetching balances

---

exchanges/binance/binance_cfutures.go
exchanges/binance/binance_test.go
exchanges/binance/binance_wrapper.go
exchanges/binance/cfutures_types.go
exchanges/binance/cfutures_types_test.go

Fixes submitssion of orders for coin margined futures on Binance.

exchanges/binance/coinm: fix order submission

---

exchanges/binance/binance_wrapper.go

If not instruments were enabled refrain from trying to be clever and
auto-enabling BTC/USDT.

binance: don't enable BTC/USDT instrument without user's knowledge

---

exchanges/huobi/huobi_cfutures.go
exchanges/huobi/huobi_futures.go

This uses the provided IsEmpty method to check if currency code or pair has been set. 

huobi: Use method IsEmpty

---

exchanges/ftx/ftx_test.go
exchanges/ftx/ftx_types.go

Add additional greek information.
Fixes #863 

ftx: add greek field support for GetFutureStats function

---

CONTRIBUTORS
LICENSE
README.md

Removes superfluous empty files. 

cmd: remove empty template files

---

exchanges/binance/binance_cfutures.go
exchanges/binance/binance_test.go
exchanges/binance/binance_wrapper.go
exchanges/binance/cfutures_types.go

Do not add it to the request unless filled out as the API will deny the
request otherwise.

binance_cfutures: TimeOnForce is an optional order submission field

---

exchanges/huobi/huobi_wrapper.go

huobi futures: add support for market orders

---

exchanges/btcmarkets/btcmarkets.go
exchanges/ftx/ftx_test.go
main.go

Fixes the current live tests on master. Note: 1.18 introduces a redundant newline check for things like fmt.Println which is why there was that change for main.go

exchanges: fix various tests

---

.github/dependabot.yml

The web front-end is currently deprecated and requires an overhaul due to EOL depend updates. This PR restricts updates up until the front-end code is updated.

Dependabot: Update config file to ignore web npm updates

---

exchanges/ftx/ftx_test.go
exchanges/ftx/ftx_wrapper.go

ftx: Add filter for negative orderbook values on bear tokens [REST]

---

engine/order_manager.go
exchanges/binance/binance_test.go
exchanges/btcmarkets/btcmarkets.go
exchanges/btcmarkets/btcmarkets_test.go
exchanges/btcmarkets/btcmarkets_types.go
exchanges/btcmarkets/btcmarkets_wrapper.go
exchanges/order/order_test.go
exchanges/order/order_types.go
exchanges/order/orders.go
exchanges/poloniex/poloniex_wrapper.go
gctscript/wrappers/gct/exchange/exchange_test.go
gctscript/wrappers/validator/validator_test.go

* Adds formatting methods.
* Change target amount to quote amount to make it a little bit more obvious and add commentary.
* Remove price and post only from json request when not needed. 

btcmarkets: update order submission

---

exchanges/btcmarkets/btcmarkets_test.go
exchanges/btcmarkets/btcmarkets_types.go
exchanges/btcmarkets/btcmarkets_wrapper.go

btcm: add order execution limit wrapper support

---

exchanges/request/request.go
exchanges/request/request_test.go
exchanges/request/request_types.go

WithVerbose adds verbosity to a request context so that specific requests can have distinct verbosity without impacting all requests.

request: adds WithVerbose function to package to add verbosity to request context

---

docs/ADD_NEW_EXCHANGE.md
engine/helpers.go
engine/helpers_test.go
engine/order_manager.go
engine/portfolio_manager.go
engine/rpcserver.go
exchanges/bittrex/bittrex_websocket.go
exchanges/btse/btse_websocket.go
exchanges/coinbasepro/coinbasepro_websocket.go
exchanges/credentials.go
exchanges/credentials_test.go
exchanges/exchange_types.go
exchanges/ftx/ftx.go
exchanges/ftx/ftx_websocket.go
exchanges/gateio/gateio_websocket.go
exchanges/gemini/gemini_websocket.go
exchanges/hitbtc/hitbtc_websocket.go
exchanges/huobi/huobi_websocket.go
exchanges/interfaces.go
exchanges/kraken/kraken_websocket.go
exchanges/okgroup/okgroup_websocket.go
exchanges/poloniex/poloniex_websocket.go
exchanges/sharedtestvalues/customex.go
exchanges/zb/zb_websocket.go

exchange: expose GetCredentials() and split GetAuthenticatedAPISupport()

---

engine/order_manager.go
engine/order_manager_test.go
exchanges/huobi/huobi_futures.go
exchanges/huobi/huobi_test.go
exchanges/huobi/huobi_wrapper.go
exchanges/order/order_test.go
exchanges/order/order_types.go
exchanges/order/orders.go

orders: Add method for creating cancel struct from order details

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml

Enable VScode dev container support with Go debugger setup.
None
New feature
Created a local dev container and ran make inside the container
also, consider improving test coverage whilst working on a certain feature or package.
No changes to the test as it does not affect the original codebase

build/dev: Add VSCode Devcontainer support

---

exchanges/binance/binance_test.go
exchanges/binance/binance_ufutures.go
exchanges/binance/binance_wrapper.go
exchanges/binance/ufutures_types.go

```go
// old version
func (b *Binance) UFuturesNewOrder(ctx context.Context, symbol currency.Pair, side, positionSide, orderType, timeInForce,
newClientOrderID, closePosition, workingType, newOrderRespType string,
quantity, price, stopPrice, activationPrice, callbackRate float64, reduceOnly bool)(UOrderData, error) {
}
// new version
func (b *Binance) UFuturesNewOrder(ctx context.Context, data *UFuturesNewOrderRequest)(UOrderData, error) {
}
type UFuturesNewOrderRequest struct {
Symbol           currency.Pair `json:"symbol"`
Side             string        `json:"side"`
PositionSide     string        `json:"position_side"`
OrderType        string        `json:"order_type"`
TimeInForce      string        `json:"time_in_force"`
NewClientOrderID string        `json:"new_client_order_id"` …
```

binance/perf: Optimize UFuturesNewOrder function parameters

---

engine/engine.go
engine/sync_manager.go
engine/sync_manager_test.go

engine: fix potential difference between exchange config name and default

---

exchanges/ftx/ftx.go
exchanges/ftx/ftx_test.go
exchanges/ftx/ftx_types.go

Adds support for FTX's hidden referral API endpoints 😆 
- Referral rebate codes
- Referral rebates
- Referral rebate history
- Referral rebate rate
Two were excluded due to lack of data / docs
- Referral fees
- Referral fee history

ftx: Add support for hidden referral API endpoints

---

backtester/btrpc/btrpc.proto
exchanges/bybit/bybit.go
exchanges/bybit/bybit_test.go
exchanges/bybit/bybit_types.go
exchanges/bybit/bybit_wrapper.go
exchanges/bybit/futures_type.go
gctrpc/rpc.proto

A minor PR to fix bybit test and buf format issues.

bybit/buf: Fix test issues

---

engine/event_manager.go

Minor fix in log output.
Tested when checking the functionality of gocryptotrader some months ago.

EventManager: log current SleepDelay

---

cmd/exchange_wrapper_coverage/main.go
exchanges/binance/binance_wrapper.go
exchanges/bybit/bybit_wrapper.go

Fix panic bug causes by exchange wrapper coverage by 
* Adding context value
* Bybit was missing a validation function call
* Binance was letting slip an invalid asset type so did a quick fix there and potential future update TODO

exchange_wrapper_coverage: deploy context value, fix panics.

---

cmd/exchange_wrapper_issues/main.go
cmd/exchange_wrapper_issues/wrapperconfig.json
exchanges/bitfinex/bitfinex_test.go
exchanges/bitfinex/bitfinex_wrapper.go

Adds empty pair check to reduce panic potential.

bitfinex: fix potential panic caused by wrapper issues cmd

---

backtester/eventhandlers/statistics/currencystatistics.go
backtester/eventhandlers/statistics/printresults.go
backtester/eventhandlers/strategies/dollarcostaverage/dollarcostaverage.go
backtester/eventhandlers/strategies/rsi/rsi.go
common/common.go
common/common_test.go
common/timeperiods/timeperiods.go
engine/rpcserver.go
exchanges/account/account.go
exchanges/bitfinex/bitfinex_websocket.go
exchanges/bitstamp/bitstamp_websocket.go
exchanges/bittrex/bittrex_websocket.go
exchanges/bybit/bybit_websocket.go
exchanges/bybit/bybit_ws_cfutures.go
exchanges/bybit/bybit_ws_futures.go
exchanges/bybit/bybit_ws_ufutures.go
exchanges/coinut/coinut_websocket.go
exchanges/gateio/gateio_websocket.go
exchanges/hitbtc/hitbtc_websocket.go
exchanges/huobi/huobi_websocket.go
exchanges/kraken/kraken.go
exchanges/kraken/kraken_websocket.go
exchanges/okx/okx.go
exchanges/okx/okx_websocket.go
exchanges/order/orders.go
exchanges/poloniex/poloniex_websocket.go
exchanges/trade/trade.go
exchanges/zb/zb_websocket.go

Unexport errors type to force inbuilt error interface usage across GCT, allows a better method of error type matching across multiple errors in line with the errors package handling instead of first match it will iterate across the entire list. 

common: update Errors type

---

exchanges/lbank/lbank_wrapper.go
exchanges/poloniex/poloniex_test.go
exchanges/poloniex/poloniex_wrapper.go

Filter pairs that are not enabled via front end and have no liquidity. 

poloniex: filter non-liquid and unused assets

---

exchanges/kraken/kraken.go
exchanges/kraken/kraken_types.go
exchanges/kraken/kraken_wrapper.go

Presence of API restricted currency pair which is now filtered out. 

kraken: when fetching tradable pairs filter by status

---

exchanges/hitbtc/hitbtc_test.go
exchanges/hitbtc/hitbtc_wrapper.go

Fixes issue storing tradable pairs, fetching tickers and matching to available. 

hitbtc: optimise fetching tradable pairs and tickers 

---

exchanges/exmo/exmo_test.go
exchanges/exmo/exmo_wrapper.go

* Refactor UpdateTickers 
* Qualified loading of tickers by tests with all available pairs for that asset type.  

exmo: refactor UpdateTickers function

---

exchanges/btcmarkets/btcmarkets_wrapper.go
exchanges/order/order_test.go
exchanges/order/orders.go

The `AdjustBaseAmount` method alerts if non-fatal change occurs exchange side
This also adjusts BTCM and adds in price to response. 

orders: Add AdjustBaseAmount 

---

exchanges/okx/okx.go
exchanges/okx/okx_test.go
exchanges/okx/okx_type_convert.go
exchanges/okx/okx_types.go
exchanges/okx/ratelimit.go

Updates asset -> new savings endpoint as per https://www.okx.com/docs-v5/log_en/#2023-03-15 as the old endpoints wouldn't action certain things.
Also expands the numerical value type to support more values as one of the new endpoints can return either a float or string for a given JSON key 😆

OKX: Update to new savings module

---

exchanges/okx/okx_websocket.go

instId is a required API field

Okx: Fix fundingRate sub not sending instId

---

exchanges/okx/okx_websocket.go

Ping handler for okx is not the RFC compat version gorilla would support. Even if it was, I think the UseGorillaHandler is broken/misconceived because it does not send keepalive pings, it responds to them.
This also increases the delay to 27, in keeping with the 30 second timeout documented.
I think this issue was hidden by the noisy default subs. When just using funding-rates, it showed straight away.

Okx: Fix ping handler

---

currency/pair_methods.go
currency/pair_test.go
currency/pair_types.go

* Derives pair association by having a similar currency code between pairs: 
* currency.NewPair(BTC, USDT).IsAssociated(currency.NewPair(BTC, USD)) returns true (BTC association)
* currency.NewPair(XRP, USDT).IsAssociated(currency.NewPair(BTC, USD)) returns false (no association)
* Exports error 
* Add field pair in OrderParameters.

currency: Add Pair method IsAssociated

---

exchanges/okx/okx.go
exchanges/okx/okx_test.go
exchanges/okx/okx_types.go

Add missing fee fields for USDC pairs.

okx: Add fee fields for USDC pairs

---

dispatch/dispatch_test.go

Fixes a dispatch test due to an old non-rebased test being referenced.

dispatch: Fix TestMuxPublish

---

exchanges/okx/okx_websocket.go

Implemented a web socket connection error on OKX
Please delete options that are not relevant and add an `x` in `[]` as the item is complete.

Okx: Log auth websocket connection errors

---

exchanges/bitfinex/bitfinex_websocket.go

Changes formatting so subscribe works for websocket.

bitfinex: fix websocket subscribing issue caused by formatting

---

exchanges/kraken/kraken.go
exchanges/kraken/kraken_test.go
exchanges/kraken/kraken_types.go
exchanges/kraken/kraken_wrapper.go

Kraken: Load order execution limits for tradable pairs

---

exchanges/kraken/kraken_websocket.go

Kraken: Fix ws orderType parsing

---

exchanges/order/orders.go

Orders: Fix Pending status not parsed

---

exchanges/kraken/kraken_wrapper.go

Kraken: Fix WS new order pair symbol format

---

exchanges/bitstamp/bitstamp_test.go
exchanges/bitstamp/bitstamp_type_convert.go
exchanges/bitstamp/bitstamp_types.go
exchanges/bitstamp/bitstamp_wrapper.go

Feature/Bitstamp: OrderExecutionLimits and testing

Bitstamp: Implement UpdateOrderExecutionLimits and testing

---

exchanges/bitfinex/bitfinex.go
exchanges/bitfinex/bitfinex_test.go
exchanges/bitfinex/bitfinex_types.go
exchanges/bitfinex/bitfinex_wrapper.go

Bitfinex: Order Execution Limits and Testing

Bitfinex: Implement UpdateOrderExecutionLimits and tests

---

exchanges/gateio/gateio_test.go
exchanges/gateio/gateio_wrapper.go

* Adds exchange limits and test

gateio: Implement UpdateOrderExecutionLimits for spot instruments 

---

exchanges/bitstamp/bitstamp_websocket.go

Bitstamp: Fix subscription_succeeded not handled

---

exchanges/bitfinex/bitfinex_wrapper.go

Fixes Type, Amount and Symbol for new order, and IsShort for modify order

Bitfinex: Fix websocket new/modify order fields

---

currency/pair_methods.go
exchanges/bithumb/bithumb_wrapper.go
exchanges/bitmex/bitmex_wrapper.go
exchanges/exchange.go
exchanges/gateio/gateio_convert.go
exchanges/gateio/gateio_test.go
exchanges/gateio/gateio_types.go
exchanges/gateio/gateio_websocket.go
exchanges/gateio/gateio_wrapper.go
exchanges/gateio/gateio_ws_futures.go
exchanges/gateio/gateio_ws_option.go
exchanges/okx/okx_wrapper.go

* Optimise unmarshal processes in some functions by using json.Rawmessage field. Prior was unmarshalling the same thing 3 times
* Fix processing of `spotOrderbookTickerChannel`
* Streamlined event response matching 
* Reduced allocations in `processOrderbookUpdate` and `processOrderbookSnapshot`
* Assign asset type to `stream.ChannelSubscription` type which was missing
* Batch outbound orderbook ticker so that every asset can be subscribed to immediately without initial sync interruption
also consider improving test coverage …

gateio: websocket updates

---

engine/subsystem_types.go
engine/sync_manager.go
engine/sync_manager_test.go
engine/websocketroutine_manager.go

As per the request in PR #1229, the Update was replaced with WebsocketUpdate

sync_manager: Rename Update to WebsocketUpdate

---

exchanges/fill/fill.go
exchanges/fill/fill_test.go
exchanges/gateio/gateio_test.go
exchanges/gateio/gateio_websocket.go
exchanges/gateio/gateio_wrapper.go
exchanges/gateio/gateio_ws_futures.go
exchanges/gateio/gateio_ws_option.go

Included unit tests for the fill package 
F
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works

exchanges/fill: Add test coverage

---

exchanges/bitfinex/bitfinex_websocket.go
exchanges/okx/okx_websocket.go

bitfinex,okx: Fix orderbook LastUpdate timestamps

---

exchanges/binance/binance.go
exchanges/binance/binance_test.go
exchanges/binance/binance_types.go
exchanges/binance/type_convert.go

Adds crypto/flexible loan support for Binanace

Binance: Add crypto/flexible loan endpoints

---

exchanges/bitfinex/bitfinex_websocket.go

Fix WebSocket configured more than once

Bitfinex: Ensure websocket configuration is sent with every connection

---

common/convert/convert.go
common/convert/convert_test.go
exchanges/gateio/gateio.go
exchanges/gateio/gateio_test.go
exchanges/gateio/gateio_types.go
exchanges/gateio/gateio_websocket.go
exchanges/gateio/gateio_wrapper.go
exchanges/gateio/gateio_ws_futures.go
exchanges/gateio/gateio_ws_option.go

Randomly errors: `json: invalid use of ,string struct tag, trying to unmarshal "" into float64`

gate.io: Enforce the use of 'convert.StringToFloat64' and permit its use in outbound requests

---

exchanges/okx/okx.go
exchanges/okx/okx_test.go
exchanges/okx/okx_types.go
exchanges/okx/okx_websocket.go
exchanges/okx/okx_wrapper.go

Bundle of Okx fixes for websockets.
Commit messages should provide adequate context.

Okx: Various websocket fixes

---

exchanges/bitfinex/bitfinex.go

Bitfinex: replace errTypeAssert with common.GetTypeAssertError

Bitfinex: replace errTypeAssert with common.GetTypeAssertError

---

exchanges/kline/weighted_price_test.go
exchanges/orderbook/depth_test.go
exchanges/orderbook/linked_list_test.go

Fixes floating point inaccuracies on different architectures Moves the depth tests over to table driven tests

Orderbook: Fix test failures on arm64

---

contrib/spellcheck/exclude_lines.txt
exchanges/okx/okx_types.go
exchanges/okx/okx_websocket.go
exchanges/okx/okx_wrapper.go

Change type float64 to convert.StringToFloat64

OKX: Change float64 to convert.StringtoFloat64 in okx_types

---

exchanges/bitstamp/bitstamp_test.go
exchanges/bitstamp/bitstamp_types.go
exchanges/bitstamp/bitstamp_wrapper.go
testdata/http_mock/bitstamp/bitstamp.json

GetWithdrawalRequests was erroring on parsing the date and time. TestGetWithdrawalRequests has been updated

Bitstamp: Fix GetWithdrawalRequests/GetWithdrawalsHistory date parsing and enhance test coverage

---

exchanges/kraken/kraken_test.go

Failed again due to kraken re-setting limits due to price increases. Switch from specific PriceStepIncrementSize and MinimumBaseAmount to just ensuring they are positive so we don't have to do this again

Kraken: Fix TestUpdateOrderExecutionLimits

---

exchanges/bitfinex/bitfinex_test.go
exchanges/btse/btse_test.go
exchanges/gateio/gateio_test.go
exchanges/okx/okx_test.go
internal/testing/exchange/exchange.go

Abstracts updatePairsOnce for use in several branches including #1482

Tests: Abstract UpdatePairsOnce

---

exchanges/bithumb/bithumb_test.go

Update the tests to ensure all are passing as well as to increase the coverage.
Tests the require subscription were not enhanced due to the inability to test it.

Bithumb: Enhance testing coverage

---

exchanges/bybit/bybit_types.go
exchanges/bybit/bybit_wrapper.go

Bybit has Solana options now. To allow everyone to use puts on SOL, I've implemented it here.
Sadly Bybit doesn't have an API endpoint that says what options they support 😕 
I also ensure that we retrieve all options in a loop

Bybit: Solana options

---

currency/manager.go
exchanges/exchange.go
exchanges/exchange_test.go

Resolves intermittent deadlock observed in CI builds. [Example](https://github.com/thrasher-corp/gocryptotrader/actions/runs/9120973131/job/25079360158?pr=1082#step:10:279)

currency/manager: remove deadlock potential in concurrent operations

---

exchanges/bybit/bybit_test.go
exchanges/bybit/bybit_types.go

Bybit: Add missing field min notional

---

.github/workflows/tests.yml
backtester/eventhandlers/exchange/slippage/slippage_test.go
common/file/file_test.go
config/config_test.go
exchanges/gateio/gateio.go

Fixes the following test issues:
1) GateIO 64bit alignment for 32bit systems
2) Intermittent 1/20 chance failure of TestRandomSlippage
3) Skips docker specific tests due to its very relaxed filesystem

tests: Fix various issues

---

exchanges/gateio/gateio_convert.go
exchanges/gateio/gateio_test.go

There was some inconsistent values being parse, this attempts to rectify time issues. And also makes it a little bit speedier.  

gateio: fix and optimise time

---

exchanges/bybit/bybit_wrapper.go

Small change to the `exchanges/bybit/bybit_wrapper.go` file. The change adds a new field to the `GetWithdrawalsHistory` function to include the cryptocurrency chain information.
* [`exchanges/bybit/bybit_wrapper.go`](diffhunk://#diff-80edbb8d99f55568a9e2b618e852698548cd8093ee256cea007d713e7b664e13R682): Added the `CryptoChain` field to the `GetWithdrawalsHistory` function to include the chain information of the withdrawal.# PR Description
Please include a summary of the change, feature or issue which this pull request addresses. Please also include relevant motivation and context. List any dependencies that are required for this change.
- [x ] New feature (non-breaking change which adds functionality)
Please describe the tests that you ran to verify your changes. Provide …

Bybit: Add CryptoChain field to GetWithdrawalsHistory wrapper

---

exchanges/huobi/huobi_wrapper.go

Notified by @Vlomzzz that values were swapped. 

huobi: ticker swap amount and volume values

---

exchanges/bitmex/bitmex_test.go
exchanges/bitmex/bitmex_websocket.go
exchanges/bitmex/bitmex_websocket_types.go
exchanges/bitmex/bitmex_wrapper.go
exchanges/exchange.go
testdata/configtest.json

* Add subscription templating
* Upgrade test config
* Remove deprecated Upside/Downside Profit contracts

Bitmex: Subscription templating

---

exchanges/bybit/bybit_inverse_websocket.go
exchanges/bybit/bybit_linear_websocket.go
exchanges/bybit/bybit_options_websocket.go
exchanges/bybit/bybit_test.go
exchanges/bybit/bybit_websocket.go
exchanges/bybit/bybit_wrapper.go
exchanges/orderbook/depth.go
exchanges/orderbook/depth_test.go
exchanges/orderbook/orderbook_types.go
exchanges/stream/buffer/buffer.go
exchanges/subscription/subscription.go

* Adds subscription configuration
* Adds candles to the default subs
This PR does not touch any of the assets that aren't used by the engine by default.
It just fixes the default subs for the only available asset for the websocket as it would normally run.

Bybit: Add subscription configuration for spot

---

exchanges/gateio/gateio.go
exchanges/gateio/gateio_test.go
exchanges/gateio/gateio_types.go
exchanges/gateio/gateio_wrapper.go

Gate.IO recently made an API update which caused various tests to fail for things which use USD as a settlement currency since it doesn't exist. Looking at their site, they only support USDT and BTC based contracts (linear and inverse):
Fixes the issue and modifies tests along the way for things I've touched.

gateio: Update contract settlement currencies

---

exchanges/okx/okx_test.go
exchanges/okx/okx_websocket.go
exchanges/okx/okx_wrapper.go
exchanges/subscription/subscription.go

Just adds configurable subscriptions
Will also replay on top of the #1420

Okx: Add subscription configuration

---

exchanges/btse/btse_test.go
exchanges/btse/btse_websocket.go
exchanges/btse/btse_wrapper.go
testdata/configtest.json

* Add subscription templating
* Upgrade test config
- Orderbook is not present in this pull request because it has its own websocket connection and requires multi-websocket support

BTSE: Add subscription configuration

---

exchanges/poloniex/poloniex.go
exchanges/poloniex/poloniex_types.go
exchanges/poloniex/poloniex_wrapper.go

In fact, err is incorrect and should be errRet.

Poloniex: Fix GetChartData error return value

---

exchanges/futures/contract.go
exchanges/okx/okx_wrapper.go

- Introduced a map (`contractsMap`) to store contracts for faster lookup.
- Replaced loop-based contract search with direct map access, improving efficiency.
- Fixed comparison in position filtering to use formated pair instead of `req.Pairs[i].String()`.

okx: optimize futures position orders retrieval

---

exchanges/okx/okx_types.go
exchanges/okx/okx_wrapper.go

This pull request includes changes to the `AccountConfigurationResponse` struct in the `okx_types.go` file to correct data types for specific fields. The most important changes are:
* Changed the type of `Level` from `types.Number` to `string` to correctly represent the user level as a string.
* Changed the type of `TraderInsts` from `string` to `[]string` to correctly represent multiple trader instructions as a list of strings.
* Changed the type of `SpotTraderInsts` from `string` to `[]string` to correctly represent multiple spot trader instructions as a list of strings.
https://www.okx.com/docs-v5/en/#trading-account-rest-api-get-account-configuration
Please describe the tests that you ran to verify …

okx: fix type for AccountConfigurationResponse

---

cmd/apichecker/apicheck.go
common/cache/lru.go
currency/manager_test.go
currency/pair_methods.go

fix some function names in comment

chore: fix some function names in comments

---

exchanges/huobi/huobi_test.go

When testing CW against today, we were using a time.Now().Truncate() and documentation says to not do that.
Driveby refactored the tz out of the loop

Huobi: Fix TestPairFromContractExpiryCode on CW

---

config/versions/v2.go
config/versions/v4.go
config/versions/v4_test.go
config/versions/v5.go
config/versions/v5/defaults.go
config/versions/v5_test.go
config/versions/v6_test.go
config/versions/versions.go

* Fixes shared vars in both runtime and test packages
* Fixes test func names in Version6
Fixes #1864

Config: Eliminate shared config version package vars

---

common/key/key.go
engine/rpcserver.go
exchanges/account/account.go
exchanges/account/account_test.go
exchanges/account/account_types.go

Fixes https://github.com/thrasher-corp/gocryptotrader/issues/1831

account: refactor for save holdings

---

exchanges/kucoin/kucoin_test.go

* Kucoin: Fix failing TestSubscribeBatchLimit
This test ensures we have eyes on what the subscription limit per
session is. They've increased it from 300 to 400.
I think when I first did this, the code actually needed to know, but
it's still useful to ensure we know exactly where it sits.
* DriveBy: Remove checkSubscriptions
Fixes #1883

Kucoin: Fix failing TestSubscribeBatchLimit

---

exchanges/gateio/gateio.go
exchanges/gateio/gateio_test.go
exchanges/gateio/gateio_types.go
exchanges/gateio/ratelimiter.go

gateio: add ConvertSmallBalances, GetAccountDetails and GetUserTransactionRateLimitInfo methods

---

engine/websocketroutine_manager.go
exchanges/account/account.go
exchanges/account/account_test.go
exchanges/account/account_types.go
exchanges/bybit/bybit_websocket.go
exchanges/gateio/gateio_test.go
exchanges/gateio/gateio_websocket.go
exchanges/gateio/gateio_websocket_futures.go
exchanges/gateio/gateio_websocket_option.go
exchanges/kucoin/kucoin_test.go
exchanges/kucoin/kucoin_websocket.go
exchanges/okx/okx_test.go
exchanges/okx/okx_websocket.go
exchanges/poloniex/poloniex_websocket.go

Add ProcessChange method for update balance by websocket.

account: add ProcessChange for balance update

---

exchanges/huobi/huobi_test.go

We saw another false negative failure on huobi NW testing [here](https://github.com/thrasher-corp/gocryptotrader/actions/runs/14926487990/job/41932452598?pr=1901#step:11:731)
On Friday 2025-05-09 the end date for the next week moved to 2025-05-25.
This fix relaxes our tests, and handles the predictable failure on Next Quarter in the same manner as Next Week. For the quarterly tests, we add another 7 days.
Hopefully this will be the end of this recurring test failure.

Huobi: Relax TestPairFromContractExpiryCode expiry date tests 

---

currency/storage.go
exchanges/bybit/bybit_wrapper.go

fix some function names in comment

chore: fix some function names in comment

---

engine/apiserver_test.go

Engine: Assertify apiserver_test

---

cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go

cmd/exchange_wrapper_standards: Fix race on t.Context in exchange wrapper tests

---

web/src/app/pages/settings/settings.component.html

web: Fix typo in settings component
