common/common.go
You have to pass a pointer to `JSONDecode` and if you don't `JSONDecode` will pass a pointer to `json.Unmarshal` and no error will occur but message won't be unmarshaled.
=> Fix JSON unmarshaling

common/common.go, common/common_test.go, exchanges/gdax/gdax.go, exchanges/gdax/gdax_websocket.go, exchanges/gdax/gdax_wrapper.go
This aims to address a few issues with GDAX:
- update websocket API endpoint to restore websocket feed data (old one no longer resolves)
- API auth based on unix time stamp and hashed path instead of URL (auth fails otherwise).
- support alternate currency notation on GDAX (AAA-BBB and AAABBB). the configuration currently uses AAABBB format on GDAX for calls to GetTickerPrice() but that method requires AAA-BBB format. this is used by example AllActiveExchangesAndCurrencies and addresses account retrieval via that.
=> GDAX support

exchanges/poloniex/poloniex_types.go
example code
https://play.golang.org/p/FLrGM2x4v8
```golang
package main
import (
"fmt"
"time"
"encoding/json"
)
type Dummy struct {
Val time.Time `json:"val"`
}
func main() {
str := `{"val":1497314214}`
data := []byte(str)
var resp Dummy
err := json.Unmarshal(data, &resp)
if err != nil {
panic(err)
}
fmt.Println(resp)
}
```
output
```
panic: parsing time "1497314214" as ""2006-01-02T15:04:05Z07:00"": cannot parse "1497314214" as """
```
so I modify type from `time.Time` to `int64`
string -> status
```
- Status string `json:"string"`
+Status string `json:"status"`
```
=> Fix typo and type error in PoloniexDepositsWithdrawals

exchanges/poloniex/poloniex.go, exchanges/poloniex/poloniex_types.go
gocryptotrader is a trading bot, but I use it as poloniex API wrapper.
I implement missing poloniex api, returnLendingHistory
test code
```golang
package main
import (
"fmt"
"github.com/thrasher-/gocryptotrader/config"
"github.com/thrasher-/gocryptotrader/exchanges/poloniex"
)
func makePoloniex(apikey, secret string) *poloniex.Poloniex {
conf := config.ExchangeConfig{
Enabled:                 true,
APIKey:                  apikey,
APISecret:               secret,
AuthenticatedAPISupport: true,
Verbose:                 true,
Websocket:               true,
}
exchange := poloniex.Poloniex{}
exchange.Setup(conf)
return &exchange
}
func main() {
apikey := "your-api-key"
secret := "your-secret-key"
p := makePoloniex(apikey, secret)
histories, err := p.GetLendingHistory("", "")
if err != nil { …
```
=> Implement Poloniex API wrapper, returnLendingHistory

exchanges/btcc/btcc.go
BTCC and BTTChina are two different sites now. The market of btccny is in BTCChina. So please use api.btcchina.com rather then api.btcc.com
=> pls use api.btcchina.com to replace api.btcc.com

common/common.go, common/common_test.go
I know this is an annoying pull request, but thought I would submit it anyway since it is spelled correctly in other places of the repo.
=> Fixed misspellings of separator

exchanges/gdax/gdax.go
`SetDefaults` already sets `g.Verbose` to `false` (see few lines above)
=> GDAX SetDefaults cleanup

web/README.md
the readme was wrong when it said to run npm run web:start. It should be npm run start:web.
=> changes command to run application

exchanges/poloniex/poloniex.go
>>> returnTradeHistory
Returns your trade history for a given market, specified by the "currencyPair" POST parameter. You may specify "all" as the currencyPair to receive your trade history for all markets. You may optionally specify a range via "start" and/or "end" POST parameters, given in UNIX timestamp format; if you do not specify a range, it will be limited to one day. You may optionally limit the number of entries returned using the "limit" parameter, up to a maximum of 10,000. If the "limit" parameter is not specified, no more than 500 entries will be returned.
Before it was limited to 500. Now it could be extended
=> increase limit for GetAuthenticatedTradeHistory poloniex

.dockerignore, Dockerfile, docker-compose.yml, web/.dockerignore, web/Dockerfile, web/nginx/default.conf
Here is a proposal of working docker builds for the CLI and web app and a docker-compose setup. It uses optimized and cacheable layer structure and multi-stage builds resulting in tiny image sizes.
Simply execute `docker-compose up` and open http://localhost:9051/.
Here's what `docker images` says about the images:
```
REPOSITORY            TAG        IMAGE ID        CREATED             SIZE
gocryptotrader_web    latest     8bc6f6475793    11 minutes ago      17.6MB
gocryptotrader_cli    latest     d57add7f97d3    17 minutes ago      19.3MB
```
A full build until everything is build, up and running takes 2m59.591s (Output of `time docker-compose up -d`).
=> Docker setup

exchanges/bitfinex/bitfinex_websocket.go
According to: https://docs.bitfinex.com/v1/reference#ws-public-trades bitfinex sends a SEQ which is a string and is a trade id. Later it sends the real ID, so we can discard it the first time we receive it. 
Furthermore, bitfinex sends each trade in two messages: "te" and "tu". The "tu" messages contains the real trade id.
=> bitfinex websocket trade fix

web/package.json
warning gocryptotrader-web@0.4.0: Potential typo "contributers", did you mean "contributors"?
=> fix typo in package.json

exchanges/huobi/huobi.go
This PR fixes 2 things:
1) When sending in a POST request, we need to use a different "Content-Type" header (application/json).
2) We were sending in POST data via the query string, actually, we need to send it as json via the request body (we don't need to sign this data).
=> Fix Huobi's POST requests

common/common.go, common/common_test.go, exchanges/gateio/gateio.go
Improved GetHMAC test
Cut ByteArrayToString from common, already have a function that does the same thing
more coverage for SendHTTPRequest test
Improved SendHTTPGetRequest test
added JSONDecode test
added UnixMillis test
added RecvWindow test
added FloatFromString test
added IntFromString test
added Int64FromString test
added TestTimeFromUnixTimestampFloat test
=> Common.go testing

communications/slack/slack.go, communications/slack/slack_test.go
Slack.go Adding handling for trying to send responses when the websocket isn't connected
Slack.go Adding handling for an error response other than "Socket URL has expired"
Slack.go Making handleErrorResponse return an error
Slack.go Making use of s.Connected
Slack.go Making HandleMessage return an error
Slack.go Removing SendHTTPGetRequestSlack, code now calls SendHTTPGetRequest from common.go instead
More coverage for slack GetChannelsString test
More coverage for slack GetUsernameByID test
Improving slack GetIDByName test
Adding slack GetGroupIDByName test
Improving slack GetChannelIDByName test
More coverage for slack GetUsersInGroup test
Adding slack WebSocketConnect test
Adding slack handlePresenceChange test
Adding slack handleMessageResponse test
Adding slack handleErrorResponse …
=> Slack.go improvements and increasing coverage

engine/restful_router.go, engine/restful_server_test.go
The current router setup by design accepts requests from any hosts making it vulnerable to [DNS rebinding](https://en.wikipedia.org/wiki/DNS_rebinding) attacks
Automated testing with unit tests:
Running go test ./...
Manual testing running
``
curl localhost:9050/config/all -H "Host: localhost" -verborse
``
``
curl localhost:9050/config/all -H "Host: superawesomeinvalidhost.com" -verborse
``
=> Fixes DNS rebinding vulnerability in router by explicitly passing Host parameter based off config listenaddress

exchanges/huobihadax/huobihadax.go
Hadax had the wrong URL in its signature generation so all authenticated requests were denied. This changes it to the correct URL
I've run authenticated endpoint tests such as TestCancelExchangeOrder and it is successful
=> Fixes huobi hadax signature for authenticated methods

Makefile, config/config.go, config_example.json, restful_router.go, testdata/configtest.json
Simple PR to enable pprof for ongoing performance testing
It adds a profiler config option that is disabled by default along with some Makefile aliases for ease of access with the net/http/pprof package for heap and CPU profiling
At the moment it listens on the same address as the REST interface this may change in future
Automated testing using go test ./.. confirms all existing tests pass
Manual testing confirms pprof is working as intended when enabled
=> Added config option to enable pprof

exchanges/okcoin/okcoin_test.go
Fixes race condition in okcoin tests
=> OKEX websocket: Fix test race condition

exchanges/coinbasepro/coinbasepro_websocket.go
This fixes a nil pointer crash added in https://github.com/thrasher-/gocryptotrader/pull/262
Fixes #268
Usual automated testing and manual confirmation websocket for coinbase pro works
=> Coinbase Pro Websocket nil pointer crash fix - (#268)

currency/pair.go, exchanges/exchange_websocket.go, exchanges/kraken/kraken.go, exchanges/kraken/kraken_test.go, exchanges/kraken/kraken_types.go, exchanges/kraken/kraken_websocket.go, exchanges/kraken/kraken_wrapper.go, exchanges/okex/okex_test.go, exchanges/okgroup/okgroup_types.go, testdata/configtest.json
This PR adds Kraken websocket support to GCT
- Kraken orderbook data keeps last updated timestamps per price. GCT orderbook data has it per update. So there is a chance that orderbook data can be technically out of sync. I try to address it by taking the last updated currency vs the latest ob update.
New WS tests for kraken. All tests run simultaneously and builds and tests pass
=> Kraken websocket support

exchanges/binance/binance.go, exchanges/binance/binance_websocket.go
Updates binance to enable websocket cleanly 
Converts event timestamp to correct timestamp 
Also fixes a bug introduced in #161 the the switch statement does not correctly strip before the @ symbol causing no cases to be detected.
Fixes #271 #270 
Automated testing using go test
Manual testing of binance endpoint and websocket data
=> Binance websocket fixes for #271 & #270

exchanges/kraken/kraken_test.go, exchanges/kraken/kraken_types.go, exchanges/kraken/kraken_websocket.go
Kraken's websocket orderbook has very specific timestamps. Without a checksum, timestamps are the only thing we can rely on to process orderbook updates via WS. 
At the present time REST and Websocket are run simultaneously, so when the orderbook updates via REST, the partial/update system for Kraken WS orderbook is no longer in sync as it relied on `GetOrderbookEx`. So the first change is to internalise WS orderbooks/orderbook channel since we cannot rely on `GetOrderbookEx` right now.
Secondly, there is a potential for Kraken to send out of order WS orderbook updates. So a basic buffer is being introduced to append the last 3 updates/WS orderbook array, reorder and then save the orderbook. 
The ask/bid functions are pretty much the same except for what is referenced (bids, asks). I'd …
=> Kraken websocket orderbook buffer

config/README.md, config/config.go, config/config_test.go, config_example.json, main.go, ntpclient/ntpclient.go, ntpclient/ntpclient_test.go, testdata/configtest.json
This PR add's a new NTP Client into GCT that can be used for checking time against a remote NTP Server
It also includes a startup check that can be configured that will alert / warn (can also be disabled completely) a user if their current time is outside an allowed difference from the current network time
```js
"ntpclient": {
"enabled": 0,
"pool": [
"pool.ntp.org:123"
],
"allowedDifference": 0,
"allowedNegativeDifference": 0
},
```
The configuration options for this are:
enabled: -1 to disable 0 for alert 1 for warn 
pool:  list of time servers to attempt to contact this attempt first to last 
allowedDifference: how far behind the time is allowed before a warning/alert is triggered
allowedNegativeDifference: how far ahead the time is allowed before a warning/alert is triggered
The NTP …
=> New NTP Client

exchanges/zb/zb.go
Comparative is true when nothing is returned could force out of range, also misses element if you initialise with -1. 
Local package test
- [n/a] I have commented my code, particularly in hard-to-understand areas
=> ZB: GetOrderbook out of range fix

restful_router.go, restful_server_test.go
The HTTP standard https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23 requires a port only be sent for the Host header if it is not the "Default" port 80
This is a simple fix to check if the port is 80 and strip if it is
Automated testing using go test ./...
manually confirming required Host headers are accepted using
- curl -H "Host: localhost:9050" localhost:9050
- curl -H "Host: localhost" localhost:80
- curl -H "Host: invalid:9050" localhost:9050
=> RPC server host/port fix

codelingo.yaml, config/config.go, config/config_encryption.go, exchange.go, exchanges/bitfinex/bitfinex_test.go, exchanges/bitfinex/bitfinex_websocket.go
Omit unnecessary else statements when `if` does not flow into the next statement, [as specified in Effective Go](https://golang.org/doc/effective_go.html#control-structures).  Previous instances of this issue were fixed in [PR #154](https://github.com/thrasher-/gocryptotrader/pull/154/commits/5de0c94ab891914292d2193e2489f30084b40ebc). 
Adds [unnecessary-else tenet](https://github.com/codelingo/codelingo/blob/master/tenets/codelingo/effective-go/unnecessary-else/codelingo.yaml) to your [codelingo.yaml file](https://github.com/leilaes/gocryptotrader/blob/unnecessary-else/codelingo.yaml#L8) to notify you of any future instances of the same issue via code review.
`go test -race -coverprofile=coverage.txt -covermode=atomic  ./...`
=> Omit unnecessary else statements when `if` does not flow into the next statement

exchanges/gateio/gateio.go, exchanges/gateio/gateio_test.go, exchanges/gateio/gateio_types.go, exchanges/gateio/gateio_websocket.go, exchanges/gateio/gateio_wrapper.go, restful_router.go
1) Adds GetOrderInfo wrapper function to GateIO
- GateIO requires a "market" on its OrderInfo endpoint but we only take OrderID to get around this a query is done against all orders to match passed in Order
2) Adds support for Authenticated Websocket requests
- Following https://www.gate.io/docs/websocket/index.html Sends a "signin" request that is a base64ed HMAC using your api key, secret & nonce 
- I have also added wsGetBalance & wsGetOrderInfo functions to get balance and order information
3) Bug fix for GateIO balance
- GateIO sends different responses depending on if you have no balance a single balance or multiple balances this is a simple work around for that although the code is a little complex over the usual json.Decode it does catch and ignore potentional errors in data …
=> Gateio expand wrappers, websocket and bug fix

restful_router.go, restful_server_test.go
Changes the listenAddress that is passed to Host() to follow project standard of using "localhost" if no interface is selected (i.e listening on ":9050")
This change does mean in a default configuration the RPC interface will only accept requests on "http://localhost:9050" unless configured otherwise by a user
Also remove the unneeded double status write on getIndex as it will return 200 anyway
Fixes #296 
Automated testing using go test ./...
Manual testing confirms host matches required validation levels
=> RPC Server Host valdiation fix for #296

exchanges/kraken/kraken_test.go, exchanges/okcoin/okcoin_test.go, exchanges/okex/okex_test.go
OKGroup Websocket tests weren't the best before, and now with the merge of the connection and subscription handler, the chance of their tests failing has increased due to excess noise.
So I've made the following changes:
- OKGroup: Dial the websocket manually and read responses rather than going through WsConnect(). Doing it this way means the connection monitor and subscription handlers aren't run, so the only messages going through the WS connection are from test inputs
- Kraken: The orderbook validation functions don't actually require a WS connection, so I removed it.
run package tests,
run all tests
run all tests -race\
=> WS test improvements

config/config.go
Coinut only uses one key (`APIKey`). If you try and set `AuthenticatedApiSupport: true` in config and only set the `APIKey`, `AuthenticatedApiSupport` will always be set to false due to an if statement that will always match.
I've swapped the if statements around so the more specific scenario is hit first and correctly sets `authenticatedApiSupport`
I was wondering why authenticated WS testing for COINUT wasn't working for way too long before realising that `APIKey`, `ClientId` and  `AuthenticatedApiSupport` were not being properly set due to the above. 
Switching the if around fixed it. All tests pass
Checklist:
=> Config: Fix AuthenticatedAPISupport default values check

exchanges/coinut/coinut.go
Fixes Coinut SendHTTPRequest as it uses ClientID(username) and APIKey only, not an APISecret.
Coinut API authenticated endpoints using an APIKey.
=> COINUT: Fix SendHTTPRequest authenticated requests

exchanges/kraken/kraken_types.go, exchanges/kraken/kraken_websocket.go
Kraken let's you know its updated its WS api via a blog post rather than its API documents. Changes can be found here: https://blog.kraken.com/post/2341/new-version-of-kraken-websockets-public-api-goes-live-may-30/
I've run the application. The new fields come through:
`[3,["11488.00000","11493.90000","1562131789.805398","1.07600000","2.00000000"],"spread","XBT/USD"]` 
Where "spread" is the channel name and "1.07600000" & "2.00000000" are the bid volume and ask volume respectively
There is an additional feature that's not implemented since we don't have a use for it at the moment. The "r" field for border republishes on the orderbook. ~~I've left it as a comment~~ I've removed the comment due to linting. If we ever need it we'll implement it.
=> Adds support for kraken websocket 0.2.0

exchanges/binance/binance_websocket.go, exchanges/okgroup/okgroup_websocket.go
Timestamp in raw data feed is in milliseconds whilst it is parsed as nanosecond value using time.Unix(0, trade.TimeStamp).
Actual data:
```
{Timestamp:1970-01-19 05:03:39.862109 +0300 MSK CurrencyPair:BTCUSDT AssetType:SPOT Exchange:Binance EventType: EventTime:0 Price:12181.35 Amount:0.01097 Side:trade}
```
Expected data:
```
{Timestamp:2019-07-09 00:10:01.969 +0300 MSK CurrencyPair:BTCUSDT AssetType:SPOT Exchange:Binance EventType: EventTime:0 Price:12169.83 Amount:0.006087 Side:trade}
```
Zero trade volume amount in incoming WS trade events. Wrong data field is being exposed.
Actual data:
```
{Timestamp:2019-07-08 20:58:21.718 +0000 UTC CurrencyPair:ETH-BTC AssetType:SPOT Exchange:OKEX EventType: EventTime:1562619511 Price:0.02547 Amount:0 Side:sell}
```
Expected data:
``` …
```
=> Fixes to OKEX and Binance WS trades data mapping

exchanges/huobi/huobi.go, exchanges/huobi/huobi_test.go, exchanges/huobi/huobi_types.go
Add Huobi GetAggregatedBalance api that returns the balances of all the
sub-account aggregated.
See also
- https://huobiapi.github.io/docs/spot/v1/en/#get-the-aggregated-balance-of-all-sub-accounts-of-the-current-user
- [] I have commented my code, particularly in hard-to-understand areas
=> Add Huobi GetAggregatedBalance api

exchanges/huobihadax/huobihadax.go, exchanges/huobihadax/huobihadax_test.go, exchanges/huobihadax/huobihadax_types.go
_Shamelessly copies_ hannut91's fine work from https://github.com/thrasher-/gocryptotrader/pull/329 and applies it to `Hadax.go` forcing us to consider merging the two exchanges slightly more
Add ~Huobi~Hadax GetAggregatedBalance api that returns the balances of all the
sub-account aggregated.
See also
- https://huobiapi.github.io/docs/spot/v1/en/#get-the-aggregated-balance-of-all-sub-accounts-of-the-current-user
Running test `TestGetAggregatedBalance()` in huobihadax_test.go and seeing the response
=> Implements endpoint GetAggregatedBalance for Hadax

exchanges/bitmex/bitmex_websocket.go
Bitmex websocket is not able to initialise order book snapshot due to case sensitive comparison of side:
`[ERROR]: 2019/07/30 21:50:55 routines.go exchange Bitmex websocket error - bitmex_websocket.go error - snapshot not initialised correctly`
Bitmex side is supplied as `Buy` or `Sell` (not all caps) - https://www.bitmex.com/app/wsAPI.
Not able to get initial orderbook snapshot without this change.
=> Bitmex compare initial orderbook snapsnot insensitive

main.go
Currently if logging output is disabled and your local time is out of sync from one of the network servers it will still prompt for you to confirm if you wish to alert/warn or disable in future but wont display this message to output
This adds an additional check to only prompt if logging is enabled
=> NTP out of sync prompt fix if logger is disabled

exchanges/anx/anx_live_test.go, exchanges/bitstamp/bitstamp.go, exchanges/bitstamp/bitstamp_test.go
Various bug fixes
```
go test ./... -tags=mock_test_off // for ANX
go test ./... -race -count=100 // for Bitstamp
```
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [hopefully] My changes generate no new warnings
- [n/a] I have added tests that prove my fix is effective or that my feature works
=> Bugfix: Bitstamp race condition and ANX format directive issue

communications/telegram/telegram.go, currency/coinmarketcap/coinmarketcap.go, currency/coinmarketcap/coinmarketcap_test.go, currency/storage.go, exchange.go, exchanges/mock/recording.go, main.go
Cleans up unnecessary log.Fatals around the codebase where neccessary. There still exists some for exchange loading via Setup but these have all been fixed in engine branch.
Also moves the os.Exit(1) if number of loaded exchanges == 0 from SetupExchanges to main, so developers don't have to look through the code too far if they find out their programs exits on them unexpectedly. 
=> Fix unnecessary log.Fatals and os.Exits

logger/logger.go, logger/logger_multiwriter.go, logger/logger_rotate.go, logger/logger_setup.go, logger/logger_types.go, logger/loggers.go, logger/sublogger_types.go
This PR Fixes an issue with unbuffered channels and multiwriter
Also some general improvements and added some comments
_please ignore the nolint in sublogger_types.go I didn't want to comment 16 times_
```go
// ConnectionMgr sublogger does stuff and things
ConnectionMgr    *subLogger
// CommunicationMgr sublogger does stuff and things
CommunicationMgr *subLogger
```
Automated testing using go test ./..
Manual testing of application running
pprof monitoring
=> (Engine) Logger - fixes issues with multiwriter go routine 

exchanges/okex/okex_wrapper.go
My previous PR included changes concerning config upscaling for OKEX. While it can successfully update a master branch `config_example.json`, it fails when dealing with a config that has already been updated to `engine` style - causing widespread `panic`.
This PR fixes that by being explicit about the config delimiter styles for OKEX and not just trying to deal with SPOT.
-`go test ./...`
- Running GCT with a `config_example.json` 
- Running GCT with an upscaled config and an OKEX currency pair configuration like the following (where ... are the default currencies):
```
"currencyPairs": {
"requestFormat": {
"uppercase": false,
"delimiter": "_"
},
"configFormat": {
"uppercase": true,
"delimiter": "_"
},
"useGlobalFormat": true,
"assetTypes": [
"spot",
"futures",
"perpetualswap",
"index"
], …
```
=> Engine: bugfix: OKEX Future swap panic

exchanges/gateio/gateio_websocket.go
Fun happy little accident i ran into while testing 
GateIO pairs are upper case & case sensitive on Websocket for Orderbook/ticker (and lower case on REST :D)
Automated unit tets all pass as required
Manual confirmation of valid output being received 
Before:
```sh
[DEBUG] |  12/09/2019 10:29:06  | GateIO Subscribing to ticker.subscribe BTC_USDT
[DEBUG] |  12/09/2019 10:29:06  | GateIO sending message to websocket {"id":1568248146292412809,"method":"ticker.subscribe","params":["btc_usdt"]}
[DEBUG] |  12/09/2019 10:29:06  | GateIO Websocket message received: {"error": null, "result": {"status": "success"}, "id": 1568248146292412809}
[DEBUG] |  12/09/2019 10:29:06  | GateIO has received a traffic alert. Setting status to connected
[DEBUG] |  12/09/2019 10:29:07  | GateIO checking connection …
```
=> (Engine) Gate-IO Websocket subscription pairs case sensitivity 

exchanges/orderbook/orderbook.go, exchanges/orderbook/orderbook_types.go, exchanges/ticker/ticker.go, exchanges/websocket/wshandler/wshandler.go, exchanges/websocket/wshandler/wshandler_test.go, exchanges/websocket/wsorderbook/wsorderbook.go, exchanges/websocket/wsorderbook/wsorderbook_test.go, exchanges/websocket/wsorderbook/wsorderbook_types.go
> Captured footage of GoCryptoTrader attempting to outrun Coinbase Pro updates 
There have been many updates to websockets, orderbooks and tickers recently that rely on the use of maps. Every time a map is used, go has to look it up - you'll see in the old code, we were looking up items many lines in a row. At the end of our maps are pointers, so we can just make a var referencing the pointer without needing to do a double-lookup.
Coinbase Pro sends out websocket orderbook and ticker updates for _every_ change. When processing this large amount of data, GoCryptoTrader would fall behind leading to an ever larger queue of updates. This was captured by @shazbert as a result of testing https://github.com/thrasher-corp/gocryptotrader/pull/360 (noscope)
This PR addresses that by minimising map …
=> Bugfix/improvement: Orderbook/ticker update processing

dispatch/dispatch.go, dispatch/dispatch_types.go, engine/engine_types.go, main.go
Uses int32 for dispatcher atomic variables, in line with the rest of the engine changes. 
Fixes a crash bug when running GCT on ARM.
CI and by running the binary
=> Engine: Use int32 for dispatcher atomic operations

exchanges/gateio/gateio_websocket.go
Updates the GateIO websocket endpoint to their other reccomended (https://www.gate.io/docs/websocket/index.html#server-url) one due to a certificate failure.
Fixes # (issue).
Enabling websocket on GateIO and running tests
```
[DEBUG]: 2019/10/31 11:37:04 GateIO Websocket message received: {"method": "ticker.update", "params": ["BTC_USDT", {"period": 86400, "open": "9400", "close": "9175.6", "high": "9400", "low": "9000.22", "last": "9175.6", "change": "-2.38", "quoteVolume": "1759.1883544226", "baseVolume": "16124505.306686951488755921"}], "id": null}
```
=> GateIO: Update websocket endpoint because of certificate failure

exchanges/order/order_types.go
When testing some code on my engine qa branch, I noticed that append wasn't working as expected when using exchange wrapper order funcs. After investigating it a bit more, it turns out that using anonymous fields breaks it.
```
func TestAppendage(t *testing.T) {
var orders []order.Detail
orders = append(orders, order.Detail{
Price: 1337,
})
t.Log(orders)
}
```
Output: bitstamp_test.go:263: []
Manually testing order wrapper funcs and go test ./... -race (though isn't helpful for runtime)
=> Add in types for order fields

cmd/config/config.go, cmd/exchange_wrapper_issues/main.go, cmd/gen_cert/main.go, cmd/gen_sqlboiler_config/main.go, cmd/huobi_auth/main.go, common/common.go, common/common_test.go, common/file/file.go, common/file/file_test.go, config/config.go, currency/storage.go, engine/helpers.go, exchanges/mock/recording.go, exchanges/mock/server.go, logger/logger_rotate.go
Adds a new file.Move func for moving files as recent testing has shown that docker volumes and Golang trigger a "Invalid cross-device link" error when using os.Rename as found here: https://github.com/thrasher-corp/gocryptotrader/pull/382#discussion_r351078142
go test ./... -race and golangci-lint
=> Fix Docker os.Rename invalid cross-device link issue

.gitattributes
Introduces a .gitattributes file which sets go.mod/go.sum line endings to LF based off the discussion in: https://github.com/golang/go/issues/31870
=> Always set go.mod/go.sum file line endings to LF

cmd/exchange_template/wrapper_file.tmpl
Adds missing withdraw import to the exchange_template tool
Running the tool with dummy params
=> Exchange template tool: Fix exchange_template missing import

exchanges/btcmarkets/btcmarkets.go, exchanges/btcmarkets/btcmarkets_test.go, exchanges/btcmarkets/btcmarkets_wrapper.go
Enables ticker batching support for BTC Markets using the [Get Multiple Tickers](https://api.btcmarkets.net/doc/v3#tag/Market-data-APIs/paths/~1v3~1markets~1tickers/get) endpoint
=> (BTC Markets) Ticker batching support

config/config.go, config/config_test.go, config/config_types.go
Another small PR this adds a field "ID" to the BankAccount struct along with a method GetBankAccountByID to return pointer to BankAccount
adding this as an easy way to pass bank details when withdrawing fiat funds as part of #383 so users dont need to pass and have validation doesn't need to happen on 30 parameters.
=> [Config] Add "ID" field to BankAccount struct & GetBankAccountByID method

cmd/dbmigrate/main.go, engine/database.go
Originally it was possible to crash the bot by sending two subsequent stop requests to the database subsystem (via the cli or an app) due to attempting to close and already closed channel. This method protects the bot when stopping the database subsystem (sets the state to stopping, preventing further stop requests) until the state is finally reset when it does actually shutdown.
- Send 2 subsequent stops and you'll get a panic on attempt to close an already closed channel
=> Engine: Use atomic.LoadInt32/AddInt32 for starting/stopping the database subsystem

cmd/config/config.go, cmd/dbmigrate/main.go, cmd/gen_otp/otp_gen.go, cmd/gen_sqlboiler_config/main.go, cmd/portfolio/portfolio.go, config/config.go, config/config_test.go, main.go
There exists use cases where a person will want to specify a config file which doesn't exist in the default data directory, all of our cmd applications currently will fail if one doesn't exist, even if you specify a source config file to use.
```
dbmigrate --help
GoCryptoTrader database migration tool
Copyright (c) 2014-2020 The GoCryptoTrader Developers.
config.json file not found in C:\Users\x\AppData\Roaming\GoCryptoTrader, please follow README.md in root dir for config generation
```
Now:
```
dbmigrate.exe --help
GoCryptoTrader database migration tool
Copyright (c) 2014-2020 The GoCryptoTrader Developers.
Usage of dbmigrate.exe:
-args string
arguments to pass to goose
-command string
command to run status|up|up-by-one|up-to|down|create
-config string
config file to load (default …
```
=> Bugfix: Introduces a new config.DefaultFilePath func

cmd/gctcli/commands.go, exchanges/binance/binance.go, exchanges/bitfinex/bitfinex.go, exchanges/bitflyer/bitflyer.go, exchanges/bithumb/bithumb.go, exchanges/bitmex/bitmex.go, exchanges/bitstamp/bitstamp.go, exchanges/bittrex/bittrex.go, exchanges/btcmarkets/btcmarkets.go, exchanges/btse/btse.go, exchanges/coinbene/coinbene.go, exchanges/coinut/coinut.go, exchanges/exmo/exmo.go, exchanges/gateio/gateio.go, exchanges/gemini/gemini.go, exchanges/hitbtc/hitbtc.go, exchanges/huobi/huobi.go, exchanges/itbit/itbit.go, exchanges/kraken/kraken.go, exchanges/lakebtc/lakebtc.go, exchanges/lbank/lbank.go, exchanges/localbitcoins/localbitcoins.go, exchanges/okcoin/okcoin.go, exchanges/okex/okex.go, exchanges/poloniex/poloniex.go, exchanges/withdraw/withdraw_types.go, exchanges/yobit/yobit.go, exchanges/zb/zb.go
Basic commit which adds destination vars and arg checks before assignment in GCTCLI
Also fixes linter issues associated with func name comments
```
NAME:
gctcli gethistoriccandles - gets historical candles for the specified granularity up to range size time from now.
USAGE:
gctcli gethistoriccandles [command options] <exchange> <pair> <rangesize> <granularity>
OPTIONS:
--exchange value, -e value     the exchange to get the candles from
--pair value                   the currency pair to get the candles for
--rangesize value, -r value    the amount of time to go back from now to fetch candles in the given granularity (default: 10)
--granularity value, -g value  value is in seconds and can be one of the following {60, 300, 900, 3600, 21600, 86400} (default: 86400)
```
=> GCTCLI: Destination var/arg check usage fixes

config/config_types.go, config_example.json, engine/restful_router.go, engine/restful_server_test.go, testdata/configtest.json
Adds a config entry for setting [SetMutexProfileFraction](https://golang.org/pkg/runtime/#SetMutexProfileFraction) value this allows you to do mutex profiling with pprof
Also removed the stutter on config struct adds additional test covage to check endpoint responds if its enabled 
=> (PROFILING): Add config support for setting runtime.SetMutexProfileFraction() value

exchanges/coinut/coinut.go, exchanges/coinut/coinut_test.go, exchanges/coinut/coinut_websocket.go, exchanges/coinut/coinut_wrapper.go
Our tests were failing due to an invalid nonce issue, this PR introduces a simple getNonce func to generate a number between 1 and 16777215 as per https://github.com/coinut/api/wiki/Websocket-API#nonce
=> Coinut: Fix nonce issue based on new API change

gctrpc/rpc.pb.go, gctrpc/rpc.proto, gctrpc/rpc.swagger.json
Hi I'm David a software developer from Frankfurt, Germany. Your project looks interesting, so I tried to build an automatically generated client for it. During this process I found a bug, that is fixed with this pull request.
Fixes:
gctrpc/rpc.proto has an error in line 939  "};rpcse"
This prevents clients, that were generated with rpc.swagger.json, from compiling.
[x] Bug fix and executing gen_pb_linux.sh. Except of rpc.proto all changes are autogenerated.
I used the new rpc.swagger.json to generate a rustclient for gocryptotrader that actually compiled.
=> Fixed rpc.proto and regenerated files

engine/rpcserver.go
RPC server crashed when requesting submit by using gctcli
- [x ] My code follows the style guidelines of this project
=> (BUG FIX) Fix order submission crash due to missing "exchange" parameter 

config/config.go, exchanges/btcmarkets/btcmarkets.go, exchanges/btcmarkets/btcmarkets_test.go, exchanges/btcmarkets/btcmarkets_types.go, exchanges/btcmarkets/btcmarkets_wrapper.go, log/logger_types.go, log/loggers.go
Adds support for the updated GetHistoricCandles() wrapper method added in #454 and also reworks GetMarketCandles() method to match requirements of [BTC Markets API](https://api.btcmarkets.net/doc/v3#tag/Market-data-APIs/paths/~1v3~1markets~1{marketId}~1candles/get)
```
✗ go run ./cmd/gctcli gethistoriccandles "BTC Markets" "BTC-AUD" "SPOT" 1 86400
{
"candle": [
{
"time": 1584230400,
"low": 8355.12,
"high": 9550,
"open": 8430.65,
"close": 8744.37,
"volume": 383.06940601
},
{
"time": 1584316800,
"low": 8500,
"high": 8776.22,
"open": 8773.25,
"close": 8598.41,
"volume": 138.76640452
}
]
}%         
```
also consider …
=> (BTC Markets) Add support for GetHistoricCandles wrapper

exchanges/zb/zb.go, exchanges/zb/zb_test.go, exchanges/zb/zb_websocket.go
ZB has changed its websocket URL, I've changed it. See: https://www.zb.com/api#WebSocket%20API
Its also changed its Trading and Data API urls, however, they appear to be redirecting. I've updated those now too
- Comparing results of old URL to current URL. The new one can connect, the old one can't
- go test ./... race
- Testing with API credentials
=> (FIX) Update ZB API URLs

exchanges/okcoin/okcoin.go
Another websocket connection issue caught. Embarrassingly, I missed this post from last year: https://support.okcoin.com/hc/en-us/articles/360031164711-Change-in-V3-WebSocket-API-Address-Port-Number
I've also missed that okcoin hasn't been able to connect to the websocket with this:
```
[ERROR] | WEBSOCKET | 31/03/2020 15:14:28 | OKCOIN International Error connecting wss://real.okcoin.com:10442/ws/v3 Error: dial tcp 149.129.81.119:10442: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```
Running with the new URL:
```
[INFO]  | WEBSOCKET | 31/03/2020 15:16:30 | OKCOIN International Websocket connected to wss://real.okcoin.com:8443/ws/v3
```
=> (BUGFIX) OKCoin websocket port update

exchanges/binance/binance.go, exchanges/binance/ratelimit.go, exchanges/binance/ratelimit_test.go, exchanges/request/request.go, go.sum
Request types / variations contribute different weights towards the limit Binance enforces. These can be considerably more than 1 per request, which results in the server side limits being hit, producing 429 and 418 responses and bans
=> Binance: Fix Request Rate Limits

engine/portfolio.go, portfolio/portfolio.go, portfolio/portfolio_test.go, portfolio/portfolio_types.go
Also syncs address balances straight away instead of waiting the default time for the tick to hit channel.
Fixes #
When we call an ETH address it falls through to another block explorer then errors out. Now it does not.
running it
=> Portfolio: Add support for XRP balance fetching and fix ETH address balance 404 issue

exchanges/binance/binance_test.go, exchanges/binance/binance_websocket.go, exchanges/orderbook/orderbook_types.go, exchanges/websocket/wsorderbook/wsorderbook.go, exchanges/websocket/wsorderbook/wsorderbook_test.go
With the incorrect implementation currently, orderbooks have incorrect entries in them which never get removed. This results in an unsynchronised state, having issues such as bid prices greater than the lowest ask prices
The websocket depth updates must be subscribed to before getting a snapshot. Any updates from the websocket that have earlier update ids must be discarded.
https://binance-docs.github.io/apidocs/spot/en/#how-to-manage-a-local-order-book-correctly
=> Binance: Fix Orderbook Management

exchanges/kraken/kraken_websocket.go
Please include a summary of the change, feature or issue which this pull request addresses. Please also include relevant motivation and context. List any dependencies that are required for this change.
Probably a mechanical typo in the wsProcessOrderBook method (Kraken). As a result, both variables fullAsk and fullBids got the Ask data.
=> Kraken: wsProcessOrderBook, the method was returning wrong bids data

config/config.go, config/config_test.go, config/config_types.go, config_example.json, engine/engine.go, engine/engine_test.go
The provided data directory is not honored by the engine in some cases, instead a default path is used.
This change makes the data directory configuration part of config.json and enables the override using command line flag.
=> Config/Engine: Add data directory to config.json

cmd/gctcli/main.go
GCT cli can only read cert from default dir. Fix this.
=> gctcli: Add flag var for TLS cert path

engine/engine.go
* the data directory can be loaded from config file and not from settings
* the correct data directory will be created later when subdirs are created
The default data dir is created even if other directory is specified in config file and no flag is set.
=> Engine: Remove incorrect creation of data directory

cmd/config_builder/builder.go, cmd/exchange_wrapper_coverage/main.go, cmd/exchange_wrapper_issues/main.go, currency/storage.go, engine/addr_helpers.go, engine/connection.go, engine/engine.go, engine/engine_test.go, engine/exchange.go, engine/exchange_test.go, engine/fake_exchange_test.go, engine/helpers.go, engine/helpers_test.go, engine/orders.go, engine/portfolio.go, engine/restful_router.go, engine/restful_server.go, engine/restful_server_test.go, engine/routines.go, engine/rpcserver.go, engine/syncer.go, engine/syncer_test.go, engine/websocket.go, engine/withdraw.go, gctscript/wrappers/gct/exchange/exchange.go, gctscript/wrappers/gct/exchange/exchange_test.go
* make the dependency on having an existing running Engine more obvious
* use explicit dependency of engine in RPCServer
* reduce static dependencies in rpcserver
* improve helpers
This change should have no functional impact on the code. Just a Refactoring to use less of `engine.Bot` global variable.
It will break external code that uses static methods, but it's only a small syntactic change, replacing
`engine.GetXXX()` with `engine.Bot.GetXXX()` is the fix (e.g. `engine.Bot.GetExchangeNames(true)`)
but ideally `engine.Bot` should not be used at all, instead your local intance of the bot should be preferred.
Ran all the existing tests
Is there a list somewhere?
=> Engine: Refactor use of global Bot

cmd/dbseed/dbseed_test.go, config/config.go, config/config_test.go, config/config_types.go
Tests should explicitly state their target configuration file, so no need
to use fallback default override flag
I don't think there would be any
=> Config: Remove TestBypass flag

config/config.go, config/config_encryption.go, config/config_encryption_test.go, config/config_types.go
* save session variables as unexported fields in config
* unexport internal encryption helper functions
* add encryption/decryption tests
Still don't know what these are
=> Config: do to not store decryption variables globally

common/file/file.go, common/file/file_test.go, config/config.go, config/config_test.go, engine/engine.go, engine/engine_test.go, engine/exchange.go, engine/exchange_test.go, gctscript/wrappers/gct/exchange/exchange_test.go, main.go
Resolving paths shouldn't really edit file system
=> Config: fix don't create empty dir when resolving path

cmd/exchange_wrapper_issues/main.go, cmd/gctcli/validation.go, config/config.go, engine/rpcserver.go, engine/websocket.go, exchanges/asset/asset.go, exchanges/asset/asset_test.go, gctscript/modules/gct/exchange.go
When testing #580 there was an issue with script deployment via assets as we were changing casing. This update attempts to standardise casing to asset package supported items and be explicit invalidation to its case, minimising the chance of change. 
Before: 👎 
```
[ERROR]| 16/10/2020 11:00:32 |GCT Script: (ACTION) RunCtx Runtime Error: asset not enabled
at (main):8:18
at (main):12:1
```
After:  👍 
```
[DEBUG]| 16/10/2020 12:49:25 |New GCTScript VM created
[INFO] | 16/10/2020 12:49:25 |CSV file successfully saved to: 
Roaming\GoCryptoTrader\scripts\output\bro-1602812965767569600.csv
```
Please describe the tests that you ran to verify your changes. Provide instructions so we can …
=> Asset package update

common/common_test.go, engine/comms_relayer.go, engine/fake_exchange_test.go, engine/orders.go, engine/orders_test.go, engine/rpcserver.go, exchanges/lbank/lbank_test.go, exchanges/lbank/lbank_wrapper.go, gctscript/examples/exchange/cancel_order.gct, gctscript/examples/exchange/submit_order.gct, gctscript/modules/gct/exchange.go, gctscript/modules/gct/gct_test.go, gctscript/modules/gct/gct_types.go, gctscript/modules/wrapper_types.go, gctscript/wrappers/gct/exchange/exchange.go, gctscript/wrappers/gct/exchange/exchange_test.go, gctscript/wrappers/gct/gctwrapper_test.go, gctscript/wrappers/validator/validator.go, gctscript/wrappers/validator/validator_test.go, gctscript/wrappers/validator/validator_types.go
Our Slack community member "ed" discovered a bug when attempting to execute scripted trading:
When attempting to submit or cancel orders via scripting, gctscript would error out because the exchange name was unset. This PR sets it. 
Since this area of code was untested against a real interface, I've added tests to ensure that these kind of errors would surface Just double checking this part. Fixed a few other things I noticed too.
Update: This PR also updates the script implementation of cancel order to include currency pair and asset type. It also adds the ability for the bot ordermanager to retrieve orders on an exchange's behalf. This will allow us to store any order retrieved via command so that we will not get any order not founds when cancelling orders via script …
=> Bugfix: Submit/Cancel order scripting errors + Ordermanager GetOrder & CancelOrder improvements

exchanges/bitflyer/bitflyer_test.go, exchanges/bitflyer/bitflyer_types.go
Added MarketType field in MarketInfo of bitflyer.
Before this, struct MarketInfo of bitflyer contained only ProductCode and Alias. But it seems insufficient, see the definition of the endpoint ```/v1/getmarkets```; https://lightning.bitflyer.com/docs?lang=en#market-list
In case that this MarketType field is absent, you can't distinguish futures valid or expired on SQdate.
Here is an response example below on SQdate (I requested on 6, Nov 2020). You can find BTCJPY06NOV2020 expiring futures doesn't have Alias field but MarketType, and the other futures have both yet.
Namely Alias field is not mandatory but MarketType is. So I added.
```
[
{
"product_code": "BTC_JPY",
"market_type": "Spot"
},
{
"product_code": "FX_BTC_JPY",
"market_type": "FX"
},
{
"product_code": "ETH_BTC",
"market_type": …
```
=> Added MarketType field in MarketInfo of bitflyer

gctscript/modules/ta/indicators/atr.go, gctscript/modules/ta/indicators/bbands.go, gctscript/modules/ta/indicators/correlation.go, gctscript/modules/ta/indicators/ema.go, gctscript/modules/ta/indicators/macd.go, gctscript/modules/ta/indicators/mfi.go, gctscript/modules/ta/indicators/obv.go, gctscript/modules/ta/indicators/rsi.go, gctscript/modules/ta/indicators/sma.go
An issue was brought up by Ed via our Slack. Due to small decimals, we are not getting the correct output when running TA scripts. 
This attempts to address this issue by removing the rounding of outbound float64's inside the script package. 
=> script: remove rounding from scripting TA

exchanges/binance/binance.go, exchanges/binance/binance_test.go, exchanges/binance/binance_types.go, exchanges/binance/binance_websocket.go, exchanges/binance/binance_wrapper.go, exchanges/binance/type_convert.go
* add custom Unmarshal function for JSON types
To make the Binance API easier to use we can already do the time conversions for the user of the library.
=> Binance: convert timestamps to time.Time

Makefile, cmd/gctcli/commands.go, cmd/gctcli/main.go, engine/fake_exchange_test.go, engine/rpcserver.go, engine/rpcserver_test.go, exchanges/lbank/lbank_types.go, exchanges/lbank/lbank_wrapper.go, gctrpc/rpc.pb.go, gctrpc/rpc.pb.gw.go, gctrpc/rpc.proto, gctrpc/rpc.swagger.json, gctrpc/rpc_grpc.pb.go
This patch add support of UpdateAccountInfo to the GRPC server. 
It is useful to have actual account state for the preliminary validation of the bid request. 
Without such possibility we have to send requests to the exchange and either use completed orders for keeping account up to date or handle error messages from the exchange.  
- [x ] New feature (non-breaking change which adds functionality)
Added tests to the engine/rpcserver_test.go
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass …
=> engine/gRPC: Add update account info to grpc interface

.gitignore, Makefile, cmd/gen_sqlboiler_config/main.go
* the generator should use the same path as the database/drivers/sqlite3
* remove unused data directory
* auto-generate sqlboiler.json for model generation
* ignore target folder
=> gen_sqlboiler: fix incorrect database path for non-default sqlite location

currency/pair.go, currency/pair_test.go, currency/pair_types.go, exchanges/binance/binance.go, exchanges/binance/binance_test.go, exchanges/binance/binance_types.go, exchanges/binance/binance_websocket.go, exchanges/binance/binance_wrapper.go, exchanges/binance/type_convert.go
* request calls use type safe arguments
* binance API handles the correct conversion now on a lower level
* consolidate formatting to a single place
* remove unused Pair.ID
This change adds type safety to binance requests that are using currency pairs as input.
=> binance: use currency.Pair for request arguments

engine/engine.go, engine/orders_test.go, engine/routines.go, engine/routines_test.go, engine/syncer.go, exchanges/binance/binance_websocket.go, exchanges/bitfinex/bitfinex_websocket.go, exchanges/bitmex/bitmex_websocket.go, exchanges/bitstamp/bitstamp_websocket.go, exchanges/btcmarkets/btcmarkets_websocket.go, exchanges/btse/btse_websocket.go, exchanges/coinbasepro/coinbasepro_websocket.go, exchanges/coinbene/coinbene_websocket.go, exchanges/coinut/coinut_websocket.go, exchanges/ftx/ftx_websocket.go, exchanges/gateio/gateio_websocket.go, exchanges/hitbtc/hitbtc_websocket.go, exchanges/huobi/huobi_websocket.go, exchanges/kraken/kraken_websocket.go, exchanges/lakebtc/lakebtc_websocket.go, exchanges/okgroup/okgroup_websocket.go, exchanges/poloniex/poloniex_websocket.go, exchanges/stream/websocket.go, exchanges/zb/zb_websocket.go
* subscribe if this is required by ws routines or sync manager
* restore previous subscriptions on reconnect (also don't restore anything if there were no subscriptions)
Mostly refactoring
start engine with WS disabled
enable WS via gctcli
=> Engine/websocket: subscribe to default channels only when actually needed

exchanges/bitfinex/bitfinex_websocket.go, exchanges/ftx/ftx_test.go, exchanges/ftx/ftx_websocket.go, exchanges/kraken/kraken_websocket.go, exchanges/okgroup/okgroup_websocket.go, exchanges/orderbook/orderbook.go, exchanges/orderbook/orderbook_types.go, go.sum
Reduces the need to traverse and validate book contents when there is a checksum present from the exchange.
Exchanges affected:
=> Exchanges: Bypass websocket book validation

exchanges/binance/binance_wrapper.go, exchanges/kraken/kraken_wrapper.go
Fixed faulty resp.Time handling in Binance GetOrderInfo method
Kraken always return Cost param on closed orders on QueryOrders request, so It will be useful to use it
API method GetOrder  always returned an error in case of Binance
Added Cost param in Kraken GetOrderInfo method
=> Binance: GetOrderInfo method issue. Kraken - add Cost param to GetOrderInfo output

exchanges/btse/btse_test.go, exchanges/btse/btse_types.go, exchanges/btse/btse_websocket.go, exchanges/btse/btse_wrapper.go, go.sum
BTSE updated its websocket to have a new type of message `event` for subscription acknowledgement and login. Our code assumed we'd always get a `topic` and panicked when it didn't. This is now fixed
- [📈] Bug fix (non-breaking change which fixes an issue)
This was caused by simply connecting to the websocket and receiving a subscription acknowledgement message. Tests have been written to ensure that no unhanded messages cause a panic
This also now filters out REST orderbook updates with zero values as BTSE does not provide enough decimal places in their API responses to have accurate data.
- [📈] go test ./... -race
- [📈] golangci-lint run
- [📈] My code follows the style guidelines of this project
- [📈] I have performed a self-review of my own code
- [📈] I have commented my …
=> Bugfix: BTSE websocket panic + REST orderbook fix

exchanges/coinbasepro/coinbasepro.go, exchanges/coinbasepro/coinbasepro_test.go, go.sum
Fixes Coinbase GetFills/GetOrders issue as identified by whiskeywhiskey in Slack. I don't have any API keys for Coinbase, but the tests now show a correct path.
- [N/A] Any dependent changes have been merged and published in downstream modules
=> Coinbase: Fix path issue for GetFills and GetOrders

exchanges/lbank/lbank_wrapper.go
Our LBANK tests reported an error for kline retrieval. After testing the endpoint, it appears that the limit has changed from 2880 to 2000. This PR amends the enabled limit to reflect this change.
- [N/A] Any dependent changes have been merged and published in downstream modules
=> LBANK: Fix undocumented kline limit adjustment

backtester/common/common_types.go, backtester/eventhandlers/strategies/base/base_types.go, currency/storage_types.go, exchanges/account/account_test.go, exchanges/asset/asset.go, exchanges/binance/binance_test.go, exchanges/ftx/ftx.go, exchanges/ftx/ftx_test.go, exchanges/ftx/ftx_types.go, exchanges/kline/kline.go, exchanges/kline/kline_types.go, exchanges/kraken/futures_types.go, exchanges/okcoin/okcoin_test.go, exchanges/okex/okex_test.go, exchanges/zb/zb.go, portfolio/withdraw/validate_test.go
Adds REST API subaccount support. NOTE: There's currently a duplication issue for portfolio info introduced in https://github.com/thrasher-corp/gocryptotrader/pull/530. Will be addressing this in a separate PR. Also fixes a particular spelling mistake in the codebase 😆
=> FTX: Add REST subaccount support

engine/routines.go, exchanges/account/account_types.go, exchanges/bitmex/bitmex_websocket.go, exchanges/bittrex/bittrex_test.go, exchanges/order/order_types.go, exchanges/poloniex/currency_details.go, exchanges/poloniex/currency_details_test.go, exchanges/poloniex/poloniex.go, exchanges/poloniex/poloniex_test.go, exchanges/poloniex/poloniex_types.go, exchanges/poloniex/poloniex_websocket.go, testdata/http_mock/poloniex/poloniex.json
While going through an account handling update in another PR which will be opened soon. I have come across issues with account order and balance processing. Hopefully, these resolve some issues. 
Websocket update:
Notes: 
* Ticker subscription generation is turned off; still trying to track down issue when tickers and orderbook subscriptions cause an unstable websocket connection. (support ticket has been opened)
*
=> poloniex: websocket update 

.golangci.yml, Makefile, backtester/eventhandlers/exchange/exchange.go, backtester/eventhandlers/exchange/exchange_test.go, backtester/eventhandlers/portfolio/size/size.go, backtester/eventhandlers/portfolio/size/size_test.go, backtester/eventtypes/signal/signal.go, backtester/eventtypes/signal/signal_test.go, backtester/eventtypes/signal/signal_types.go
add buy and sell limit to backtest strategy to buy and sell a specific amount of asset
=> Backtester: Add buy and sell limit for strategies 

engine/routines_test.go, exchanges/binance/binance_websocket.go, exchanges/orderbook/calculator_test.go, exchanges/orderbook/node_test.go, exchanges/orderbook/orderbook.go, exchanges/orderbook/orderbook_test.go
Shazbert and I debugged an orderbook test as a result of this lovely appveyor output: https://ci.appveyor.com/project/thrasher-/gocryptotrader-g5pk0/builds/38887028?fullLog=true
I've changed a few minor things as well.
=> Bugfix: Orderbook locks

README.md, cmd/documentation/exchanges_templates/bittrex.tmpl, cmd/documentation/exchanges_templates/exchanges_trade_readme.tmpl, cmd/documentation/root_templates/root_readme.tmpl, docs/ADD_NEW_EXCHANGE.md, exchanges/bittrex/README.md, exchanges/bittrex/bittrex.go, exchanges/bittrex/bittrex_test.go, exchanges/bittrex/bittrex_types.go, exchanges/bittrex/bittrex_websocket.go, exchanges/bittrex/bittrex_wrapper.go, exchanges/bittrex/bittrex_ws_orderbook.go, exchanges/trade/README.md, testdata/configtest.json
Bittrex API v1.1 reached its EOL 9/30/2020. The current version is v3.
This PR replaces the v1.1 implementation with a v3 implementation, and adds websocket support.
I am currently running this version.
=> Bittrex: Update API v1.1 to v3 and add websocket support

exchanges/ftx/ftx_types.go
I found some typo in ftx_types.go. Those changes enable fetching some fields in private data again. These kind of method is generally supposed not to be tested by CI.
Correct name of fields are here
https://docs.ftx.com/
These fields referred via private methods have to be manually tested, I suppose. To test the fields, I made some order on the web and rewrote my local ```ftx_test.go``` as follows set with my private key;
=> FTX: Fixed typos in ftx_types

exchanges/kraken/kraken_websocket.go
This PR is based off of Vazha's lovely PR: #650 . For context, if you have both `authenticatedSupport` and `authenticatedWebsocketApiSupport` set to `true` in your config, along with having API keys, the websocket will not work, instead, returning "already subscribed" errors.
I thought I would just fix the area that prevented Authenticated Kraken websocket from working without any of the other contended changes.
I tested that the authenticated websocket actually connects and can subscribe to authenticated endpoints successfully.
=> Kraken: Authenticated websocket bugfix

exchanges/binance/binance_test.go, exchanges/binance/binance_types.go, exchanges/binance/binance_websocket.go, go.mod
While looking into the Orderbook manager, I discovered some issues with Binance websockets which led to 3 orders ending up as active orders in the order manager with invalid ids after an order was created and then canceled.
Example message from the execution report highlighting the areas that were wrongly interpreted:
> {"e":"executionReport","E":1625512039095,"s":"BTCUSDT",**"c":"A4kplXxxIvEDqoAKq6xlIf"**,"S":"SELL","o":"LIMIT","f":"GTC","q":"0.00020000","p":"68121.64000000","P":"0.00000000","F":"0.00000000","g":-1,**"C":"QJyBvorya02T3MeyNLc9HT"**,"x":"CANCELED",**"X":"CANCELED"**,"r":"NONE",_"i":6745981401_,"l":"0.00000000","z":"0.00000000","L":"0.00000000","n":"0","N":null,"T":1625512039095,"t":-1,**"I":14416574986**,"w":false,"m":false,"M":false,"O":1625512033495,"Z":"0.00000000","Y":" …
=> Binance: Websocket order update fixes

backtester/config/configbuilder/README.md, cmd/documentation/backtester_templates/backtester_config_configbuilder_readme.tmpl
The typo in flag -config**P**ath breaks running backtest.
=> Backtester: Update flag typo

backtester/backtest/backtest.go, backtester/config/config.go, backtester/config/examples/dca-api-candles.strat, backtester/eventhandlers/exchange/exchange.go, exchanges/gateio/gateio_wrapper.go
A Slack user name Dave highlighted that there was an issue with the backtester regarding GateIO data retreival. I found the following issues:
- GateIO was unable to retrieve candle data if the end date wasn't the current date due to the API not having start/end support and so we were providing the wrong time. The backtester would yell MISSING DATA
- The backtester was having issues with GateIO and currency lookups due to formatting differences between default and request format, so I format currencies in the backtester to match their request format.
- I noticed that CaPiTaLiSaTiOn was impacting backtester settings lookup for exchanges such as "OKCOIN International", so its now loaded lowercase
GateIO's API [has been updated to v4 which has better candle retrieval …
=> BUGFIX: GateIO candle retrieval, backtester formatting

connchecker/connchecker.go, connchecker/connchecker_test.go
In the case of a connection problem, Checker.initialCheck() has to wait for a connection timeout. This fix makes it aware of the CheckInterval setting.
Initially the connchecker tests were blocking locally because of timeouts to "faultyIP" and "faultyHost".
=> connchecker: initialCheck() now also respects CheckInterval

gctrpc/README.md, gctrpc/gen_pb_linux.sh, gctrpc/gen_pb_win.bat, gctrpc/rpc.swagger.json
To ease future addition of gRPC calls, it would be great to use latest versions of generating tools.
This commit updates the corresponding README and generates anew following `gocryptotrader/gctrpc` files:
* `rpc.swagger.json`
* `rpc_grpc.pb.go` [NO CHANGES AFTER NEW GENERATION]
* `rpc.pb.go` [NO CHANGES AFTER NEW GENERATION]
* `rpc.pb.gw.go` [NO CHANGES AFTER NEW GENERATION]
- [*] I have performed a self-review of my own code
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [*] My changes generate no new warnings
- [*] New and existing unit tests pass locally …
=> gctrpc: generate protobuf files with latest versions of tools

CONTRIBUTORS, README.md, backtester/README.md, backtester/backtest/README.md, backtester/backtest/backtest.go, backtester/config/config.go, backtester/eventhandlers/README.md, backtester/eventhandlers/exchange/exchange.go, backtester/eventhandlers/exchange/exchange_test.go, backtester/eventhandlers/exchange/exchange_types.go, backtester/eventhandlers/exchange/slippage/slippage_types.go, backtester/eventhandlers/portfolio/risk/risk.go, backtester/eventhandlers/portfolio/size/size.go, backtester/eventhandlers/statistics/statistics.go, backtester/eventtypes/README.md, backtester/main.go, cmd/documentation/backtester_templates/backtester_backtest_readme.tmpl, cmd/documentation/backtester_templates/backtester_eventhandlers_readme.tmpl, cmd/documentation/backtester_templates/backtester_eventtypes_readme.tmpl, cmd/documentation/backtester_templates/backtester_readme.tmpl, cmd/documentation/documentation.go, cmd/documentation/engine_templates/datahistory_manager.tmpl, engine/datahistory_manager.md
@MadCozBadd noticed an error when the Backtester attempts to sell an asset, it unnecessarily shrinks the sell size in the function `reduceAmountToFitPortfolioLimit`. I've adjusted sell orders to simply not exceed the portfolio amount availible if that somehow were to occur.
I also neatened up an existing function, added a test and added some planned features to the backtester readme
- Use [this RSI strategy](https://gist.githubusercontent.com/gloriousCode/1b5689d6cb985d6a8204463512d9af3d/raw/eb85dd6f1ae1d8302745c2e8946b3e94a068c43a/rsi-test.strat)
- On branch master you will receive order warnings such as ` Order size shrunk from 0.17298078301363376 to 3.2159956297318508e-06 to remain within portfolio limits.`
- On this branch you will receive properly sized sell orders.
=> backtester: Fix selling bug, add planned features list

config/config_types.go, config_example.json, engine/rpcserver.go, engine/rpcserver_test.go
gRPC endpoints currently set  
* ```TickerResponse.LastUpdated```
* ```OrderbookResponse.LastUpdated```
* ```TradeHistory.CreationTime```
* ```OrderDetails.CreationTime```
* ```OrderDetails.UpdateTime```
to timestamps with a precision of **1 second**.
This PR proposes a new configuration attribute -- ```remoteControl/gRPC/timeInNanoSeconds``` -- that changes the precision to **1 nanosecond**.
Affected endpoints are:  
* ```GetTicker()```
* ```GetTickers()```
* ```GetOrderbook()```
* ```GetOrderbooks()```
* ```GetOrders()```
* ```GetManagedOrders()```
* ```GetOrder()```
* ```GetTickerStream()```
* ```GetExchangeTickerStream()```
There are two new tests added in rpcserver_test.go:  
* …
=> gctrpc: endpoints now optionally return timestamps in nanoseconds (configurable)

exchanges/binance/binance_wrapper.go, exchanges/ftx/ftx.go, exchanges/ftx/ftx_test.go, exchanges/ftx/ftx_types.go, exchanges/ftx/ftx_wrapper.go, exchanges/order/limits.go, exchanges/order/limits_test.go
Adds in step increments for price and amount and amount minimum to reduce request errors from API endpoint. 
=> ftx: add basic exchange order execution limits for lower bound

exchanges/ftx/ftx.go, exchanges/ftx/ftx_test.go, exchanges/ftx/ftx_websocket.go, exchanges/ftx/ftx_wrapper.go, exchanges/orderbook/unsafe_test.go
This is based on https://github.com/thrasher-corp/gocryptotrader/pull/729 but with some additional testing and fixes. Thank you to @MarkDzulko for the intial highlighting of the error
It also fixes all other instances which were incorrect 👀
=> FTX: Fix incorrect partially-cancelled order assignment

exchanges/ftx/ftx.go, exchanges/request/request.go
This PR fixes an odd desynchronization that may occur if (1) an order is already "managed", (2) order is already canceled and (3) we try to cancel it from the bot side. What it does basically is it now considers a cancellation successful if the exchange returns one of the following two errors:
* `"Order already closed"`
* `"Order already queued for cancellation"`
=> FTX: order cancellation improvement

exchanges/binance/binance_wrapper.go
Balance.Hold for Binance spot seems wrong as it is set to freeCurrency and not to lockedCurrency.
Using real Binance and other exchange accounts. :)
=> Binance: Fix Balance.Hold for spot

exchanges/btse/btse_wrapper.go, exchanges/gemini/gemini_wrapper.go
Thanks to @ydm for highlighting this issue in https://github.com/thrasher-corp/gocryptotrader/pull/736. This PR fixes up Gemini and BTSE misrepresenting account info for `Hold` amounts
I read the documentation [here](https://docs.gemini.com/rest-api/#get-available-balances) for Gemini and [here](https://www.btse.com/apiexplorer/spot/#getwallets) for BTSE
=> Bugfix: Hold values for BTSE and Gemini

engine/engine.go, engine/helpers.go, engine/sync_manager.go, engine/sync_manager_test.go, engine/sync_manager_types.go, engine/websocketroutine_manager.go, exchanges/interfaces.go
One of our wonderful Slack members: Przemysław Skiba, highlighted an issue:
> 1. SyncManager is created and needs WebsocketRoutineManager as dependency. In my case, during SyncManager startup, WebsocketRoutineManager is nil.
> 2. SyncManager tries set WebsocketDataReceiver to nil object and transforms WS to "connecting" state
> 3. During WebsocketRoutineManager startup, it checks WS state. State is "connecting", so WebsocketRoutineManager returns from start function and not set WebsocketDataReceiver.
> 
> The result is no updates from WS routine
We have the `CurrencyPairSyncer` depending on the `WebsocketRoutineManager` and the `WebsocketRoutineManager` wants the  `CurrencyPairSyncer`. The `CurrencyPairSyncer` was given the ability to control the websocket connections, but its not …
=> Bugfix: Syncer & websocket circular dependency

engine/engine.go, engine/exchange_manager.go, engine/exchange_manager_test.go, exchanges/sharedtestvalues/customex.go
This PR allows applications that import GCT as a lib to declare custom exchanges that do not require full GCT integration.
- [] I have added tests that prove my fix is effective or that my feature works
=> engine/exchange manager: Add support for custom exchanges

cmd/gctcli/pair_management.go, cmd/gctcli/websocket_management.go
Fix enable flag for various gctcli commands
Fixes https://github.com/thrasher-corp/gocryptotrader/issues/751
```
$ ./gctcli pair enable --exchange binance --pairs "VITE-BTC" --asset spot
{
"status": "success"
}
```
=> gctcli: Fix enable flag for various commands

exchanges/bittrex/bittrex_types.go, exchanges/bittrex/bittrex_ws_orderbook.go, exchanges/orderbook/depth.go, exchanges/orderbook/depth_test.go, exchanges/orderbook/orderbook.go, exchanges/stream/buffer/buffer.go, exchanges/stream/buffer/buffer_test.go
Bittrex fails to recover after a failed websocket orderbook update. This PR addresses this by
- Testing if books have been cleared
- Assigning options when loading snapshot
Fixes #746 
The PR has been tested by dropping ws orderbook updates on-demand.
=> Bittrex: Enable ws orderbook sync recovery (resolves #746)

exchanges/binance/binance_test.go, exchanges/binance/binance_types.go, exchanges/binance/binance_websocket.go, exchanges/ftx/ftx_websocket.go, exchanges/order/order_types.go
With c38757a68990858aa989557d2cdfb8be1e7f932f a number of issues were introduced. Some of them are:
1. instead of reading the order status, which is pushed through the websocket, floating point numbers were compared for equality :)
2. there was no average price populated
3. incorrectly fee was assigned to cost
4. "m" was being overridden by "M" 
This PR fixes all of them and, on top of that:
1. orders fields of WsOrderUpdateData the way they are described in the latest version of Binance docs + that's the same order when they come out of the websocket
2. adds and populates order.Detail.FeeAsset
3. sorts out mixed := and var declarations
4. orders temporary variables by the order they are used
=> Binance/FTX: spot websocket fixes

cmd/gctcli/commands.go, cmd/gctcli/data_history.go, cmd/gctcli/pair_management.go, cmd/gctcli/trades.go, cmd/gctcli/validation.go, cmd/gctcli/websocket_management.go, engine/rpcserver.go
Since now exchange names can be user-assigned we can no longer have
client-side validation, all exchange name validation must now occur
on the server (it was already doing that).
=> gctcli: remove all exchange name client-side validation

exchanges/binance/binance_ufutures.go
Fix some issues for `exchanges/binance/binance_ufutures.go#UKlineData` function
1. `UKlineData` func introduce some wrong parameters which lead to wrong response
start_time -> startTime
end_time -> endTime
2. Incorrect supported interval list
`ufuturesKlineData          = "/fapi/v1/klines?"`
The endpoint for this func can support all intervals the list of `validFuturesIntervals`
uValidPeriods -> validFuturesIntervals
3. Make consistency for time format with others Kline fetching func (ex: GetSpotKline)
time.Unix() --> convert.TimeFromUnixTimestampFloat 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant …
=> Binance: Fix UKlineData func

exchanges/ftx/ftx_test.go
I made a mistake in a previous PR which allowed test fee calculation to work without API keys present. Problem is, when API keys are present, authenticated tests don't run as `areTestAPIKeysSet()` requires `exchCfg.API.AuthenticatedSupport = true` be set before setting API keys, which then makes `GetFee` require API keys... 
I tested with keys and then authenticated tests could run.
=> FTX: allow authenticated tests to run

exchanges/account/account.go, exchanges/account/account_test.go
When working with `account.Balance`s, getting the available amount of an asset is a very common thing to do, so such a method would be helpful.
=> Account: Add account.Balance.Available() method

engine/apiserver.go, engine/engine.go, engine/exchange_manager.go, engine/exchange_manager_test.go, engine/helpers.go, engine/order_manager.go, engine/order_manager_test.go, engine/order_manager_types.go, engine/portfolio_manager.go, engine/rpcserver.go, engine/rpcserver_test.go, engine/subsystem_types.go, engine/sync_manager.go, engine/websocketroutine_manager.go, exchanges/bittrex/bittrex_wrapper.go, exchanges/order/order_test.go, exchanges/order/orders.go
When a placed order is filled or partially filled, the orderStore is expected to update the order status accordingly, both in WS and in REST mode. Currently, for exchanges where no websocket stream is available/active, active orders will never get updated: they'll never turn into filled or partially filled orders.
This PR addresses that issue by tracking missing orders and performing REST calls to verify and update their status.
Fixes #772
=> engine/order manager: Initial REST managed order updating (resolves #772)

exchanges/huobi/huobi_wrapper.go
Fix spot asset account info retrieval on Huobi
- [] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [] I have added tests that prove my fix is effective or that my feature works
=> huobi: don't overwrite account balances when request spot asset

exchanges/coinbasepro/coinbasepro_wrapper.go
Remove "settled" from status when querying from Coinbase Pro for orders. As from Coinbase Pro's documentation: "Valid statuses: 'open', 'pending', 'rejected', 'done', 'active'."
Doc: https://docs.pro.coinbase.com/#list-orders
Fixes # Error when querying for order history from Coinbase Pro "CoinbasePro unsuccessful HTTP status code: 400 raw response: {"message":"settled is not a valid status"}"
Submitted order on Coinbase Pro, then tested by calling function "GetOrderHistory()" with Coinbase Pro config setup with my exchange credentials and successfully got filled orders.
=> CoinbasePro: Remove settled from order history status

exchanges/coinbasepro/coinbasepro_test.go, exchanges/coinbasepro/coinbasepro_wrapper.go
Allow getting order history without restricting to a currency pair as supported by Coinbase Pro: https://docs.pro.coinbase.com/#list-orders
"product_id: optional"
Also added Price in order to be returned.
Fixes # N/A
Tested locally by retrieving order with my credentials to Coinbase Pro.
=> CoinbasePro: GetOrderHistory pair handling improvements

exchanges/kraken/kraken_wrapper.go
Fixes issue on UpdateAccountInfo of Kraken futures, it was returning the symbol instead of the actual currency code
- [] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [] I have added tests that prove my fix is effective or that my feature works
=>  kraken futures: fix account info currency pairs

exchanges/ftx/ftx_websocket.go
The "ticker" FTX WS event yields best bid and ask quantities, but these are not applied to the created ticker.Price structure.
=> ftx/ws/ticker: Populate best bid/ask quantities

exchanges/binance/binance_websocket.go, exchanges/binance/binance_wrapper.go
Expose Binance trade feed through channel
=> binance: allow exposure of trade feed through websocket data channel

backtester/common/common_types.go, backtester/data/data_test.go, backtester/eventhandlers/exchange/exchange.go, backtester/eventhandlers/portfolio/holdings/holdings.go, backtester/eventhandlers/portfolio/holdings/holdings_types.go, backtester/eventhandlers/statistics/currencystatistics.go, backtester/eventhandlers/statistics/currencystatistics_test.go, backtester/eventhandlers/statistics/fundingstatistics.go, backtester/eventhandlers/statistics/statistics.go, backtester/eventhandlers/strategies/base/base.go, backtester/eventhandlers/strategies/dollarcostaverage/dollarcostaverage.go, backtester/eventhandlers/strategies/rsi/rsi.go, backtester/eventhandlers/strategies/top2bottom2/top2bottom2.go, backtester/eventtypes/kline/kline.go, backtester/eventtypes/kline/kline_test.go, backtester/funding/funding.go
This PR fixes the issue raised by @MeanSquaredError where there would be a zero value being divided. The fix is to use a previous benchmark's data when a price is zero/missing. Its not accurate, but a warning is displayed and it skews data a lot less than calculating with zeroes.
Verification that the strategy posted [here](https://github.com/thrasher-corp/gocryptotrader/issues/840) now works:
I also noticed a couple of other issues during testing:
- Strategies such as `dca-api-candles-multiple-currencies.strat` would fail due to multiple instances of USDT funding Items and USD tracking candles not being appropriately set
- The initial valuation calculation in Holdings/the output report were _way_ off. The calculation is now based upon the initial closing price
Before:
After:
Fixes # …
=> Backtester: Fix dividing by zero when missing data

exchanges/binance/cfutures_types.go, exchanges/binance/type_convert.go
FuturesAccountInformation.Positions had some fields missing, which are now added.
By actually interacting with Binance Coin-M Futures.
=> Binance: Add position fields to FuturesAccountInformation

exchanges/huobi/huobi_futures.go
Fix wrong return type of FGetPositionsInfo
=> huobi futures: fix return type when fetching positions

log/logger.go, log/logger_setup.go, log/sublogger_types.go
This allows applications that import GCT to define their own
writer on their own terms.
=> log: expose output writer interface

go.mod, go.sum
Bump go version to 1.17.0 from 1.13. As there are method only available from go version 1.17.0 in https://github.com/thrasher-corp/gocryptotrader/blob/master/common/convert/convert.go#L58. `time.UnixMilli`
verion bump to 1.17.0.
=> build: bump go version in go.mod

backtester/data/kline/database/database_test.go, backtester/main.go, cmd/apichecker/apicheck.go, cmd/apichecker/apicheck_test.go, config/config.go, database/repository/candle/candle_test.go, database/repository/datahistoryjob/datahistoryjob_test.go, database/repository/datahistoryjobresult/datahistoryjobresult_test.go, database/repository/exchange/exchange_test.go, database/repository/script/script_test.go, database/repository/trade/trade_test.go, database/repository/withdraw/withdraw_test.go, database/testhelpers/test_helpers.go, engine/engine.go, exchanges/exchange_test.go, exchanges/kline/kline_test.go, gctscript/vm/vm_test.go, log/logger.go, log/logger_multiwriter.go, log/logger_rotate.go, log/logger_rotate_types.go, log/logger_setup.go, log/logger_test.go, log/logger_types.go, log/loggers.go, log/sublogger.go, log/sublogger_types.go
Noticed some things that could be improved when testing another log PR. 
* Fix bug when adding and removing writers
* Optimize newLogEvent to return only the fix sized []byte from pool and and not a struct. Reuse param variables already included in stack. 
* Expand test coverage. 
* Fix some race issues.
NOTE: As a quick test I dropped the file size to 1MB, that proved to write to the initial log file and then rotate to other files which was expected. On a new instance it wrote to the old file filling up more then over flowing to other files which can make logs a bit disjointed. Maybe we can make improvements on this in the future.
Please describe the tests that you ran to verify your changes. Provide …
=> log: fix bug,  expand test coverage and slightly optimize

exchanges/kraken/kraken_futures.go
Generate a larger nonce on Kraken Futures requests to avoid same millisec collisions, a better mechanism is maybe possible but this quick fix should decrease dramatically the number of nonce collisions
=> kraken futures: generate a larger nonce on requests

engine/helpers.go, exchanges/okgroup/okgroup_wrapper.go
Repairs panic when no wallet information was returned via `GetDepositAddress` and a nil address was returned with a nil error. 
=> engine/okgroup: fix panic when calling GetDepositAddress()

exchanges/request/options.go, exchanges/request/report.go, exchanges/request/request.go, exchanges/request/request_types.go
This PR allows applications to set an optional global reporter that will provide observability over latency of all HTTP requests (eg. through Prometheus). It also allows a per-exchange setting that is overridden by a global one.
=> request: provide observability over HTTP request latency

exchanges/kraken/futures_types.go, exchanges/kraken/kraken_futures.go
Kraken Futures supports a `mkt` order type which is a market order at
best price with a 1% order protection.
=> kraken futures: add support for market orders

exchanges/exchange.go
Stop erroring out when receiving execution reports from currency pairs
that have not been enabled. In the use-case where multiple services consume market data from different currency pairs on the same account it happens that eg. a service handling ETH/USDT gets execution reports from a separate service handling BTC/USDT on the same account, no big side effects but error rates increase somewhat damaging observability effectiveness.
=> exchanges: make ErrPairNotFound an exportable error

exchanges/huobi/huobi_futures.go
As per Huobi Futures documentation, client order id must be an
integer field in the request. For most other exchanges this is a string
field so to accomodate we keep the string representation and convert
to a number right before the request goes on the wire.
=> huobi futures: fix client order id submit order

exchanges/huobi/huobi_wrapper.go
Numeus quants informed me that `optimal_20` is a more accurate depiction of a market order.
=> huobi futures: improve market order type

exchanges/account/account.go, exchanges/account/account_test.go, exchanges/account/account_types.go, exchanges/binance/binance_wrapper.go, exchanges/bitmex/bitmex_wrapper.go, exchanges/coinbasepro/coinbasepro_wrapper.go
Set account id when available, changes affecting Binance USDTMarginFutures, Coinbase Spot.
N/A
Tested Binance/Coinbase by cross-checking api response.
Coinbase Pro is a bit confusing as they have both "profile id" and "account id"
Their response for account balances looks like below:
#
Which I believe the id is what they call the "account id" but is more like an asset-specific id, and profile_id is what GCT call "ID" in subAccount
reference:
https://forums.coinbasecloud.dev/t/how-do-i-get-account-id-for-rest-api/231/3
Binance reference:
https://dev.binance.vision/t/binance-account-id/1418
I also tried to look at CCXT's implementation and api docs but couldn't find more exchanges that …
=> Exchanges: Set AccountInfo ID when available

exchanges/binance/binance_wrapper.go, exchanges/bitfinex/bitfinex_wrapper.go, exchanges/bitmex/bitmex_wrapper.go, exchanges/bittrex/bittrex_wrapper.go, exchanges/btcmarkets/btcmarkets.go, exchanges/btcmarkets/btcmarkets_test.go, exchanges/btcmarkets/btcmarkets_types.go, exchanges/btcmarkets/btcmarkets_websocket.go, exchanges/btcmarkets/btcmarkets_wrapper.go, exchanges/coinbasepro/coinbasepro_wrapper.go, exchanges/coinut/coinut_wrapper.go, exchanges/hitbtc/hitbtc_wrapper.go, exchanges/kraken/kraken_wrapper.go, exchanges/orderbook/depth.go, exchanges/orderbook/depth_test.go, exchanges/poloniex/poloniex_wrapper.go, exchanges/stream/buffer/buffer.go, exchanges/stream/buffer/buffer_test.go, exchanges/stream/buffer/buffer_types.go, exchanges/stream/websocket.go, exchanges/stream/websocket_types.go
*Adds websocket checksum orderbook validation. 
*Fetches level 1 book via wrapper instead of level 2 ~as this can be~ as level 2 can be cached up to 10 seconds. 
=> btcmarkets: Add websocket orderbook checksum validation

currency/pairs.go, currency/pairs_test.go
Adds a method to see if a code is contained in the currency pairs list. `Has()`
Adds a method to construct from a pairs list with a list of currencies. `GetPairsByCurrencies`
=> currency: Add methods to pairs type

exchanges/orderbook/depth.go, exchanges/orderbook/depth_test.go, exchanges/orderbook/orderbook.go, exchanges/orderbook/unsafe.go, exchanges/orderbook/unsafe_test.go
Exports NewDepth functionality for testing and implementation outside of the library. 
Adds methods for basic checks and data fetching directly from the linked list. 
=> orderbook: export NewDepth(), add methods to orderbook.Unsafe type

backtester/config/config_test.go, backtester/report/report_test.go, common/file/archive/zip_test.go, common/file/file_test.go, config/config_encryption_test.go, config/config_test.go, engine/database_connection_test.go, engine/engine_test.go, engine/rpcserver_test.go
A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := ioutil.TempDir("", "")
if err != nil {
t.Fatal(err)
}
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```
=> test: use `T.TempDir` to create temporary test directory

engine/engine.go, engine/engine_test.go, engine/websocketroutine_manager.go, engine/websocketroutine_manager_test.go, engine/websocketroutine_manager_types.go
Allows to easily register a data handler method for websocket data if needed for external strategy inspection. 
=> engine: Add websocket data handler register function

backtester/config/config_test.go, backtester/config/examples/ftx-cash-carry.strat, backtester/config/examples/rsi-api-candles.strat, backtester/engine/backtest_types.go, backtester/engine/setup.go, backtester/eventhandlers/portfolio/portfolio.go, backtester/report/tpl.gohtml
While working on my other branch I noticed there were some strategies not working. Then I noticed they didn't work on `master` either.
This fixes some typos with errors and the report template. ~I set `err = nil` after each of the `errors.Is` processing exceptions to prevent this kind of fall-through from happening again, but I'm happy to revert those if you don't like it.~ edit: this is no longer the case
=> Backtester: mini bug fixes

currency/code.go, currency/code_test.go, currency/code_types.go, currency/storage.go
* Implement map of currency.Item instead of slice
* Use upper case currency code string as key identifier 
* cleaned up some coderinos
This should have a good knock on affect to the speed of currency.NewPair functions as it was iterating over 3k items * 2 for each currency side and this was compounded across different routines.  
=> currency: boost retrieval speed when calling currency.NewCode()

exchanges/binance/binance_wrapper.go
There is already an `ImmediateOrCancel` flag within `order.Submit`. Just using it when set in the `SubmitOrder` wrapper function
=> Binance: add IOC support to SubmitOrder wrapper

exchanges/stream/stream_types.go, exchanges/stream/websocket.go, exchanges/stream/websocket_connection.go, exchanges/stream/websocket_test.go, exchanges/stream/websocket_types.go
There's a latency reporter for HTTP requests. This PR adds a similar latency reporter around `SendMessageReturnReponse` websocket call.
Since this is a WS message request and the signature is generally added from inside the client, the reliable way to match against the request outside of the client is the request message itself, which is why it is sent to the latency reporter.
=> websocket: add SendMessageReturnResponse latency reporter

exchanges/binance/binance.go, exchanges/binance/binance_cfutures.go, exchanges/binance/binance_live_test.go, exchanges/binance/binance_test.go, exchanges/binance/binance_ufutures.go
`time.UTC().Unix()` -> `time.UTC().UnixMilli()`
ALSO: Sets correct outbound start and end time strings for USDT and coin margined futures
Fixes #1038
=> binance: adjust outbound start and end time payload strings and update unix to milliseconds

currency/pair_methods.go, currency/pair_test.go
I'm not sure this is the best place for this fix, but with FTX on some submit order calls (spot, with IOC), the returned data includes both `market` with the asset pair and `future` with `null`.
The `null` ends up in currency pair `UnmarshalJSON` resulting in an error for a successful SubmitOrder call.
I am not entirely sure if this will be a breaking change
If this looks ok at face value I'm happy to add some unit tests[
=> ftx: fix null currency.Pair UnmarshalJSON

exchanges/stream/websocket.go
I've been noticing some reconnection issues and tracking it down, it looks like there's a condition that causes deadlock during websocket shutdown. 
Since this is in the traffic monitor which doesn't seem to be doing anything other than monitoring for traffic this seems fairly safe to do.
Not sure how to write a reliable unit test.
might be the fix for #901, #761 and possibly #683 as the issues are all similar to what I was noticing in my logs
also consider improving test coverage whilst working on a certain …
=> websocket: fix shutdown deadlock

exchanges/request/request.go
When http client.Do fails I don't think it makes sense to measure latency since this is due to things like connectivity issues rather than measuring the latency of the request-response cycle.
I thought about passing around the resp/err to the Latency call to let this be checked down the line, but ultimately I don't really see a use case for it as the error is passed down the line anyway. 
Happy to hear differing opinions.
=> requester: Remove httpclient.Do errors from latency measurement

exchanges/kraken/kraken.go, exchanges/kraken/kraken_futures.go, exchanges/kraken/kraken_wrapper.go
👋 
Another small fix. Kraken futures doesn't use the configured url right now. This PR fixes it.
=> Kraken: use configured endpoint for futures

exchanges/coinbasepro/coinbasepro_test.go, exchanges/coinbasepro/coinbasepro_wrapper.go
This PR fixes an issue when placing Market orders with the CoinbasePro wrapper interface.
To trigger this issue the Submit struct needs to look like this:
```
gctPair, err := currency.NewPairFromString(pair.Symbol)
if err != nil {
// ...
}
submit := order.Submit{
Exchange:  "coinbasepro",
Amount:    0.001,
Type:      order.Market,
Side:      order.Buy,
AssetType: asset.Spot,
Pair:      gctPair,
}
resp, err := e.SubmitOrder(ctx, &submit)
```
The code was passing `Amount` both as `size` and `funds` parameters. These two parameters are optional (one of them must be provided) but have different units. The exchange complained about the precision of "funds" being too accurate, while only the size should have been set.
Error:
`CoinbasePro unsuccessful HTTP status code: 400 raw response: …
=> CoinbasePro: Fix funds parameter for market orders

engine/helpers.go, engine/helpers_test.go
Going over a PR empty string were being inserted by accident this attempts to bypass and alert improper potential implementation. 
=> engine: filter and warning for empty string when syncing all deposit addresses

exchanges/asset/asset.go, exchanges/okx/okx.go, exchanges/okx/okx_test.go, exchanges/okx/okx_types.go, exchanges/okx/okx_websocket.go, exchanges/okx/okx_wrapper.go
The Instrument type "option" is what was added to the assets list. But, the instrument name "options" is supported by other exchanges. So, I have created(amended) the custom method calls for Okx outgoing calls to convert "options" to "option"; that way we can use the String() method call to get the asset Item name for other exchanges instead of creating a conversion method for each.
Also, we can use either "option" or "options" in the config.json files or with the asset.New() method and the result will be same. …
=> asset: Rename option to options

backtester/btcli/commands.go, cmd/gctcli/commands.go, cmd/gctcli/data_history.go, cmd/gctcli/futures.go, cmd/gctcli/orderbook.go, cmd/gctcli/pair_management.go, cmd/gctcli/trades.go
With a version update of package `urfave/cli/v2`, it can now infer the command description without needing to explicitly tell it. Also, the old way doesn't work.
`master`
```
go run . gethistoriccandles
No help topic for 'gethistoriccandles'
exit status 3
```
`this branch`
```
go run . gethistoriccandles
NAME:
gctcli gethistoriccandles - gets historical candles for the specified granularity up to range size time from now.
USAGE:
gctcli gethistoriccandles command [command options] <exchange> <pair> <asset> <rangesize> <granularity>
COMMANDS:
help, h  Shows a list of commands or help for one command
OPTIONS:
--exchange value, -e value     the exchange to get the candles from
--pair value                   the currency pair to get the candles for
--asset value                  the asset type …
```
=> cli: fix description output using new version of urfave/cli/v2

cmd/gctcli/commands.go, cmd/gctcli/data_history.go, cmd/gctcli/futures.go, cmd/gctcli/helpers.go, cmd/gctcli/technical_analysis.go, cmd/gctcli/trades.go, engine/rpcserver.go, engine/rpcserver_test.go
I noticed this when parsing time for #1091 that the start end times looked more funky than I'd like them to be. Turns out the implementation of `negateLocalOffset` was off. 
When running `gethistoriccandles` it would be returning candle data hours outside of my expected timeframe. Its harder to measure since `gethistoriccandles` truncates the time, but it was well over 11 hours + truncated time. I was expecting candle data up to late 22nd Dec/early 23rd Dec. Instead I was getting 1pm on the 22nd. See below:
```
"start": "2022-12-20 21:00:00",
"end": "2022-12-22 13:00:00",
```
where now it is in line with my expectations where it is in line with the truncated time
```
"start": "2022-12-21 08:00:00",
"end": "2022-12-23 00:00:00",
```
This also matches `negateLocalOffsetTS`'s implementation …
=> cli: rpc time parsing

config/config.go, config/config_types.go, exchanges/binance/binance_wrapper.go, exchanges/binanceus/binanceus_wrapper.go, exchanges/bitfinex/bitfinex_wrapper.go, exchanges/bithumb/bithumb_wrapper.go, exchanges/bitmex/bitmex_wrapper.go, exchanges/bitstamp/bitstamp_wrapper.go, exchanges/bittrex/bittrex_wrapper.go, exchanges/btcmarkets/btcmarkets_wrapper.go, exchanges/btse/btse_wrapper.go, exchanges/bybit/bybit_wrapper.go, exchanges/coinbasepro/coinbasepro_wrapper.go, exchanges/coinut/coinut_wrapper.go, exchanges/exchange_test.go, exchanges/gateio/gateio_wrapper.go, exchanges/gemini/gemini_wrapper.go, exchanges/hitbtc/hitbtc_wrapper.go, exchanges/huobi/huobi_wrapper.go, exchanges/kraken/kraken_wrapper.go, exchanges/okcoin/okcoin_wrapper.go, exchanges/okx/okx_wrapper.go, exchanges/poloniex/poloniex_wrapper.go, exchanges/stream/websocket.go, exchanges/stream/websocket_types.go, exchanges/zb/zb_wrapper.go
- this fixes a bug where the connection monitor delay config value does not get set to the websocket on intialization.
=> stream: set connection monitor delay.

cmd/exchange_template/exchange_template.go, cmd/exchange_template/exchange_template_test.go
Restores automatic testing of the example template tool to ensure that the templates are valid whenever there is an update done to the exchange wrappers.
=> exchange_template: Fix test regression

exchanges/okx/okx.go
When I used the okx exchange to sell the operation, the error "`invalid order side`" was reported. I deeply analyzed the code and found this judgment logic bug.
=> OKx: Fix order side validation typo

exchanges/okx/okx_test.go, exchanges/okx/okx_wrapper.go
Enabling authenticated ws for okx would block the entire exchange client.
The channels for the ws multiplexer weren't made.
So any interaction with it would block.
Tests passed because they invasively setup the multiplexer.
There are quite a few architectural risks with this implementation pattern, such as leaking an uncancellable goro in a for-select loop. Ideally WsConnect should take a cancellable context and any selects should watch for ctx.Done()
That's a very invasive and pervasive change though, so this fix is as minimal and atomic as possible.
Will consider opening a PR for cancellable context or improving this multiplexer pattern.
=> OKX: Fix authenticated websocket blocking during login

exchanges/btse/btse_types.go, exchanges/btse/btse_wrapper.go
BTSE returns 0 for both highest bid and lowest ask if there is no order book data. There is no way to  take or provide liquidity for these pairs. They are not found on the frontend either.
=> BTSE: Filter no liquidity pairs

exchanges/okx/okx.go, exchanges/okx/okx_types.go, exchanges/okx/okx_wrapper.go
Fixes `UpdateAccountInfo` to use Trading account balances instead of Funding account.
It looks like this was an oversight.
No other exchange uses the funding account for balance and it wouldn't make sense.
Again, this aims to be minimally invasive and backwards compatible, so GetBalance is left alone to preserve compat.
There's one change that could be considered breaking, `EquityOfCurrency` is now just `Equity`
=> OKX: Fix balance using funding account

exchanges/okx/okx_test.go, exchanges/okx/okx_wrapper.go
Adds support for PriceStepIncrementSize and MinAmount limits
=> OKX: Support exchange order limits

exchanges/okx/okx.go
Fix limit of 100 rejected
Allow a limit of 0 for using the default value of limit (currently 100).
=> Okx: Fix GetFundingRateHistory limit

engine/engine.go, engine/engine_test.go, engine/websocketroutine_manager.go, engine/websocketroutine_manager_test.go, engine/websocketroutine_manager_types.go
Consumers must be able to tell when it's safe to start new
subscriptions. Before this fix any new subscriptions would get unsubbed
as part of the flush during `websocketRoutine`.
This fix also significantly simplifies the state management, removing
atomics in favour of using the existing mutex as per
the [atomics docs](https://pkg.go.dev/sync/atomic#pkg-overview).
This fix does not require this simplification but it's much clearer with
it. Specifically in Stop() where we can't do an atomic swap because we
The shutdown channel was already in setup.
Consumers could reasonably expect it to not be replaced in between the
two, and it's not really part of Start to assign it.
Without exposing the manager users don't know when it's ready to use.
=> wsManager: Fix IsRunning true before flushed

cmd/documentation/communications_templates/telegram.tmpl, communications/base/base.go, communications/telegram/README.md, communications/telegram/telegram.go, communications/telegram/telegram_test.go, config/config.go, config_example.json, testdata/configtest.json
Takes the work done in https://github.com/thrasher-corp/gocryptotrader/pull/1194 by @shanhuhai5739 and adds an authorised client list so only authenticated users can receive pushed events.
=> telegram: Fix pushing events to an authorised client list

exchanges/stream/websocket.go
When an existing ws disconnects the connection manager goro will call Connect.
This fix prevents Connect trying to start another connection manager if it's already running
=> websocket: Fix redundant connection monitor error upon disconnect

exchanges/binance/binance_test.go, exchanges/binance/binance_types.go, exchanges/binance/type_convert.go
Fixes:
`Could not convert to executionReport structure json: cannot unmarshal number into Go struct field .data.w of type bool`
Happens because a new W field is being unmarshalled into the old w.
This new field was added in the 2022-12-05 updates.
It's not always in an execution report, but only if isWorking=true
=> Binance: Fix WorkingTime breaking executionReport

exchanges/stream/websocket_connection.go, exchanges/stream/websocket_test.go
WebsocketConnection.parseBinaryResponse() checks for incoming GZIP messages by testing 2 magic bytes - without performing a bounds check. Receiving bad messages can cause panic:
```
panic: runtime error: index out of range [0] with length 0
goroutine 2583960 [running]:
github.com/thrasher-corp/gocryptotrader/exchanges/stream.(*WebsocketConnection).parseBinaryResponse(0xc000624b40?, {0xc000679600?, 0xc000b97f08?, 0x3?})
/home/user/go/src/github.com/thrasher-corp/gocryptotrader/exchanges/stream/websocket_connection.go:274 +0x265
github.com/thrasher-corp/gocryptotrader/exchanges/stream.(*WebsocketConnection).ReadMessage(0xc0003bd710)
/home/user/go/src/github.com/thrasher-corp/gocryptotrader/exchanges/stream/websocket_connection.go:251 +0x235 …
```
=> websocket: Check for slice size to avoid panic when classifying empty binary message

currency/pair_methods.go, currency/pair_test.go, currency/pair_types.go
Adds minor helper methods for a currency pair to derive order parameter details from a currency either being sold; which can be derived from account balance, or a specific currency wishing to be purchased.
**Suggestions for naming conventions are welcomed**
_NOTE: This is mainly for spot_
=> currency: Add OrderParameters helpers for currency pair

exchanges/okx/okx.go, exchanges/okx/okx_websocket.go, exchanges/okx/okx_wrapper.go
G K's profile says he will be away for a bit, and #1202 has not had an answer. This PR shamelessly steals the work from #1202  and also applies a fix for instrument type casing allowing "orders" auth subscription to work:
```
[DEBUG] | WEBSOCKET | 08/06/2023 13:22:19 | Okx websocket connection: message received: {"event":"subscribe","arg":{"channel":"orders","instType":"FUTURES"}}
```
I tested #1202 and then also tested that now things subscribe properly
=> OKx: Fix websocket subscriptions and casing

engine/order_manager.go, engine/order_manager_types.go
This ensures that orders are processed as soon as orderManager claims to have started.
Specifically this will fix an eager call to CancelAllOrders not finding anything until after the first Interval run.
DriveBy:     orders: Fix reset timer call
This fix is small niggle.
The existing code was more complicated than it needed to be, whilst also ignoring the return of `timer.Reset` and the conditional need to drain the channel. It's unlikely but possible during transient resource starvation.
See [Timer docs](https://pkg.go.dev/time#Timer.Reset)
=> orders: Fix manager not processing immediately

exchanges/okx/okx_test.go, exchanges/okx/okx_type_convert.go, exchanges/okx/okx_types.go, exchanges/okx/okx_wrapper.go
This fixes: `json: invalid use of ,string struct tag, trying to unmarshal "" into float64` when TwapSz or other fields are empty, which happened briefly today.
As a DriveBy it also simplifies the exposed Instrument type to native types only.
=> Okx: Fix Instrument unmarshal

contrib/spellcheck/exclude_lines.txt, exchanges/okx/okx_test.go, exchanges/okx/okx_types.go, exchanges/okx/okx_wrapper.go
While looking at something completely different I was concerned at how OKx only had 1 entry in its orderbook when on REST. I assumed it was a bad pair, but websocket returns many more results...
Turns out OKx's default depth is **one**: [source](https://www.okx.com/docs-v5/en/#rest-api-market-data-get-order-book)
- `TestGetOrderBookDepth`
=> okx: REST orderbook depth fix

exchanges/order/order_test.go, exchanges/order/orders.go
UpdateOrderFromDetail did not merge the client order id in.
=> Orders: Fix ClientOrderID not updated in merge

dispatch/dispatch.go, dispatch/dispatch_test.go, dispatch/dispatch_types.go, dispatch/mux.go, engine/rpcserver.go, exchanges/account/account_test.go
When unsubscribing using the dispatcher, a `<-chan interface{}` is put in a pool. When subscribing results in getting a used channel as a `chan interface{}` from the pool, a type assertion error happens. 
One solution would be to store all used channels as bidirectional channels. Alternative solutions could be possible too.
Fixes #1236
Added a section to the dispatch test 'TestUnsubscribe' that would fail with the current code:
```
=== NAME  TestUnsubscribe
dispatch_test.go:229: received: 'type assertion failure' but expected: '<nil>'
```
But passes with the proposed solution.
=> dispatch: channel reuse fix

exchanges/kraken/kraken.go
This fix addresses a regression in Kraken's auth requests where an empty error message would cause them to fail 😆
=> Kraken: Fix auth request regression

exchanges/account/credentials.go, exchanges/credentials.go, exchanges/credentials_test.go
Further investigation of the PR here https://github.com/thrasher-corp/gocryptotrader/pull/1199 showed that there indeed was an issue with external package usage specifically when an exchange requires their API secret to be base64 decoded. This impacted the user whether they used `SetCredentials` (subsequent auth calls would throw a base64 decode error as it had already been decoded when `VerifyAPICredentials` is triggered again) or whether they used the SetX(y) API methods as subsequent calls to `VerifyAPICredentials` would just test decoding of the secret but not assign the result if it.
=> credentials: Fix issue with external package usage

cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go
PR #1255 highlights that when populated, the function will be called when it shouldn't be. Order execution limits is not currently made in a way that works with the exchange wrapper standards test suite. Given that the other functions for order limits are ignored, this just adds onto that rather than reworking limits.go to support the tests because its not a common function to be supported.
=> standards test: ignore CheckOrderExecutionLimits func

cmd/gctcli/main.go
As someone who frequently debugs the application while testing, its lame to have the context cancelled while inspecting code which then just returns conctext cancelled errors. This PR just adds a quick flag to prevent it happening. Naturally its at the requester's peril to have no deadline that's why its opt in
You can use it as such:
`go run . --ignoretimeout gettickerstream binance btc-usdt spot`
or
`go run . --it gettickerstream binance btc-usdt spot`
=> gctcli: Add command line parameter to ignore default context timeout

engine/engine.go
Found with go run -race:
```
WARNING: DATA RACE
Write at 0x00c0005c5740 by goroutine 125:                                                                                                                                                       github.com/thrasher-corp/gocryptotrader/engine.(*Engine).Start.func2()
/Users/gbjk/go/pkg/mod/github.com/gbjk/gocryptotrader@v0.0.0-20230619070715-ae6f283f6be6/engine/engine.go:524 +0x58
Previous write at 0x00c0005c5740 by main goroutine:                                                                                                                                             github.com/thrasher-corp/gocryptotrader/engine.(*Engine).Start()
/Users/gbjk/go/pkg/mod/github.com/gbjk/gocryptotrader@v0.0.0-20230619070715-ae6f283f6be6/engine/engine.go:576 …
```
=> engine: Fix Start method data race on err var

engine/subsystem_types.go, engine/sync_manager.go, engine/sync_manager_test.go, engine/sync_manager_types.go
This is a fairly invasive change which addresses the amount of work the sync manager does each cycle and the cycle intervals. We switch to using discrete locks for each type of work on each pair, so each worker can take a discrete chunk of work safely. For performance and simplicity we now use a map for the currencyPairs.
* fix reporting when a websocket is reconnected
* fix not switching REST off after websocket available again
* fix race condition in isProcessing flag
This PR still could go further by avoiding cycling through everything each time, and by pushing some one-time work for adding enabled pairs down to a later stage off the hot path.
This was the smallest chunk of refactoring I felt could address everything without changing too much.
Significant manual testing done with a …
=> SyncManager: Optimise and fixes

exchanges/okx/okx_types.go, exchanges/okx/okx_websocket.go, exchanges/okx/okx_wrapper.go
Error:
```
panic: runtime error: slice bounds out of range [:13340] with capacity 8192
bufio.(*Reader).Read(0x14000038540, {0x1400059cffc?, 0x4?, 0x0?})
/usr/local/go/src/bufio/bufio.go:250 +0x33c
github.com/gorilla/websocket.(*messageReader).Read(0x1400098bb78, {0x1400059cffc, 0x4, 0x4})
/Users/gbjk/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:1050 +0x208
io.ReadAll({0x12f36c618, 0x1400098bb78})
/usr/local/go/src/io/io.go:701 +0xe4
io/ioutil.ReadAll(...)
/usr/local/go/src/io/ioutil/ioutil.go:27
github.com/gorilla/websocket.(*Conn).ReadMessage(0x3?)
/Users/gbjk/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:1097 +0x54
github.com/thrasher-corp/gocryptotrader/exchanges/stream.(*WebsocketConnection).ReadMessage(0x140006622d0) …
```
=> Okx: Fix panic during shutdown due to race

exchanges/kraken/kraken.go, exchanges/kraken/kraken_types.go, exchanges/kraken/kraken_wrapper.go
This switches to BalancesEx(tended) to get Held assets so we can construct a Total, Held and Free.
Without this fix we get 0 balance from GetFree()
Haven't added tests because no construct for mocks and it's private data. Considering adding mocks a bridge to far for this fix.
=> Kraken: Fix Balances reporting 0 Free

backtester/engine/grpcserver.go, engine/rpcserver.go
The gRPC server uses Basic Authentication to control access, on top of a self generated TLS certificate that is private to the currently running instance. (Additionally, by default the gRPC server listens on a local address only).
However, currently only unary calls are protected with basic authentication.
This PR adds basic authentication to streaming gRPC calls (on top of the TLS certificate used as credentials).
Ensure the gRPC server is enabled.
To verify Basic Authentication works for unary calls, e.g. place a getticker request:
`gctcli --rpcuser <USERNAME> --rpcpassword <PASSWORD> getticker --exchange bybit --asset spot --pair BTC-USDT`
Now change the password or remove the credentials: the call …
=> gRPC: Add stream authentication to gRPC server

exchanges/order/limits.go
Was using max instead of min, and using either should be redundant anyway
=> Order: Fix AmountStepIncrementSize conforms check

exchanges/kraken/kraken_test.go, exchanges/kraken/kraken_wrapper.go
Sets `AssetType` when using `GetActiveOrders` which ensures any methods like DeriveCancel have their asset type set properly. Also adds a default asset type check to CancelOrder.
=> Kraken: Set AssetType in GetActiveOrders, CancelOrder and GetOrderInfo wrappers

exchanges/binance/binance_wrapper.go, exchanges/binanceus/binanceus_wrapper.go, exchanges/bitfinex/bitfinex_wrapper.go, exchanges/bithumb/bithumb_wrapper.go, exchanges/bitstamp/bitstamp_wrapper.go, exchanges/bittrex/bittrex_wrapper.go, exchanges/btcmarkets/btcmarkets_wrapper.go, exchanges/bybit/bybit_wrapper.go, exchanges/coinut/coinut_wrapper.go, exchanges/exmo/exmo_wrapper.go, exchanges/gateio/gateio_wrapper.go, exchanges/huobi/huobi_wrapper.go, exchanges/lbank/lbank_wrapper.go, exchanges/poloniex/poloniex_wrapper.go
The fix is intended to cover all order actions- Buy, Sell, Ask, Bid, Long and Short by using IsLong() instead of order.Buy. Combined the exchanges in stead of creating a PR for each one separately
Fixes #1270 
=> exchanges/order: Improve order side handling in SubmitOrder

.appveyor.yml, .github/workflows/linter.yml, .github/workflows/proto-lint.yml, .github/workflows/tests.yml, .golangci.yml, Dockerfile, Makefile
Updates CI and golangci-lint versions now that Go 1.21 now that it is released. Release notes: https://go.dev/doc/go1.21.
=> CI: Update go and golangci-lint versions

exchanges/bitstamp/bitstamp.go, exchanges/bitstamp/bitstamp_types.go, exchanges/bitstamp/bitstamp_websocket.go
Drive-By: Remove:
`Bitstamp BTC/USDT spot orderbook has zero bid price, filtering.` It's unactionable and happens every snapshot right now
=> Bitstamp: Fix websocket orderbook snapshot blanking LastUpdate

exchanges/stream/buffer/buffer.go, exchanges/stream/buffer/buffer_test.go, exchanges/stream/buffer/buffer_types.go, exchanges/stream/websocket.go
Uses a key instead of multiple map to map lookups. This yields slightly better performance, with no additional allocations. There was also an obstruction due to a potential slow go schedular read on the data handler channel. Opted to ~~drop alert for improved websocket reader update through put.~~  buffer the channel to allow for that hand over to occur.
```
var multiMapHolder = …
```
=> stream/buffer: Reduces map lookups by using key struct

exchanges/orderbook/depth.go, exchanges/orderbook/depth_test.go, exchanges/orderbook/linked_list.go, exchanges/orderbook/linked_list_test.go
* Adds method `GetTranches` which takes in a count so the entire book side doesn't need to be returned. It amalgamates entire book and top book calls. 
* Adds GetPair to access underlying pair. 
=> orderbook: Add GetTranches and GetPair methods to Depth type 

exchanges/bitstamp/bitstamp_websocket.go
This prevents the frequent (5x / hour) disconn/reconns we're seeing with a 10s or even 20s traffic timeout.
I'd like to base the interval on the traffic timeout / 2, but that's non-trivial right now, and 8s isn't an excessive default
=> Bitstamp: Add websocket heartbeat

config/config.go, config/config_test.go, config/config_types.go, config_example.json, engine/engine.go, engine/helpers.go, engine/sync_manager.go, engine/sync_manager_test.go, engine/sync_manager_types.go, main.go
This is a quick & basic QoL improvement which adds the sync manager config to our config file. No longer do you need to add so many params when running the application to change behaviour. You can still use the running params to override your config.
Also, the sync manager is a pretty trustworthy subsystem now, so I've added the ability to modify what logging events to output. You can toggle whether you want to see:
- Switch protocol updates
- Initial sync updates
- Event updates
Errors, default subsystem logs all still show and Verbose is still a thing. 
=> egnine/sync-manager: add config support

exchanges/orderbook/orderbook.go, exchanges/orderbook/orderbook_test.go
Base.GetDepth returns the concrete book of which Base is a copy This is probably useful for immutably monitoring orderbook health and state whereas FetchOrderbook would trigger a refresh.
=> Orderbook: Add GetDepth to Base

exchanges/kraken/kraken_websocket.go
When Kraken has a disconnect or failure that sets SetCanUseAuthenticatedEndpoints(false), it's never re-enabled when the websocket is reconnected That means all subsequent requests would fall back to rest
Can't see a low hanging fruit test for this so just doing a driveby on it.
=> Kraken: Fix WS Auth endpoints not re-enabled

exchanges/bitfinex/bitfinex_websocket.go
=> Bitfinex:  Improve websocket type assertion checks for order processing

backtester/eventhandlers/exchange/exchange.go, backtester/eventhandlers/exchange/exchange_test.go
Compare volume directly as the current implementation passes candle volume in base currency.
- [x ] Bug fix (non-breaking change which fixes an issue)
I updated the relavant test.
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally and on Github Actions/AppVeyor with …
=> backtester: Fix ensureOrderFitsWithinHLV

cmd/gctcli/helpers.go, cmd/gctcli/orderbook.go, engine/rpcserver.go
I have difficulty looking at the CLI way of rendering orderbooks and checking them against exchanges to find faults in our books. So I've added an option to allow it to render like an exchange
From CLI use:
`go run . --it  orderbook getorderbookstream --exchange="binance" --pair="btc-usdt" --asset="spot" --depthlimit=25 --exchangestyle=true`
https://github.com/thrasher-corp/gocryptotrader/assets/9261323/92b2df0c-d926-43e5-9a13-1e5a0c60cd81
Fixes: my eyes
=> gctcli: Add colourful exchange-style rendering to orderbook fetching commands (optional)

exchanges/stream/websocket.go, exchanges/stream/websocket_connection.go, exchanges/stream/websocket_test.go
Subscribers probably care when the WS got disconncted. Tell them and expose a method to test the error for matching
=> websocket: Relay disconnect errors to subscribers

exchanges/bitfinex/bitfinex_test.go, exchanges/bitfinex/bitfinex_types.go, exchanges/bitfinex/bitfinex_websocket.go
Note:
This PR builds upon #1302 and contains a single commit from it.
It should not be merged first or in isolation.
It is, however, the driver and context for the atomic fixes in #1302
=> Bitfinex: Resubscribe orderbook after checksum err

exchanges/orderbook/depth.go
* orderbook fields were exposed beyond a mutex gate this fix closes them in and makes them super safe and snug.
https://trello.com/c/ZOTO4BCP/195-rare-orderbook-data-race
=> orderbook: fix race condition when function scope is in error.

engine/order_manager.go, engine/order_manager_test.go, exchanges/bitfinex/bitfinex_test.go
If the ws sees the order before processSubmittedOrder then it will have assigned it an internal order id already and added it to the store. Don't treat that as an error. Instead just use the newer ws details
=> OrderManager: Fix race condition in submit with ws

exchanges/bitstamp/bitstamp.go, exchanges/bitstamp/bitstamp_live_test.go, exchanges/bitstamp/bitstamp_test.go, exchanges/bitstamp/bitstamp_types.go, testdata/http_mock/bitstamp/bitstamp.json
A fix for issue #1271 
The trading fees have not been updated, always being 0.
Upon review, it showed a change in the trading fee fetching between v1 and v2.
Get trading fees directly from the API
=> Bitstamp: Add new trading fees API endpoint; refine fee calcuations and test coverage

engine/sync_manager.go
* In the context of orderbook synchronisation via websocket this update aims to reduce the fallover to REST with illiquid assets. There could be big stretches of time between updates (🧸 market) and as long as there is an active connection it's probable that the orderbook state has not been compromised. 
=> engine/syncer: Stop orderbook fallover to REST when websocket connection is active

engine/helpers_test.go
BTSE is currently failing startup.
This fix simply prevents that from panicing.
=> Engine: Fix panic when exchange errors

exchanges/okx/okx.go, exchanges/okx/okx_test.go, exchanges/okx/okx_types.go
`TestGetBlockTrades` has been failing with 429.
It smelt like a rate limit issue, which is probably why everyone left it alone until now.
Turns out the url is wrong and 429 is how they respond to that 🤷 
* Fix URL for GetBlockTrades
* Remove UpdateTradablePairs from TestMain so one-shot tests are fast and clean. Tested not required for other one-shots, but can implement an updatePairsOnce pattern if needed
* Expand test coverage in TestGetBlockTrades and TestPublicBlockTrades
* Fix GetPublicTrades marked as an authenticated api
* Rename GetPublicTrades to GetPublicBlockTrades
=> Okx: Fix GetBlockTrades and enhance test coverage

common/convert/convert.go, common/convert/convert_test.go, contrib/spellcheck/exclude_lines.txt, contrib/spellcheck/ignore_words.txt, exchanges/binance/binance_types.go, exchanges/binance/ufutures_types.go, exchanges/bybit/bybit.go, exchanges/bybit/bybit_cfutures.go, exchanges/bybit/bybit_test.go, exchanges/bybit/bybit_types.go, exchanges/bybit/bybit_usdcfutures.go, exchanges/bybit/futures_type.go, exchanges/gateio/gateio_test.go, exchanges/gateio/gateio_types.go, exchanges/gateio/gateio_wrapper.go, exchanges/gemini/gemini_types.go, exchanges/kucoin/kucoin_futures_types.go, exchanges/okcoin/okcoin_types.go, exchanges/okx/okx_types.go, types/number.go, types/number_test.go
This change mostly just renames the type.
convert package and StringToFloat64 represent actions, not types,
and make it misleading to use outside of the API context,
especially when using it for a Float64ToString operation.
This is intended as a first step towards unified type helpers appropriate across GCT in general, not just in exchange APIs.
=> Types: Switch convert.StringToFloat64 to types.Number

dispatch/dispatch.go, dispatch/dispatch_test.go
The existing behaviour was not consistently testable. Publishing to only listening Subscribers has no guarantees at all, and I'm not clear on when we'd be able to use it.
TestMuxPublish would fail intermittently when the jobs queue drained quickly
enough, and we could never guarantee a subscriber would receive a message even when synchronising the pools.
=> dispatch: Fix intermittent TestMuxPublish issue

exchanges/bitfinex/bitfinex_test.go, exchanges/bitfinex/bitfinex_wrapper.go
* Fix UpdateTickes aborting on first failed ticker
On a cross or locked market error we should continue processing the other tickers.
BONK was locked today and as a result other tickers would not be processed
* Fix TestUpdateTickers failing on ICE
Accept 5% failure rate of available pairs not working as tickers.
When Bitfinex [delisted ICE](https://www.bitfinex.com/posts/990) it's still coming back in all pub:conf and pub:info listings:
```
❯ curl -s https://api.bitfinex.com/v2/conf/pub:info:pair | jq -c '.[0][] | select(.[0] | test("(BTC|ICE|ZIL)USD")) '                                                                   ["BTCUSD",[null,null,null,"0.00006","2000.0",null,null,null,0.1,0.05,null,null]]
["ICEUSD",[null,null,null,"4.0","25000.0",null,null,null,null,null,null,null]] …
```
=> Bitfinex: Fix UpdateTickers

exchanges/binance/binance.go, exchanges/binance/binance_test.go
This test was failing with `-tags mock_test_off` because the API imposes a default limit of 500 now, so we'd just get 500 trades and no batching.
If the user doesn't provide a limit, that means we need to assume batching
=> Binance: Fix GetHistoricTrades failing live

dispatch/dispatch.go, dispatch/dispatch_test.go, dispatch/dispatch_types.go
If we have blocking writers, then we need to synchronise them exiting before closing off their channels.
=> Dispatch: Fix race during stop

exchanges/bitfinex/bitfinex.go, exchanges/bitfinex/bitfinex_test.go, exchanges/bitfinex/bitfinex_types.go
* Handle Errors in tickers without panic
* Refactor and improve ticker handling
* Unify Ticker response handling
* Simplify/Humanify errors in parsing ticker responses
* Remove polymorphic response handling for < 10 fields, seems [antiquated according to docs](https://docs.bitfinex.com/reference/rest-public-ticker)
* Add test coverage for tickers
Panic was on using `err.Error()` when no errors were collected:
```
=== NAME  TestUpdateTickers
bitfinex_test.go:508:
Error Trace:    /Users/gbjk/go/src/github.com/gbjk/gocryptotrader/exchanges/bitfinex/bitfinex_test.go:508
Error:          Can not compare type "float64"
Test:           TestUpdateTickers
Messages:       At least 95% of marginfunding tickers should not error
--- FAIL: TestUpdateTickers (15.08s)
panic: runtime error: invalid memory …
```
=> Bitfinex: Fix panic on TestUpdateTickers

common/file/archive/zip_test.go, config/config.go, config/config_types.go, engine/engine.go, exchanges/binance/binance_live_test.go, exchanges/binance/binance_mock_test.go, exchanges/binance/binance_test.go, exchanges/binance/binance_websocket.go, internal/testing/exchange/exchange.go, main.go, testdata/configtest.json
* ~Add a generic WS mock and instance fixture for re-use~
* Add listSubscriptions API support
* Handle Subscribe and Unsubscribe response errors
This is sub-optimal, because it turns out that no matter what we do, we can't verify the subscriptions.
A bad subscription name not only doesn't error, but it's actually returned by listSubscriptions.
All this really achieves is ensuring that the message is actually received and acknowledged before marking a subscription as successful.
Maybe they'll fix the API at some point.
~I'll roll the mock WS handling out to other exchanges in a separate PR.~
=> Binance: Subscribe response handling

engine/helpers.go, engine/rpcserver.go, engine/rpcserver_test.go
A user spotted a regression in Slack that the mux wasn't set for the gRPC proxy handler. This PR adds it back and adds test coverage.
=> engine/gRPC proxy: Fix mux regression and add test coverage

go.mod
Our build toolchain is using 1.21 since #1313
This hides issues on 1.20 from go.mod
Notably uses of implied Generics and slices package seem okay, but would fail for anyone running 1.20 locally
=> Deps: Require go 1.21

exchanges/binance/binance.go, exchanges/binance/binance_test.go, exchanges/binance/binance_types.go, exchanges/binance/binance_wrapper.go, exchanges/btse/btse_test.go
Calls for limits for margin asset were not doing anything if spot is enabled.
This caused intermittent test failures when the sequence meant margin was tested before spot, since the limits wouldn't be loaded.
But it also highlighted that API users calling Update Limits for margin outside the context of a loop on all assets would not get an update. Also intermittently when the loop of UpdateLimits on assets puts margin first
The unfortunate side to this is that we can't avoid having to hit the API twice, because UpdateOrderExecutionLimits can never know if it's being called in isolation or not. Caching could fix that, but it'd be a new paradigm in this context.
=> Binance: Fix UpdateOrderExecutionLimits margin test

common/common.go, common/common_test.go
Retain the .msg field of a go fmt.Errorf .msg field returned by .Error() when wrapping multiple errors.
This fixes a situation where a nested stack of errors would lose formatting information, which is often used to supply identifying context.
e.g.
```
err = fmt.Errorf("%w `%s`: %w", errParsingField, fieldName,
parsingError)
errs = common.AppendError(errs, err)
```
This isn't really an issue with our implementation; Calling Unwrap() on a fmt.Errorf() which returns a wrapErrors will lose that formatting. Our issue was that we were using just Unwrap() to bind together our chain-of-custody.
=> Common: Fix fmt msg lost in AppendError().Error()

exchanges/account/account.go, exchanges/binance/binance_wrapper.go
This was brought initially to my attention by vancake on Slack. However, I started getting broken order results when I actually wanted to do something with my account details.
`GetAccountInfo` only collects a single currency before calling `Break` in the underlying `account` package, however `UpdateAccountInfo` initially does not, leading to an inconsistent output when using the `FetchAccountInfo` endpoint for wrappers.
I've slightly changed it so it doesn't call `break`. I would call the section of code quite strange, and I think I could do more refactorings there, but I don't think I should do that yet and just prioritise the bug. I will point to this if a review comment is asking for too much 😄 
- Run GCT
- Call `FetchAccountInfo`
- eg via GCTCLI: `go run . getaccountinfo binance spot` …
=> account: fix balance issue returning only one balance

exchanges/stream/websocket.go, exchanges/stream/websocket_test.go
Previously we'd set the websocket to disconnected when *either* of the
Conn/AuthConn got a disconnect message.
This meant that:
* The other connection was still functioning
* A user would be free to call Connect()
* wsReadData() may not have exited
Any call to Connect would be acceptable, and we'd probably get a panic
from the underlying shared/re-used gorilla websocket:
`panic: runtime error: slice bounds out of range [:13501] with capacity 8192`
when a new wsReadData goro is started and the old tries to ReadMessage
as well, overallocating the buffer.
This wouldn't normally occur because trafficMonitor would see traffic
(on either connection) and then set the websocket to being connected
again.
The solution is to treat a Disconnect on either websocket as a call to
Shutdown the whole …
=> Websocket: Prevent panic on Disconnect/Connect

exchanges/coinut/coinut_types.go, exchanges/coinut/coinut_websocket.go
WsConnect is calling GetInstruments, and when that fails, erroring out and not subscribing to anything.
The response to get instruments is an object {}, which skips the IncomingWithData check in wsReadData for arrays []. The check in wsHandleData depended on client_ord_id, but I figure so long as there's a nonce which matches, we can palm it off.
This results simutaneously in having to move the login handler back to it's waiting nonce-parser, and also simplifying/deduping it.
=> Coinut: Fix websocket not parsing instruments, improve nonce matching and error handling

common/common.go, common/common_test.go, exchanges/binance/binance_test.go, exchanges/kraken/kraken_test.go, exchanges/kraken/kraken_websocket.go, internal/testing/exchange/exchange.go
We were using the "cancel many" facility of the Kraken api. However since that doesn't actually report errors individually, it seems saner to just multiplex over it.
We were going to get N+ responses anyway. Might as well send N+ requests
One thing I'm unhappy about is the change of Key/Secret for this to work.
I really don't like that there's special values for the auth values which get silently ignored, such as Test, Mock, Key, Secret, etc.
So I've ended up using something adhoc, and putting a require in the test to ensure it's obvious if the auth-conn isn't connected.
=> Kraken: Fix wsCancelOrders not erroring with order id

go.mod
go build will give following error.
```
go: download go1.22 for darwin/arm64: toolchain not available
```
Refer to this solution
https://github.com/golang/go/issues/65568#issuecomment-1954876836
=> go: Fix darwin/arm64: toolchain not available version directive

cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go, currency/manager.go, currency/manager_test.go, exchanges/kraken/kraken_wrapper.go
APIs like this should not require the pair to be enabled.
Fixes intermittent test failure on cmd/exchange_wrapper_standards:
```
exchange_wrapper_standards_test.go:227: Kraken Func 'GetLatestFundingRates' Error: 'pair not enabled FF-TEST-DELIM-solusd_240628'. Inputs: [context.Background {futures FF-TEST-DELIM-solusd_240628 true}].
```
=> Kraken: Fix GetLatestFundingRates requiring pair enabled

exchanges/btcmarkets/btcmarkets.go
BTC markets woke up one day and banned the trailing slash. This hopefully appeases the BTCM gods. 
=> btcmarkets: remove trailing slash on markets/ticker strings and update endpoint pathways

exchanges/bitstamp/bitstamp_test.go, exchanges/bitstamp/bitstamp_types.go, exchanges/bitstamp/bitstamp_wrapper.go, testdata/http_mock/bitstamp/bitstamp.json
Issues picked up during PR#1423 but were considered out of scope. In addition, the main error checks changed from assert to require.
=> Bitstamp: Add missing API fields

exchanges/binance/binance_live_test.go, exchanges/binance/binance_mock_test.go, exchanges/kraken/kraken_test.go, exchanges/kucoin/kucoin_test.go, internal/testing/exchange/exchange.go, internal/testing/exchange/exchange_test.go, internal/testing/exchange/testdata/http.json, internal/testing/utils/path.go, internal/testing/utils/path_test.go
Minimal test coverage for internal/testing/exchange.
It doesn't cover all statements or methods, but at least gets us started in the right direction.
=> Test: Internal exchange coverage

backtester/engine/setup.go, engine/exchange_manager.go, engine/exchange_manager_test.go, exchanges/binance/binance.go, exchanges/binance/binance_test.go, exchanges/binance/binance_types.go, exchanges/mock/recording.go, exchanges/sharedtestvalues/sharedtestvalues.go
David on Slack has been informing us of issues with the Backtester. This fix uses up-to-date credential checking functions instead of returning an error. 
Before I could fix that I found [Binance changed the json for SPOT/MARGIN execution limits](https://binance-docs.github.io/apidocs/spot/en/#change-log) to use [[][]permissionSets](https://binance-docs.github.io/apidocs/spot/en/#exchange-information)
Upon fixing that I went to update our json mock data, and that showed that #1444 introduced a compatibility change with recording to the new path
I also came across duplicate errors _right next to eachother_ and have addressed that
- Modify `/backtester/config/strategyexamples/dca-candles-live.strat`
- Change exchange to Binance and currency to BTC-USDT (or whatever)
- Add your credentials
- …
=> bugfixes: Backtester credentials, Binance ExecutionLimits, Mock recording

backtester/eventhandlers/exchange/slippage/slippage_test.go, currency/manager.go, currency/manager_test.go, currency/pair.go, exchanges/bitfinex/bitfinex_test.go, exchanges/bitflyer/bitflyer_test.go, exchanges/bitstamp/bitstamp_test.go, exchanges/exchange.go, exchanges/exchange_test.go, exchanges/gateio/gateio.go, exchanges/kraken/kraken_test.go, exchanges/kucoin/kucoin_test.go, exchanges/okx/okx.go, exchanges/okx/okx_test.go, exchanges/okx/okx_websocket.go, exchanges/okx/okx_wrapper.go, exchanges/sharedtestvalues/sharedtestvalues.go, internal/testing/exchange/exchange.go, testdata/configtest.json
* Fix a instance pair manager race intermittently causing Bitfinex and Kraken to fail
* Fix PairsManager.Load breaking matcher
* Fix UpdatePairsOnce not working across instances
* Move and Simplify FixtureToDataHandler
* Rename PairStore.copy to PairStore.clone and replace various builtin `copy` with slices.Clone
* Add Fullstore.clone and PairFormat.clone
=> Tests: Various race fixes and move TestFixtureToDataHandler

backtester/engine/grpcserver.go, cmd/gctcli/commands.go, contrib/spellcheck/ignore_words.txt, currency/code.go, currency/currencies.go, currency/pairs.go, exchanges/asset/asset.go
=> Linter: Spelling fixes

exchanges/deribit/deribit.go, exchanges/deribit/deribit_test.go, exchanges/deribit/deribit_websocket.go, exchanges/deribit/deribit_wrapper.go, exchanges/kline/kline.go, exchanges/orderbook/orderbook.go
These are the kinds of bugs that can only pop up after proper use, it was still an excellent PR Sam 🕊️ 
This PR does the following:
- Speeds up `UpdateTradablePairs` utilising concurrency since its so slow. Reduces `go test -race -count=0` from `28s` to `20s`
- Implement `GetCurrencyTradeURL`
- Update function `IsPerpetualFuture`
- Update `optionPairToString` and add test coverage
- Simplifies some tests
- Rename `guessAssetTypeFromInstrument` to `getAssetFromPair` as its not guessing
- Adds `getAssetPairByInstrument` to help parse WS pair data after getting some errors
- Handles currency processing via the `any` subscriptions (eg trades) using `getAssetPairByInstrument`
- This moves the parsing of currency data to inside loops, because `any` can have multiple currencies in the slice/ the …
=> Deribit: bug fixes, test fixes and implement GetCurrencyTradeURL

common/common.go, exchanges/asset/asset.go, exchanges/btse/btse.go, exchanges/btse/btse_test.go, exchanges/btse/btse_types.go, exchanges/btse/btse_wrapper.go, exchanges/order/limits.go
* Replace `seedOrderSizeLimits` with standard `UpdateOrderExecutionLimits`
* Remove checks for limits from SubmitOrder; No other exchange implements them at the exchange level
* Fix handling of K_ prefix symbols
* Overload `GetRawMarketSummary` with `GetMarketSummary` to filter pairs
* Fix MarketPair.Futures field
* Fixes for tests prone to racing on currency updates
=> BTSE: Various fixes

backtester/funding/trackingcurrencies/trackingcurrencies_test.go, currency/pairs.go, currency/pairs_test.go, exchanges/sharedtestvalues/sharedtestvalues.go, exchanges/subscription/subscription.go
Alters the Add method on currency.Pairs to accept an arbitrary amount of Pair objects as input, to enable mass-scale safe adding of pairs, in a way that hopefully doesn't break code that currently uses this function.
=> currency: Make pairs.Add variadic

log/custom_log_hooks.go, log/custom_log_hooks_test.go, log/loggers.go
Allows the logger system to be completely bypassed by a hook while maintaining existing features. This allows clients to define their own independent logger implementations for their specific purpose and/or infrastructure. 
=> log: allow external definition of log handling 

exchanges/subscription/subscription.go, exchanges/subscription/subscription_test.go
Fixes Clone() affecting the original and not the clone for Pairs and Params.
That actually meant it would pass tests, and kinda work, but not in the way expected, and definitely not thread safe on the original parent
=> Subscriptions: Fix subscription.Clone Params and Pairs

exchanges/okx/okx_test.go
Last block trade has fallen outside 7 days many times now. Switching to within 90 days, which appears safe.
=> Okx: Fix TestGetBlockTrade transient fail

exchanges/gateio/gateio_wrapper.go, exchanges/order/order_test.go, exchanges/order/orders.go
I had both values populated for Amount and QuoteAmount and when it detected base amount it kept base amount. So this reduces a fat finger chance.  😆 
=> orders/gateio: Add `GetTradeAmount` method to order.Submit type

exchanges/subscription/list.go, exchanges/subscription/list_test.go, exchanges/subscription/subscription_test.go
This PR just adds Subscription List cloning.
It's broken out from #1579 so that other PRs can move along without such a big dependency chain.
=> Subscriptions: Add List.Clone

exchanges/kraken/kraken.go, exchanges/kraken/kraken_futures.go, exchanges/kraken/kraken_test.go, exchanges/kraken/kraken_types.go, exchanges/kraken/kraken_wrapper.go
Simplifies REST spot error and result handling with some minor enhancements along the way. Also fixes two issues:
1) ReferenceID for withdrawal requests
2) For creating new deposit addresses, `new` had to be in the format of "true" or "false".
Fixes:
=> Kraken: Simplify REST error and result handling

engine/rpcserver_test.go, exchanges/gateio/gateio_types.go, exchanges/gateio/gateio_websocket.go, exchanges/gateio/gateio_ws_futures.go, exchanges/gateio/gateio_ws_option.go, exchanges/orderbook/depth.go, exchanges/orderbook/depth_test.go, exchanges/orderbook/orderbook.go, exchanges/orderbook/orderbook_types.go, exchanges/orderbook/tranches_test.go, exchanges/stream/buffer/buffer.go, exchanges/stream/buffer/buffer_test.go
* Adds fields `UpdatePushedAt` & `InsertedAt` for the distinction as to when an exchange pushed the payload to a client and when it was inserted into memory. Allowing a more correct analysis of latency to be achieved. 
* Populate base case for Gateio for websocket orderbooks
* Did not include a zero check yet, so that we do not need a full widespread conversion across exchanges. But all websocket data types should include this field if provided in the future. 
also consider improving test coverage whilst working on a certain …
=> orderbook/gateio: add field `UpdatePushedAt` and `InsertedAt` for specific websocket updates

common/common.go, exchanges/binance/binance_test.go, exchanges/binance/binance_websocket.go, exchanges/bitfinex/bitfinex_test.go, exchanges/bitfinex/bitfinex_types.go, exchanges/bitfinex/bitfinex_websocket.go, exchanges/kraken/kraken.go, exchanges/kraken/kraken_futures.go, exchanges/kraken/kraken_test.go, exchanges/kraken/kraken_types.go, exchanges/kraken/kraken_websocket.go
We see daily failures on OpenInterest for Kraken.
This fix assumes that the issue might be related to volume of ETHUSD open interest, and switches the single pair test to XBTUSD instead
Also isolates the test from others, since we're changing stored pairs and we might be colliding on the global k
If we keep getting the issue after this, then we remove the NotEmpty errors I guess.
=> Kraken: Fix TestGetOpenInterest

engine/engine.go, engine/engine_test.go, engine/engine_types.go, main.go
Adds an overridable, dry run protected by default `-exchanges` command line flag to engine which is useful for troubleshooting or in cases where you're only interested in enabling a specific set of exchanges, without requiring you to edit your config file.
=> engine: Add overridable exchanges command line flag

exchanges/request/request.go, exchanges/request/request_test.go, exchanges/stream/websocket_connection.go, exchanges/stream/websocket_test.go
* ~~Adds verbosity for debugging for outbound websocket requests and also the responses.~~ Adds verbosity for responses when its context verbose. 
* Exposes IsVerbose func from request package so that verbosity can be set via context and only that specific request gets hit and returns the outbound and inbound info without the need for a global state.
* Adds connection URL for multi connection differentiation.
This was pulled from #1603 as that PR is not a huge priority over this change and the sweeping changes of "multi-connection ws handling"
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …
=> stream: Add verbosity to outbound requests that also returns responses

cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go, engine/engine_test.go, exchanges/coinbasepro/coinbasepro_test.go
Disables deprecated API tests until #1480 is merged
=> CoinbasePro: Skip specific tests due to API deprecation

exchanges/binance/binance_test.go
Fixes:
```
binance_test.go:2608: expected type order.Detail, found *orderbook.Depth
```
=> Binance: Fix occassional race failure on TestWsOrderExecutionReport

exchanges/huobi/huobi.go, exchanges/huobi/huobi_futures.go, exchanges/huobi/huobi_test.go, exchanges/huobi/huobi_types.go, exchanges/huobi/huobi_wrapper.go
* Collect and Return all errors from UpdateTickers
* Fix [intermittent failure of TestUpdateTickers](https://github.com/thrasher-corp/gocryptotrader/actions/runs/10917737674/job/30301656625?pr=1652) and implicitly a failure of tickers in runtime too
```
--- FAIL: TestUpdateTickers (2.29s)
huobi_test.go:2879: 
Error Trace:	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/huobi/huobi_test.go:2879
Error:      	Received unexpected error:
no ticker found huobi ETH-241227 futures
Test:       	TestUpdateTickers
FAIL
```
* Make contract type errors consistent
* Convert and Send lowercase contract type regardless of user input ( Option to reject uppercase. I'm in favour of that, personally )
=> Huobi: Fix intermittent UpdateTickers failure on expiry

exchanges/kraken/kraken_test.go
Fixes the TestGetFuturesOrderbook error and consolidates test pairs
=> Kraken: Fix TestGetFuturesOrderbook and consolidate test pairs

exchanges/huobi/huobi_cfutures.go, exchanges/huobi/huobi_futures.go, exchanges/huobi/huobi_test.go
Removes Huobi suspended endpoints as these have been moved into the "Downline interface" section of the new API docs. Unfortunately their new endpoints are reporting "service errors" which they're working on a fix to implement.
=> Huobi: Remove suspended API endpoints

exchanges/exchange.go, exchanges/kucoin/kucoin_websocket.go, exchanges/subscription/list.go, exchanges/subscription/list_test.go
=> Subscriptions: Add List.Enabled, List.Public and List.Private

exchanges/kucoin/kucoin_test.go, exchanges/kucoin/kucoin_websocket.go
This PR standardises a way for exchanges to implement subscriptionNames and a channelName function.
It's the most likely standardised way forwards for channelName func.
Providing it immediately so that @cranktakular can make use of it.
=> Kucoin: Abstract a subscriptionNames for assets solution

exchanges/subscription/template.go, exchanges/subscription/template_test.go
The subscription pairs do not need to be validated as enabled or available. The check was just belt-and-braces and didn't have a specific use-case in mind.
Coinbase has a use-case for wanting to subscribe to BTC-USD when it's not enabled.
Moreover, it shouldn't be our job to check this. You want a sub expanded with these pairs? Fine. Done. If it doesn't work, you can work out why
=> Subscriptions: Relax subscription validation for non-existent pairs

internal/testing/utils/path_test.go
This fixes looking for LICENSE files in the vendor directory
=> Tests: Fix fail on vendored modules

exchanges/huobi/huobi_test.go, exchanges/huobi/huobi_wrapper.go
We were relying on autoUpdatePairs to fetch contract types before we need them. If the user disables it in config, we'll lazily fetch just the relevant Futures.
=> Huobi: Fix invalid contract type error when autoUpdatePairs is false

exchanges/huobi/huobi_test.go, exchanges/huobi/huobi_types.go, exchanges/huobi/huobi_wrapper.go
Fixes:
`[ERROR] | LOG | 08/11/2024 19:39:52 | Huobi failed to get cryptocurrency deposit address for BTC [chain hrc20btc]. Err: unable to match deposit address currency or chain`
This seems sufficient, though I'm unhappy with the way that `GetAvailableTransferChains` might return a withdraw only chain.
Reality right now is that Huobi has no "deposit not allowed" chains which are also "withdraw allowed", so this isn't currently an issue.
=> Huobi: Fix GetAvailableTransferChains returning unavailable chains

exchanges/binance/binance.go, exchanges/binance/binance_cfutures.go, exchanges/binance/binance_test.go, exchanges/binance/binance_types.go, exchanges/binance/binance_ufutures.go, exchanges/binance/binance_wrapper.go, exchanges/binance/ratelimit.go, exchanges/binance/ratelimit_test.go, exchanges/binance/ufutures_types.go
I've been getting banned a lot from Binance and these rate limits are why. This PR is non-exhaustive and just looks to fix up the areas where I'm being banned. For more updates, please see #1546 
~I also noticed `GetFundingRateInfo` now just returns `[]` so I removed its usage in the wrapper~
=> Binance: update orderbook, ticker rate limits.

exchanges/asset/asset.go, exchanges/asset/asset_test.go, exchanges/order/order_test.go
Fixes Linear assets missing from list of strings for asset conversion.
Drive-Bys a couple of other minor fixes from another branch that shouldn't be contentious.
=> Assets: Fix LinearContracts support

exchanges/order/order_test.go, exchanges/order/orders.go
=> order: Add `Side` type MarshalJSON method

common/math/math.go, common/math/math_test.go, engine/datahistory_manager.go, exchanges/orderbook/calculator.go, exchanges/orderbook/tranches.go
* Needed absolute value as it was returning negative values. 
* Adds decimal package calc
* Adds vars so that less decimal structs are allocated
* Rename `CalculatePercentageGainOrLoss` -> `PercentageChange`
=> common/math: Add math.Abs to PercentageDifference calculation

types/time.go, types/time_test.go
Did not error when using incorrect type. So force check, more performant using time.Time type for that use case so not going to handle potential edge case.
Cherry-picked from #1670 
=> types/time: filter string that cannot be a unix timestamp

exchanges/bithumb/bithumb_websocket.go, exchanges/bithumb/bithumb_websocket_test.go, exchanges/bithumb/bithumb_wrapper.go, exchanges/subscription/subscription.go
* Add subscription configuration
- [sprig](github.com/Masterminds/sprig/v3)   ( Also included in 4 other template PRs )
=> Bithumb: Add subscription configuration

exchanges/gemini/gemini_test.go, exchanges/gemini/gemini_types.go, exchanges/gemini/gemini_websocket.go, exchanges/gemini/gemini_wrapper.go, exchanges/subscription/subscription.go, testdata/configtest.json
* Add Subscription configuration
* Upgrade test configuration
=> Gemini: Add subscription configuration

exchanges/bitmex/bitmex_test.go, exchanges/bitmex/bitmex_websocket.go, exchanges/gateio/gateio_test.go, exchanges/subscription/fixtures_test.go, exchanges/subscription/list.go, exchanges/subscription/template.go, exchanges/subscription/template_test.go, testdata/configtest.json
Subscriptions:
* Fix unsupported WS assets included
Bitmex:
* Assertify and fix tests
* Add index asset to test config
Fixes #1692
=> Subscriptions: Respect DisableAssetWebsocketSupport for assets

exchanges/coinbasepro/coinbasepro_test.go, exchanges/gateio/gateio.go, exchanges/gateio/gateio_test.go, exchanges/gateio/gateio_wrapper.go, exchanges/okx/okx_test.go
GateIO made a change in which delivery futures returns no results for BTC being the settlement currency. Looking at their website, they only support USDT ATM, despite it being a param in all their delivery API endpoints. This PR restricts it to USDT, but maintains settlement currency as a param in case they bring out inverse delivery futures which most exchanges support.
Also disables Coinbase tests completely up until #1480 is ready since they have disabled more endpoints since last time
Fixes OKX race as a drive-by I saw when I pushed this PR 🐎
=> exchanges: Fix GateIO/Coinbase test failures and OKX race

exchanges/bybit/bybit.go, exchanges/bybit/bybit_live_test.go, exchanges/bybit/bybit_test.go, exchanges/bybit/bybit_types.go, exchanges/bybit/bybit_wrapper.go
* Extra outbound call when updating accounts after first
=> bybit: Add protected subtype for account checking to reduce outbound requests

.github/workflows/stale.yml
Adds a GHA for stale issues/PRs. By default, the following settings have been defined however these are set via GH envs which make it easy to adjust these without having to commit changes. The settings will also be displayed each time the job is run however they're listed below:
Runs every Monday-Friday during AEST/AEDT hours at midnight UTC which is 10AM-11AM AEST/AEDT.
Days before an issue or PR goes stale: 30 days.
Days before an issue is closed after going stale: 7 days.
PRs will never be closed automatically.
Will automatically set the tag of the PRs/issues to `stale`.
**Tag exemptions:**
Issues: in progress,todo
PRs: nomerge requires dependency,blocked
=> CI/GHA: Add stale activity action for issues and PRs

exchanges/interfaces.go, exchanges/subscription/interface_test.go, exchanges/subscription/list.go, exchanges/subscription/template.go
Adds GetPairFormat to IBotExchange
Thusfar ExpandTemplates had only been called internally. All methods consumers might want to get, in this case GetPairFormat, need to be in the interface we're passing out, otherwise users can't call them (or things that use them, like ExpandTemplates)
=> Subscriptions: Fix IBotExchange not implementing sub.IExchange

.golangci.yml, currency/pairs.go, engine/rpcserver.go, exchanges/btse/btse_wrapper.go, exchanges/gateio/gateio.go, exchanges/gateio/gateio_test.go, exchanges/gateio/gateio_types.go, exchanges/gateio/gateio_websocket.go, exchanges/gateio/gateio_websocket_futures.go, exchanges/gateio/gateio_websocket_option.go, exchanges/gateio/gateio_wrapper.go, exchanges/subscription/template.go
* 🐛 🚨 Fix GetFuturesContractDetails for Deliveries
Was returning the product of all the contracts, so 1444 instead of 38 contracts.
Doesn't touch anything else around this; Futures asset split coming separately
* Rename Get*PersonalTradingHistory to GetMy*TradingHistory
* Remove duplicate DeliveryTradingHistory
* Rename GetMyPersonalTradingHistory to GetMyFuturesTradingHistory
* Rename GateIOGetPersonalTradingHistory to GetMySpotTradingHistory
* Rename GetSingleContract and GetSingleDeliveryContracts
* Fix GetOpenInterest returning asset.ErrNotEnabled
* Disables shadow checks for err  ( Cherry-pick from #1754 )
=> GateIO: Fix GetFuturesContractDetails for Deliveries and minor other fixes

exchanges/binance/binance_types.go, exchanges/binance/binance_websocket.go, exchanges/binance/binance_wrapper.go
Currently, the Binance side is marked as unknown. The raw data includes the isBuyerMaker: bool flag, which indicates the initiating side. Based on that, add a side.
=> Binance: Add order side

.codespellrc, .github/workflows/spell-checker.yml, backtester/engine/grpcserver.go, contrib/spellcheck/exclude_lines.txt, contrib/spellcheck/ignore_words.txt, exchanges/gateio/gateio_types.go, exchanges/request/request.go
* Moves currency checks to be a regex, avoiding hardcoding the digits in the ignore lines, and having to keep adding them
* DriveBy mini-refactor in grpcserver whilst sidestepping `eto` complaint like Neo in that scene. You know, right.
* Grabs the latest PR suggestion for the fix to gateio's risk type
* > Fixes the codespell failure about the word belows 
* Removes the github action config
* Because we have .codespellrc already and consistency is better between dev-env and CI
* Because the stupid github action enforces it's own opinion of what valid options should be, and doesn't support ignore-regex
=> Codespell: Fix failures with 2.4.0

cmd/config/config.go, config/config.go, config/config_encryption.go, config/config_encryption_test.go, config/versions/versions.go, config/versions/versions_test.go
* Config: Fix config version downgrade
* Config: Rename EncryptConfigFile to EncryptConfigData
* Config: Rename DecryptConfigFile to DecryptConfigData
Fixes #1769 and issue raised on #1735
=> Config: Fix config version downgrade

exchanges/btse/btse_test.go, exchanges/btse/btse_wrapper.go
TRUMP strikes again with a special edge case for BTSE's MarketPair Pair method handling as no other symbols experience this issue. 
Fixes #1802
=> exchanges/btse: Handle TRUMPSOL in MarketPair.Pair and add test coverage

exchanges/bybit/bybit_test.go, exchanges/bybit/bybit_websocket.go
Enhance Bybit private channel subscription with categorised topics
ref: https://bybit-exchange.github.io/docs/v5/websocket/private/position
```
go test ./exchanges/bybit -v -run TestGenerateSubscriptions
```
=> bybit: support categorised channel

cmd/config/config.go, config/config.go, config/versions/versions.go, config/versions/versions_test.go
This constrains the versions to uint16 and improves error handling. LatestVersion becomes literally that.
Fixes handling for negative or overflowing versions in config
=> Config: Tighten config version handling as uint16

exchanges/binance/binance_wrapper.go, exchanges/binanceus/binanceus_wrapper.go, exchanges/bitfinex/bitfinex_websocket.go, exchanges/bitstamp/bitstamp_websocket.go, exchanges/btcmarkets/btcmarkets_websocket.go, exchanges/btse/btse_websocket.go, exchanges/bybit/bybit_websocket.go, exchanges/bybit/bybit_wrapper.go, exchanges/coinbasepro/coinbasepro_websocket.go, exchanges/coinut/coinut_websocket.go, exchanges/deribit/deribit_websocket.go, exchanges/exchange.go, exchanges/gemini/gemini_websocket.go, exchanges/hitbtc/hitbtc_websocket.go, exchanges/huobi/huobi_websocket.go, exchanges/kraken/kraken_websocket.go, exchanges/kucoin/kucoin_wrapper.go, exchanges/okx/okx_websocket.go, exchanges/okx/okx_wrapper.go, exchanges/stream/websocket.go, exchanges/trade/trade.go, exchanges/trade/trade_test.go, exchanges/trade/trade_types.go
remove `exchangeName` for `AddTradesToBuffer`, `exchangeName` is redundant since `data[i].Exchange` already holds the exchange info.
=> trade: remove exchangeName for AddTradesToBuffer

exchanges/margin/margin.go, exchanges/margin/margin_test.go, exchanges/order/order_test.go
There is a bug from a lack of `MarshalJSON` implementation. When unmarshalling and marshalling an order.Submit for example, it will fail from being unable to parse a string into a `margin.Type`
=> exchanges/margin: Fix marshalling issue

exchanges/huobi/huobi_test.go, exchanges/huobi/huobi_websocket.go, exchanges/huobi/testdata/wsAllTrades.json, testdata/configtest.json
Like Kraken, the trades are not being sent down to the websocket DataHandler because the IsTradeFeedEnabled is not set.
=> Huobi: Fix sending trades to the websocket DataHandler

exchanges/okx/okx_wrapper.go
The `WsResponseMultiplexer` structure should be initialized in `setDefaults` method.
=> okx: move WsResponseMultiplexer to setDefaults

common/file/file_test.go, exchanges/kline/kline_test.go
TempDir returns a temporary directory for the test to use.The directory is automatically removed when the test and
all its subtests complete. More info  https://pkg.go.dev/testing#B.TempDir
=> refactor: use t.TempDir() instead of os.MkdirTemp

exchanges/okx/okx_test.go, exchanges/okx/okx_websocket.go, exchanges/okx/testdata/wsAllTrades.json, testdata/configtest.json
Trades are not being sent down to the websocket DataHandler because the IsTradeFeedEnabled is not set.
Additional changes:
- Send the trades down the DataHandler individually
- Change the timestamp to .UTC()
=> Okx: Fix sending trades to the websocket DataHandler

backtester/engine/setup.go, config/config.go, config/config_types.go, config/versions/v5.go, config/versions/v5_test.go, config/versions/versions.go, engine/engine.go, engine/order_manager.go, engine/order_manager_test.go, engine/order_manager_types.go
* Replaces `*bool` with a boolean in `orderManager.Enabled` and `orderManager.RespectOrderHistoryLimits`
* Replaces negative `FuturesTrackingSeekDuration` with positive
* Removes runtime default FuturesTrackingSeekDuration and replaces with an error
=> Config: OrderManager upgrade

.github/workflows/tests.yml, CONTRIBUTORS, Makefile, README.md, cmd/documentation/documentation.go, cmd/documentation/root_templates/root_readme.tmpl, encoding/json/common.go, encoding/json/json.go, encoding/json/sonic.go, exchanges/okx/okx.go, exchanges/okx/okx_test.go, exchanges/okx/okx_types.go, exchanges/okx/okx_wrapper.go
* Fix GetPublicUnderlying with sonic 1.12.9 on arm64
* Extend tests for UseAsIs non-defaults
* Improve SendHTTPRequest documentation
* Fix AccountConfiguration slice return
* Move withdrawData type to types
* Unify timestamp response types
* Remove redundant useAsIs on slices
* Change ResetRFQMMPStatus to return a types.Time
* Sonic: Add sonic_on build tag
Caveat: Right now to test this I'm doing:
```
GOFLAGS="-tags=sonic_on" go test -count=1 ./exchanges/okx/...
```
Without that, we're not going to see the sonic fix actually fixing arm64, but we do see that it still works.
Using `**result` for slices with useAsItIs causes sonic to fail on arm64.
This might be addressed upstream, but it's also not clear what the unmarshal behaviour for an untyped reference to a typed reference should be in …
=> Okx: Various fixes including sonic

exchanges/btse/btse_test.go, exchanges/btse/btse_types.go, exchanges/btse/btse_websocket.go, exchanges/btse/testdata/wsAllTrades.json, testdata/configtest.json
Currently, the BTSE trades are not streaming via the websocket.
The following changes were made:
- Update the raw trade data to match the API docs
- Fix extracting the pair from the topic
- Update the test
- Amend the configtest to enable the trade feed
=> BTSE: Fix sending trades to the websocket DataHandler

exchanges/btcmarkets/btcmarkets_test.go, exchanges/btcmarkets/btcmarkets_types.go, exchanges/btcmarkets/btcmarkets_websocket.go, exchanges/btcmarkets/testdata/wsAllTrades.json, testdata/configtest.json
Like with other exchanges, websocket trades are not sent down to the DataHandler.
=> BTC Markets: Fix sending trades to the websocket DataHandler

cmd/portfolio/portfolio.go, common/common.go, common/common_test.go, config/config_types.go, config/versions/v5.go, config/versions/v6.go, config/versions/v6/types.go, config/versions/v6_test.go, config_example.json, engine/engine.go, engine/helpers.go, engine/portfolio_manager.go, portfolio/portfolio.go, portfolio/portfolio_test.go, portfolio/portfolio_types.go, testdata/configtest.json
CryptoID API now requires an API key + rate limiter for balance requests which was causing a test failure. This PR adds support for that, makes the portfolio concurrency safe as well as assertifying all tests + adding additional test coverage.
I think another pass will be required to change some things around like having all providers conforming to an interface, listing which coins they support etc but just wanted to get tests working again.
=> portfolio: Fix CryptoID balance issue and assertify tests

exchanges/bitfinex/bitfinex.go, exchanges/bitfinex/bitfinex_test.go, exchanges/bitfinex/bitfinex_types.go
Fix intermittent TestGenerateSubscriptions and ticker FFRAmountAvailable failures since FRRAmountAvailable is sometimes zero, also fixes the typo of FFR to FRR since FRR means Flash Return Rate.
Fixes https://github.com/thrasher-corp/gocryptotrader/issues/1853
=> Bitfinex: Fix intermittent TestGenerateSubscriptions and ticker FRRAmountAvailable failures

exchanges/okx/okx_test.go
The leader trader may not have any positions open so this relaxes the test
=> OKX: Relax TestGetLeadTraderCurrentLeadPositions

exchanges/gateio/gateio_test.go
#1786 regressed the tests in #1603 where statusOpen replaced "open"
This just fixes that
=> GateIO: Fix regression of statusOpen

exchanges/btcmarkets/btcmarkets_websocket.go, exchanges/coinbasepro/coinbasepro_websocket.go, exchanges/credentials.go, exchanges/credentials_test.go, gctscript/wrappers/gct/gctwrapper_test.go
Swapped out empty credential returns with more specific errors to make things clearer and avoid weird behavior. Added safeguards to handle nil credentials in WebSocket data processing. This gives us better error handling and more reliable fallback options when managing credentials.
Old PR: https://github.com/thrasher-corp/gocryptotrader/pull/1683
It was unclear what my goal was and what I was trying to do. Also, I synced upstream and made a new branch to start with a clean slate. I didn't want to fight with git at 5:30 in the morning with git force push and mess up (sorry) 
```diff
creds := ctxCredStore.Get()
if err := b.CheckCredentials(creds, true); err != nil {
-                       return creds, fmt.Errorf("context credentials issue: %w", err)
+                       return nil, …
```
=> exchanges/credentials: Improve handling and error reporting

config/versions/register.go, config/versions/v8/v8.go, config/versions/v8/v8_test.go, exchanges/bitmex/bitmex_test.go, exchanges/bitmex/bitmex_websocket.go, exchanges/bitmex/bitmex_wrapper.go
* Fix configured WS url ignored
* Fix user config for [deprecated www api sub-domain](https://blog.bitmex.com/api_announcement/change-of-websocket-endpoint/)
* Switch to `realtime` endpoint instead of [now deprecated realtimemd](https://blog.bitmex.com/api_announcement/api-update-remove-support-realtimemd/) and fix user config
Fixes #1894 
Whilst testing this manually I noticed authenticated WS is not working, and I noticed this error during cred validation:
`Bitmex unsuccessful HTTP status code: 400 raw response: {"error":{"message":"Body should not be included in a GET request.","name":"HTTPError"}}, authenticated request failed`
But I'll look into that separately.
=> Bitmex: Fix deprecated API endpoints and add config migration support

exchanges/deribit/deribit.go, exchanges/deribit/deribit_test.go, exchanges/deribit/deribit_types.go, exchanges/deribit/deribit_ws_endpoints.go
Removes the deprecated public and private portfolio margin endpoints as they are no longer supported
=> Deribit: Remove deprecated public and private portfolio margin endpoints

exchanges/exchange.go, exchanges/exchange_test.go
We're directly accessing the currency pairs map in `ValidateKline` which causes a 🏎️ so this uses the CurrencyPairs helpers which utilise a mutex, also assertifies the related tests
Fixes #1918
=> exchanges: Fix race, improve error handling in ValidateKline and assertify related tests

config/config.go, config/config_encryption.go, config/config_encryption_test.go
From jules:
Here's how I resolved a race condition in the encryption prompt tests:
I've refactored `promptForConfigEncryption` to accept an `io.Reader`. This allows tests to use `strings.NewReader` instead of relying on the global `os.Stdin`. This change isolates the input source for `TestPromptForConfigEncryption`, preventing concurrent access conflicts with `TestPromptForConfigKey` which uses `withInteractiveResponse` to manipulate `os.Stdin`.
The original issue manifested as a data race detected by `go test -race` between these two test functions due to their parallel execution (`t.Parallel()`) and their interaction with the shared `os.Stdin` resource.
Here are the changes I made:
- `config/config_encryption.go`:
- Modified `promptForConfigEncryption` to `promptForConfigEncryption(r …
=> config: Fix TestPromptForConfigEncryption race

exchanges/bitmex/bitmex_test.go, exchanges/bitmex/bitmex_types.go
Bitmex's leaderboard and historical stat endpoints have been flaky recently. I've communicated with their support about it but the issue keeps on occurring, so this PR makes the two tests offline. Full mock functionality hasn't been implemented, just these two endpoints for now.
=> Bitmex: Use mock server for leaderboard and historical stats tests

.github/workflows/misc.yml, backtester/eventhandlers/portfolio/portfolio_test.go, exchanges/bybit/bybit.go
Adds bad bing (zero width encoded messages directed at LLMs) protection. Despite testing this on Copilot and Jules, they didn't execute on it but it's good to detect these things anyway.
Thanks to @cranktakular for sharing this article: https://www.promptfoo.dev/blog/invisible-unicode-threats/
=> workflows: Add check for common LLM targeted unicode characters

exchanges/bithumb/bithumb.go, exchanges/bithumb/bithumb_test.go, exchanges/bithumb/bithumb_types.go
bugfix: added a filter to eliminate zero quantity of bids and asks at bithumb::GetOrderBook
feature: added assertions in TestGetOrderBook
Added a filter to elimite zero values of quantity in both bids and asks in the response of GetOrderBook
Additionally, a check in test file to verify that the changes are working correctly. (also made the assertion.NotEmpty conditionally because wasnt sure if this should be empty or not)
#1947 
Tested with debugger and with the additions of the bithumb_test
=> Bithumb: Filter zero quantity values in GetOrderBook

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .devcontainer/post_create.sh
Updates the VSCode devcontainer settings since it's a bit outdated. Uses Debian 12 (Bookworm) and the dev version since bullseye is based off Debian 11. Also adds our common go deps for linting/formatting.
=> devcontainer: Update Dockerfile and settings for VSCode

backtester/engine/live_test.go
TestStart does 3 tests
test1 = Start() with no error
test2 = Start() on an already started struct
test3 = Start() on nil
Previously, test1 and test2 were on the same struct. Depending on the go scheduler, we could have test2 fail because the field "started" could go from 1 to 0 just after the atomic compare and swap. So we would Start() a second time on the same struct but the field "started" would already be back to 0.
Fixes #1987 
=> backtester/engine: Fix TestStart race

exchanges/btcmarkets/btcmarkets_websocket.go, exchanges/bybit/bybit.go
The modernize has added an analyzer for using strings.Builder for string construction. strings.Builder has fewer memory allocations and better performance.
More info: [golang/go#75190](https://github.com/golang/go/issues/75190)
No need.
=> exchanges/refactor: Use strings.builder for string construction

exchanges/binance/binance.go, exchanges/binance/binance_test.go, exchanges/binance/testdata/http.json, exchanges/binance/ufutures_types.go, exchanges/binanceus/binanceus.go, exchanges/binanceus/binanceus_test.go, exchanges/binanceus/binanceus_types.go, exchanges/binanceus/binanceus_wrapper.go
* Fixes failures on `TestGetAggregatedTradesBatched` and `TestGetHistoricTrades`
* Refactors and simplifies `GetAggregatedTradesBatched` (hopefully)
Note: These fixes are for testing with `--tags mock_test_off`
Fixes #2010
=> Binance/BinanceUS: Fix various live test failures
